### ISSUE TITLE
FEATURE REQUEST: Binary Releases for Windows

### ISSUE THREAD

**Issue by notcasper00** [NUWCDIVNPT/stig-manager#1032]
Will any of the newer binaries be released for Windows? Starting from v1.3.7, the Windows binary release was missing as part of the new source code. Was wondering if support was stopped for the Windows binaries. 
```[tasklist]
### Tasks
```

**Comment by cd-rite** [comment]
@notcasper00 Ah, just an oversight, thank you for pointing it out! I've attached the binaries to the releases now.
