### ISSUE TITLE
Bug: CKL Upload Workflow Results in Error if Insufficient Permissions for Select Changes

### ISSUE THREAD

**Issue by jeremygifford** [NUWCDIVNPT/stig-manager#1044]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version of STIG Manager?

- [X] I am using the latest [Release](https://github.com/NUWCDIVNPT/stig-manager/releases).
- [ ] I am NOT using the latest [Release](https://github.com/NUWCDIVNPT/stig-manager/releases). I am aware that the first thing I will be asked to do is update the application so that I have the latest bugfixes.

### Where are you experiencing the issue?

- [X] API
- [X] UI or other client
- [ ] Deployment
- [ ] Elsewhere

### Current Behavior

If a user without sufficient permissions to create new assets or STIG-to-asset associations tries to upload a CKL that doesn't match what's already exists in the collection, UI upload workflow is partially broken with unfriendly backend error messages.

### Expected Behavior

Upload UI workflow shows which CKLs imported successfully and which failed, and for what reason (such as insufficient permissions). Allow option of completing workflow with successful CKLs (ignore failures).

### Steps To Reproduce

1. In version 1.3.8 on NREN, change user permission to 'Full' for collection
2. Upload a CKL for a new asset or asset/STIG pairing

### Can you provide screenshots, logs, or other useful artifacts?

{"sourceStack":"    at  (src/SM/Error.js:207:42)\n    at  (src/SM/Error.js:207:42)\n    at loadData (src/SM/ReviewsImport.js:2633:39)\n    at updateStatusGrid (src/SM/ReviewsImport.js:2591:28)\n    at await (src/SM/ReviewsImport.js:1585:16)\n","name":"TypeError","message":"Cannot read properties of undefined (reading 'metaData')","stack":"TypeError: Cannot read properties of undefined (reading 'metaData')\n    at Ext.data.JsonReader.readRecords (https://stigman.nren.navy.mil/ph/ext/ext-all.js:21:340095)\n    at constructor.loadData (https://stigman.nren.navy.mil/ph/ext/ext-all.js:21:319440)\n    at l (https://stigman.nren.navy.mil/ph/js/stig-manager.min.js:294:3790)\n    at S.c [as addHandler] (https://stigman.nren.navy.mil/ph/js/stig-manager.min.js:294:3263)\n    at async S.handler (https://stigman.nren.navy.mil/ph/js/stig-manager.min.js:282:31289)","env":{"version":"1.3.8","apiBase":"/ph/api","welcome":{"image":"https://stigman.nren.navy.mil/images/ph.png","title":"","message":"","link":""},"commit":{"branch":"main","sha":"02a712aee0","tag":"na","describe":"1.3.8"},"oauth":{"authority":"https://stigman.nren.navy.mil/auth/realms/ph-stigman","clientId":"ph-stig-manager","refreshToken":{"disabled":false},"extraScopes":"","scopePrefix":"","claims":{"scope":"scope","username":"preferred_username","servicename":"clientId","name":"name","privileges":"['realm_access']?.['roles']","email":"email"}}}}

{"name":"ExtRequestError","method":"POST","url":"/ph/api/assets","status":403,"responseText":"{\"error\":\"User has insufficient privilege to complete this request.\",\"stack\":\"PrivilegeError: User has insufficient privilege to complete this request.\\n    at createAsset (/home/node/controllers/Asset.js:36:13)\\n    at Layer.handle [as handle_request] (/home/node/node_modules/express/lib/router/layer.js:95:5)\\n    at next (/home/node/node_modules/express/lib/router/route.js:144:13)\\n    at Route.dispatch (/home/node/node_modules/express/lib/router/route.js:114:3)\\n    at Layer.handle [as handle_request] (/home/node/node_modules/express/lib/router/layer.js:95:5)\\n    at /home/node/node_modules/express/lib/router/index.js:284:15\\n    at Function.process_params (/home/node/node_modules/express/lib/router/index.js:346:12)\\n    at next (/home/node/node_modules/express/lib/router/index.js:280:10)\\n    at Function.handle (/home/node/node_modules/express/lib/router/index.js:175:3)\\n    at router (/home/node/node_modules/express/lib/router/index.js:47:12)\\n    at operationHandlersMiddleware (/home/node/node_modules/express-openapi-validator/dist/openapi.validator.js:186:28)\\n    at Layer.handle [as handle_request] (/home/node/node_modules/express/lib/router/layer.js:95:5)\\n    at trim_prefix (/home/node/node_modules/express/lib/router/index.js:328:13)\\n    at /home/node/node_modules/express/lib/router/index.js:286:9\\n    at Function.process_params (/home/node/node_modules/express/lib/router/index.js:346:12)\\n    at next (/home/node/node_modules/express/lib/router/index.js:280:10)\"}","responseHeaders":"access-control-allow-origin: *\r\ncontent-encoding: gzip\r\ncontent-type: application/json; charset=utf-8\r\ndate: Wed, 26 Jul 2023 17:52:33 GMT\r\netag: W/\"5da-UufhASSGQWVkR9IQbeGZ2o/l+6A\"\r\nstrict-transport-security: max-age=15724800; includeSubDomains\r\nvary: Accept-Encoding\r\nx-powered-by: Express\r\n","tokenParsed":{"exp":"1690394204 (2023-07-26 10:56:44)","iat":"1690393904 (2023-07-26 10:51:44)","auth_time":"1690391074 (2023-07-26 10:04:34)","jti":"8c35250c-fa05-491c-9b58-49757ef4dda8","iss":"https://stigman.nren.navy.mil/auth/realms/ph-stigman","aud":"account","sub":"72de01f4-128a-4566-8707-d2c0bb55d3e5","typ":"Bearer","azp":"ph-stig-manager","nonce":"69212d7b-3213-4b5d-aa3b-aba9f0bfcd3c","session_state":"b6d95ec0-719a-4ddf-9e6b-b358b886f46a","acr":"0","realm_access":{"roles":["offline_access","create_collection","uma_authorization","user","default-roles-ca-stigman"]},"resource_access":{"account":{"roles":["manage-account","manage-account-links","view-profile"]}},"scope":"stig-manager:stig:read email profile stig-manager:user:read stig-manager:collection","sid":"b6d95ec0-719a-4ddf-9e6b-b358b886f46a","email_verified":false,"name":"Jeremy Gifford","preferred_username":"jeremy.gifford","given_name":"Jeremy","family_name":"Gifford"},"detail":{"message":"POST /ph/api/assets\n{\"error\":\"User has insufficient privilege to complete this request.\",\"stack\":\"PrivilegeError: User has insufficient privilege to complete this request.\\n    at createAsset (/home/node/controllers/Asset.js:36:13)\\n    at Layer.handle [as handle_request] (/home/node/node_modules/express/lib/router/layer.js:95:5)\\n    at next (/home/node/node_modules/express/lib/router/route.js:144:13)\\n    at Route.dispatch (/home/node/node_modules/express/lib/router/route.js:114:3)\\n    at Layer.handle [as handle_request] (/home/node/node_modules/express/lib/router/layer.js:95:5)\\n    at /home/node/node_modules/express/lib/router/index.js:284:15\\n    at Function.process_params (/home/node/node_modules/express/lib/router/index.js:346:12)\\n    at next (/home/node/node_modules/express/lib/router/index.js:280:10)\\n    at Function.handle (/home/node/node_modules/express/lib/router/index.js:175:3)\\n    at router (/home/node/node_modules/express/lib/router/index.js:47:12)\\n    at operationHandlersMiddleware (/home/node/node_modules/express-openapi-validator/dist/openapi.validator.js:186:28)\\n    at Layer.handle [as handle_request] (/home/node/node_modules/express/lib/router/layer.js:95:5)\\n    at trim_prefix (/home/node/node_modules/express/lib/router/index.js:328:13)\\n    at /home/node/node_modules/express/lib/router/index.js:286:9\\n    at Function.process_params (/home/node/node_modules/express/lib/router/index.js:346:12)\\n    at next (/home/node/node_modules/express/lib/router/index.js:280:10)\"}","response":{"tId":39,"status":403,"statusText":"","responseText":"{\"error\":\"User has insufficient privilege to complete this request.\",\"stack\":\"PrivilegeError: User has insufficient privilege to complete this request.\\n    at createAsset (/home/node/controllers/Asset.js:36:13)\\n    at Layer.handle [as handle_request] (/home/node/node_modules/express/lib/router/layer.js:95:5)\\n    at next (/home/node/node_modules/express/lib/router/route.js:144:13)\\n    at Route.dispatch (/home/node/node_modules/express/lib/router/route.js:114:3)\\n    at Layer.handle [as handle_request] (/home/node/node_modules/express/lib/router/layer.js:95:5)\\n    at /home/node/node_modules/express/lib/router/index.js:284:15\\n    at Function.process_params (/home/node/node_modules/express/lib/router/index.js:346:12)\\n    at next (/home/node/node_modules/express/lib/router/index.js:280:10)\\n    at Function.handle (/home/node/node_modules/express/lib/router/index.js:175:3)\\n    at router (/home/node/node_modules/express/lib/router/index.js:47:12)\\n    at operationHandlersMiddleware (/home/node/node_modules/express-openapi-validator/dist/openapi.validator.js:186:28)\\n    at Layer.handle [as handle_request] (/home/node/node_modules/express/lib/router/layer.js:95:5)\\n    at trim_prefix (/home/node/node_modules/express/lib/router/index.js:328:13)\\n    at /home/node/node_modules/express/lib/router/index.js:286:9\\n    at Function.process_params (/home/node/node_modules/express/lib/router/index.js:346:12)\\n    at next (/home/node/node_modules/express/lib/router/index.js:280:10)\"}","responseXML":null},"options":{"url":"/ph/api/assets","method":"POST","headers":{"Content-Type":"application/json;charset=utf-8","Authorization":"<removed>","X-Requested-With":"XMLHttpRequest"},"jsonData":{"name":"testdevice123","description":null,"ip":"172.16.150.43","fqdn":null,"mac":null,"noncomputing":false,"metadata":{"cklRole":"None"},"collectionId":"2","stigs":["Cisco_IOS_XE_Switch_RTR_STIG"]}}},"sourceStack":"    at  (src/overrides.js:297:18)\n    at await (src/SM/ReviewsImport.js:2654:29)\n    at await (src/SM/ReviewsImport.js:2590:48)\n    at await (src/SM/ReviewsImport.js:1585:16)\n","message":"Ext.Ajax.request() failed","stack":"ExtRequestError: Ext.Ajax.request() failed\n    at Ext.data.Connection.requestPromise (https://stigman.nren.navy.mil/ph/js/stig-manager.min.js:252:109)\n    at async d (https://stigman.nren.navy.mil/ph/js/stig-manager.min.js:294:4074)\n    at async S.c [as addHandler] (https://stigman.nren.navy.mil/ph/js/stig-manager.min.js:294:3267)\n    at async S.handler (https://stigman.nren.navy.mil/ph/js/stig-manager.min.js:282:31289)","env":{"version":"1.3.8","apiBase":"/ph/api","welcome":{"image":"https://stigman.nren.navy.mil/images/ph.png","title":"","message":"","link":""},"commit":{"branch":"main","sha":"02a712aee0","tag":"na","describe":"1.3.8"},"oauth":{"authority":"https://stigman.nren.navy.mil/auth/realms/ph-stigman","clientId":"ph-stig-manager","refreshToken":{"disabled":false},"extraScopes":"","scopePrefix":"","claims":{"scope":"scope","username":"preferred_username","servicename":"clientId","name":"name","privileges":"['realm_access']?.['roles']","email":"email"}}}}

### Describe your Environment

```markdown
- Hosting: NREN
- Browser: Edge
- OS: Windows 10
- Node:
- npm:
```

**Comment by jeremygifford** [comment]
After submitting, I realized that normally users with 'Full' permissions don't even have the modify gear option next to the collection to allow getting to the import CKLs workflow. The above issue is only possible because I was downgrading the user permissions after opening up the modify collection window and before signing out/signing back in again to where the permission change would fully take effect in the UI and not just the backend API.

This brings up another UI shortcoming, 'Full' permission users should be able to still import CKLs for the asset-to-STIG associations they manage, even if they shouldn't be able to import new assets or associations.

**Comment by cd-rite** [comment]
Hi @jeremygifford Thanks for the report. As you guessed, this is an artifact of the fact that they no longer had access to the endpoints used by the interface they were in. They wouldn't have to logout/in again, a refresh of the page would reflect their new access levels. 
This isn't perfectly desirable behavior, but we are accepting it for now.
Thanks!
