### ISSUE TITLE
FEATURE REQUEST: 'Proto SAP' like Exportable Report that Shows STIG to Asset Pairing Collection Wide

### ISSUE THREAD

**Issue by jeremygifford** [NUWCDIVNPT/stig-manager#1049]
**Is your feature request related to a problem? Please describe.**
One of the core documents to the Navy RMF risk assessment process is the 'Security Assessment Plan' (SAP). The main purpose of the SAP is to record what types of security assessments are going to be conducted and to what assets they are going to be conducted against. (See template) Maintaining that association table can be a time consuming task.

**Describe the solution you'd like**
A downloadable .csv file with a column listing all STIGs in the collection and a column with all asset names associated with that STIG.

**Describe alternatives you've considered**
Currently a manual process of organizing data mostly by hand.

**Additional context**
Proposed export .csv example template:
[example_STIG_to_Asset_Map.csv](https://github.com/NUWCDIVNPT/stig-manager/files/12295619/example_STIG_to_Asset_Map.csv)

The template has the STIGs addressed by their ID value but other columns would be fine too (such as the one for title and one for version number) 

Actual current Navy SAP template if curious:
[Navy RMF_Security_Assessment_Plan_Template v3.xlsx](https://github.com/NUWCDIVNPT/stig-manager/files/12295594/Navy.RMF_Security_Assessment_Plan_Template.v3.xlsx)

A nice-to-have feature for the .csv export would be some extra generation-time logic to avoid Microsoft Excel single-cell max character count and max newline limitations.

**Comment by cd-rite** [comment]
Development approach:

"Exports" From "Inventory" box in Collection Dash:
offer download pivoted by Asset or STIG, with .csv or json formats
One line per Asset or STIG, with appropriate column aggregating

download Asset-pivoted list
  - use existing endpoint: GET assets/  with "stigs" projection
download stigs-pivoted list
  - add (and use) "assets" projection to GET collection/{collectionId}/stigs

**Comment by csmig** [comment]
Opened PR #1082 for this issue.

After observing a wide variation in "maximum newline" behavior across spreadsheets, including legacy Excel versions and Microsoft 365 Excel, I have not implemented the "maximum newline per cell" idea above. Microsoft 365 in particular appeared to have no problem handling >253 newlines in a cell. Instead, the PR allows a user to choose an inter-cell delimiter, I think some use cases will prefer a comma separator over a newline separator.

**Comment by dtester1** [comment]
Great to see this moving forward.  I think this will be helpfull for hardware lists and SAP submittals.
