### ISSUE TITLE
FEATURE REQUEST: Asset Copy function

### ISSUE THREAD

**Issue by cd-rite** [NUWCDIVNPT/stig-manager#1057]
Add the ability to Copy an asset from one Collection to another.
**If Asset with that name does not exist in destination collection:**
Copied Asset should have same properties as origin Asset.

**Base behavior:**
Labels: Create in destination Collection if they do not exist.
Grants(lvl1) : Do not create in destination Collection. 
Reviews:
- All reviews that are mapped to any Revision of selected STIG(s).
- Reviews get timestamp of clone (old review gets put into history record)
- Reviews get unsubmitted if they don't meet destination collection setting requirements

**User selectable Options:**
STIG Assignments & Reviews: None, All, or selected STIGs

**Asset with same name exists in destination collection options:**
Clobber all Asset properties/Change no Asset Properties (fqdn, mac, etc)
Rename (create copy with new name in destination collection)
Just copy all/selected STIGs and their Reviews (Update existing Reviews for selected STIGs, creating a new history record, etc)
Create STIG assignments that don't exist in destination.
OR
Delete existing Asset in Destination, replace with Asset from Source

(**stretch goal:** create a copy in same Collection with a name change?)

**Comment by dtester1** [comment]
I know you are all in maintenace phase but do we have any current timeline on this piece?  This is the last of three pieces I see for completing the workflow for utilization for Annual Reviews/renewal snapshots.  The first two pieces (cloning and revision pining) seem like the work as intended, so looking forward to this so we can roll this complete solution out.

**Comment by csmig** [comment]
I've begun to code this and am pushing commits to https://github.com/csmig/stig-manager/tree/export-into.

**Comment by csmig** [comment]
The requirements and scope of this feature request have been heavily modified during discussions not held on GitHub. The associated PR implements the final set of requirements hashed out by the team.
