### ISSUE TITLE
Health Check endpoints to satisfy DoD guidance

### ISSUE THREAD

**Issue by cd-rite** [NUWCDIVNPT/stig-manager#108]
**Is your feature request related to a problem? Please describe.**
DoD Container Image Creation and Deployment Guide requires Health Checks

**Describe the solution you'd like**
New endpoint for health check or specify existing endpoint for use as health check.
Document asks for two checks:
Liveness Probe
Readiness Probe

**Additional context**
DoD Container guide:
https://dl.dod.cyber.mil/wp-content/uploads/devsecops/pdf/DevSecOps_Enterprise_Container_Image_Creation_and_Deployment_Guide_2.6-Public-Release.pdf

3.8 The Container Must Have a Liveness Probe
A liveness probe checks for instances in which a container has run into a deadlock state. The
container will appear as healthy from the process health check's point of view but will not be in a
usable state. This check is performed at the container level for healthiness.
3.9 The Container Must Have a Readiness Probe
Process health checks and liveness probes are helpful to determine if a container is unhealthy and
needs to be restarted, however restarting does not always make the container healthy and may
keep the container in an apparent unhealthy state (for example, when the container is starting and
is not ready to receive any workload, including the health check or liveness probe). The
readiness probe can also be used to monitor if a container is overloaded, latency has increased,
and the container needs to be shielded from additional workloads.

**Comment by csmig** [comment]
AFAIK, Liveness and Readiness probes are not implemented in the Dockerfile, they are meant to be endpoints called by an orchestration platform like k8s . I suggest the endpoint `/op/configuration` is suitable for both purposes for now.

**Comment by csmig** [comment]
However, the DISA guidance also includes this section:

2.6 The Container Image Must Be Built With a Process Health Check
Ensuring a container service is still executing and handling workloads is necessary to validate
service availability. Adding the health check instruction, HEALTHCHECK, within Docker, to
the container image, provides a mechanism for the container platform to periodically check the
running container instance against that instruction to ensure the instance is still working.

**Comment by csmig** [comment]
I pushed the commit above to establish a Dockerfile HEALTHCHECK instruction.

The commit also introduces a build argument that specifies a base image for the FROM instruction. This will allow us to easily specify an Iron Bank base image within our CD pipeline and support issue #122.

**Comment by csmig** [comment]
Merged with PR #108
