### ISSUE TITLE
Add more comprehensive constraints, common typedefs, to OAS spec

### ISSUE THREAD

**Issue by cd-rite** [NUWCDIVNPT/stig-manager#1097]
- Add more keywords to better describe expected requests:
  - add uniqueItems: true and minItems: 1 for arrays where appropriate
- restrict string lengths where currently left unbound
- Define common types for items that appear in multiple schemas:
  - ie. define a `StatusText` type to replace instances where the `text` property of a `status` object is defined `String512Nullable` in-line. 
  - same for ruleId, benchmarkId, etc.
  - BenchmarkId is already defined (but as a `string`. look to database columns for size reference), and it isn't actually used in any schema definitions. 
  - Some definitions conflict... Rule title is defined as `StringMax` in some spots and `string` in others, but in the db it's varchar(1000)

**Comment by csmig** [comment]
Closed by #1257
