### ISSUE TITLE
FEATURE REQUEST:  label interface

### ISSUE THREAD

**Issue by Sir-STIGalot** [NUWCDIVNPT/stig-manager#1102]
I have some small gripes on how the assignment of labels. 
1. Miskicking off the checkboxes removes all other selections 
2. The table for adding assets to a label only shows the asset name and label fields having access to more fields would be helpful
3. The color dropper icon in dark mode is not apparent
4. It would be a nice to have if from the asset tab on a collection main page if I the label column was a drop down where you could select from already created labels.

**Comment by cd-rite** [comment]
Thank you for the suggestion! 
1&2: We are working on a new interface for Label and STIG assignments, which will include additional filterable columns and less-prone-to-misclick mechanic.
3: I created a separate issue for the dark mode color picking icon: #1113
4: Not entirely sure what you mean by this... Was this the suggestion mentioned at Office Hours about offering label filtering from the navigation tree on the left?  Most likely, this will have to be it's own issue.
