### ISSUE TITLE
CKL Fails validation after system hardening

### ISSUE THREAD

**Issue by jgromoll** [NUWCDIVNPT/stig-manager#1110]
Prior to system hardening was able to create CKL for RHEL8 using ES 1.2307.3 and RHEL8 V1R11 STIG content. After hardening ES errors with " failed schema validation.  Moving to /tmp/Evaluate-STIG/Bad_CKL.         Please report issues to https://spork.navsea.navy.mil/nswc-crane-division/evaluate-stig/-/issues "

**Comment by cd-rite** [comment]
Hi @jgromoll Your issue seems to be regarding Evaluate STIG, which is a separate project from STIG Manager OSS.
You would need to submit your report to that team using the issue link you included in your comment.
Thanks.
