### ISSUE TITLE
FEATURE REQUEST: Risk Accepted Button [QoL Feature]

### ISSUE THREAD

**Issue by MayhemForce** [NUWCDIVNPT/stig-manager#1123]
**Describe the solution you'd like**
I've used STIG manager for about 8+ months at this point and my job is ISSO, so we utilize things like eMASS for RMF.

My feature request is geared towards adding a button of some sort, or an identifier, to STIG checks that are OPEN that we as an enclave have Risk Accepted, or pushed for Risk Acceptance.

These items would still be OPEN for .ckl purposes, but it would be nice to know easily when the items have already been Risk Accepted and will forever stay OPEN on our end. We have over 100k+ checks across our enclave, so keeping up with the status of OPEN items as an ISSO is a task in itself.

Hopefully my request makes sense!

**Comment by cd-rite** [comment]
Hi @MayhemForce I ran this by our sponsor and they decided it is out of scope for the project at this time, since they do not use "Risk Accepted" as part of their process. 
Thanks for the suggestion, though!
