### ISSUE TITLE
POST Asset creation will accept label IDs that are not part of the specified Collection

### ISSUE THREAD

**Issue by cd-rite** [NUWCDIVNPT/stig-manager#1149]
Replicate:
Create an Asset via POST specifying a labelId that is a valid UUID but is not an actual labelId for that Collection. 
Effect:
GETs for that Asset will respond with that UUID listed as a Label, but of course the labelID does not resolve to an actual Label.
Causes an error in UI when Asset is loaded:

`{"name":"TypeError","message":"Cannot read properties of undefined (reading 'extraCls')","stack":"TypeError: Cannot read properties of undefined (reading 'extraCls')\n    at tpl.compiled (eval at compileTpl (http://localhost:64001/ext/ext-all-debug-w-comments.js:14988:9), <anonymous>:1:105)\n    at Ext.XTemplate.applyTemplate (http://localhost:64001/ext/ext-all-debug-w-comments.js:14998:37)\n    at Object.labels [as renderer] (http://localhost:64001/js/SM/ColumnFilters.js:411:35)\n    at buildDynamicValues (http://localhost:64001/js/SM/ColumnFilters.js:194:54)\n    at constructor.<anonymous> (http://localhost:64001/js/SM/ColumnFilters.js:249:9)\n    at EXTUTIL.Event.fire (http://localhost:64001/ext/ext-all-debug-w-comments.js:532:34)\n    at constructor.fireEvent (http://localhost:64001/ext/ext-all-debug-w-comments.js:173:31)\n    at constructor.loadRecords (http://localhost:64001/ext/ext-all-debug-w-comments.js:37791:14)\n    at Ext.data.HttpProxy.onRead (http://localhost:64001/ext/ext-all-debug-w-comments.js:40164:28)\n    at Ext.data.HttpProxy.<anonymous> (http://localhost:64001/ext/ext-all-debug-w-comments.js:40119:22)","env":{"version":"1.3.13","apiBase":"/api","welcome":{"image":"","title":"","message":"","link":""},"commit":{"branch":"na","sha":"na","tag":"na","describe":"na"},"oauth":{"authority":"http://localhost:8080/realms/stigman","clientId":"stig-manager","refreshToken":{"disabled":false},"extraScopes":"","scopePrefix":"","claims":{"scope":"scope","username":"preferred_username","servicename":"clientId","name":"name","privileges":"['realm_access']?.['roles']","email":"email"}}}}`

**Comment by csmig** [comment]
Could revise the query [here](https://github.com/NUWCDIVNPT/stig-manager/blob/c679109169ee2b0774a497d2ec2f9b430e3f4700/api/source/service/mysql/AssetService.js#L435-L442)

```
INSERT INTO collection_label_asset_map (assetId, clId) 
  SELECT
    ?,
    clId
  FROM
    collection_label
  WHERE
    uuid IN (?)
    and  collectionId = ? <=== added predicate
```

with a query parameter added for `collectionId`. This which would silently ignore unmappable labelIds.
