### ISSUE TITLE
GET User/{userId} -> provide a Roles projection

### ISSUE THREAD

**Issue by cd-rite** [NUWCDIVNPT/stig-manager#117]
Provide a Roles projection available to users that can not use the "statistics" projection for users.
Role info is available in "lastClaims" portion of Statistics projection, but only to elevated admins.
Non-elevated users may have a need to know who the admins are on their system.

A role projection for /user may be convenient as well, rather than requiring processing of the entire statistics->lastClaims-> roles nested objects.

**Comment by csmig** [comment]
@cd-rite Let's close this for now, when/if a client comes along that requires this we can reopen
