### ISSUE TITLE
FEATURE REQUEST: Support for the USMC MCCAST POAM export in STIG Manager

### ISSUE THREAD

**Issue by haynesjs** [NUWCDIVNPT/stig-manager#1174]
**Is your feature request related to a problem? Please describe.**

- We want to be able to export POAM from STIG Manger in MCCAST format and currently there is no drop down for that format. MCCAST is what the USMC uses for ATO packages and to import the format has to contain certain fields.

**Describe the solution you'd like**

I work for the USMC and we need the POAM export feature in STIG Manager to have a drop down where you can select MCCAST.   We can provide the fields that MCCAST requires or provide you a sample sheet with the fields we would like so there is seamless export and import from STIG-Manger strait into MCCAST which the USMC uses for ATO packages.

**Describe alternatives you've considered**

**Additional context**

**Comment by cd-rite** [comment]
Hi @haynesjs Our Navy sponsors are typically reluctant to support processes that are not part of their baseline Navy-RMF pipeline, which uses eMASS.  Sounds like that may be the equivalent to your MCCAST?

Even our Navy POAM creation is usually not a straight import into eMASS, since there are fields or worksheets that are outside of STIG Manager's purview and require further manipulation by RMF Validators.

That said, feel free to provide a sample file or field set showing what you are looking for. There may be some correspondence between that and something we can already generate.

**Comment by haynesjs** [comment]
[MCCAST_POAM Example.csv](https://github.com/NUWCDIVNPT/stig-manager/files/13888547/MCCAST_POAM.Example.csv)

**Comment by haynesjs** [comment]
Above is an example of the fields we need for import to MCCAST.  Just let me know.  Thanks

**Comment by csmig** [comment]
Although the core team cannot work this feature at this time, perhaps those interested could open a PR that implements the feature in the API? The PR would need to address the following:
- provide an MCCAST POAM template XLSX that follows the example of [the eMASS POAM template](https://github.com/NUWCDIVNPT/stig-manager/raw/main/api/source/utils/poam-template.xlsx).
- add code that populates the template to [the `serializers.js` source file](https://github.com/NUWCDIVNPT/stig-manager/blob/main/api/source/utils/serializers.js)
- Add a query parameter to the OAS definition of [the Collection POAM endpoint](https://github.com/NUWCDIVNPT/stig-manager/blob/eba4c0afdc787c640a334954c4f5818e4a1483b1/api/source/specification/stig-manager.yaml#L2400-L2448) to choose between eMASS and MCCAST style, defaulting to eMASS.
- Update [this endpoint handler](https://github.com/NUWCDIVNPT/stig-manager/blob/eba4c0afdc787c640a334954c4f5818e4a1483b1/api/source/controllers/Collection.js#L177-L212) to accept the new query parameter and call the new template population functions

We'd be willing to work with the contributor during the process of getting the PR in good shape for merging. Afterwards, we could integrate the updated endpoint into the Web UI.
