### ISSUE TITLE
STIG-Manager startup fails to setup dependencies

### ISSUE THREAD

**Issue by gregglowrimore** [NUWCDIVNPT/stig-manager#1175]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version of STIG Manager?

- [X] I am using the latest [Release](https://github.com/NUWCDIVNPT/stig-manager/releases).
- [ ] I am NOT using the latest [Release](https://github.com/NUWCDIVNPT/stig-manager/releases). I am aware that the first thing I will be asked to do is update the application so that I have the latest bugfixes.

### Where are you experiencing the issue?

- [ ] API
- [ ] UI or other client
- [X] Deployment
- [ ] Elsewhere

### Current Behavior

I am deploying the latest binary distribution onto an EC2 in AWS GovCloud. Keycloak is running on this same node, as is MySQL. When starting STIG-Manager, I get "Failed to setup dependencies" and an immediate shutdown of STIG-Manager. Even with logging at '4' - there is inadequate information on how to fix this nor is there any indication of what's wrong to begin with.

### Expected Behavior

STIG-Manager should be up and running, listening on port 54000

### Steps To Reproduce

See above

### Can you provide screenshots, logs, or other useful artifacts?

```
[root@ngg-stage-stigmanager-server stig-manager]# ./stig-manager.sh
{"date":"2024-01-08T19:54:20.092Z","level":3,"component":"index","type":"starting","data":{"version":"1.3.14","env":{"STIGMAN_DB_PASSWORD":"*","STIGMAN_DB_USER":"stigman","STIGMAN_CLIENT_EXTRA_SCOPES":"offline_access","STIGMAN_DB_TLS_CERT_FILE":"/etc/nginx/ssl/ngg-stage-stigmanager-server.ssc.lmco.com.crt.pem","STIGMAN_CLIENT_KEYCLOAK_CLIENTID":"stig-manager","STIGMAN_DB_TLS_KEY_FILE":"/etc/nginx/ssl/ngg-stage-stigmanager-server.ssc.lmco.com.key.pem","STIGMAN_INIT_IMPORT_STIGS":"true","STIGMAN_LOG_LEVEL":"4","STIGMAN_DB_TLS_CA_FILE":"/etc/pki/ca-trust/source/anchors/LMChain_pem.pem","STIGMAN_OIDC_PROVIDER":"https://ngg-stage-stigmanager-server.ssc.lmco.com:8443/realms/stigman","STIGMAN_JWT_PRIVILEGES_CLAIM":"realm_access.roles"},"dirname":"/snapshot/stig-manager/api/source","cwd":"/opt/stig-manager"}}
{"date":"2024-01-08T19:54:20.096Z","level":3,"component":"index","type":"configuration","data":{"version":"1.3.14","commit":{"branch":"na","sha":"na","tag":"na","describe":"na"},"settings":{"lastAccessResolution":60,"responseValidation":"none"},"client":{"clientId":"stig-manager","authority":"https://ngg-stage-stigmanager-server.ssc.lmco.com:8443/realms/stigman","apiBase":"api","disabled":false,"directory":"../../client/dist","extraScopes":"offline_access","refreshToken":{"disabled":false},"welcome":{"image":"","message":"","title":"","link":""}},"docs":{"disabled":false,"docsDirectory":"../../docs/_build/html"},"http":{"address":"0.0.0.0","port":54000,"maxJsonBody":"31457280","maxUpload":"1073741824"},"database":{"type":"mysql","host":"localhost","port":3306,"schema":"stigman","username":"stigman","maxConnections":25,"tls":{"ca_file":"/etc/pki/ca-trust/source/anchors/LMChain_pem.pem","cert_file":"/etc/nginx/ssl/ngg-stage-stigmanager-server.ssc.lmco.com.crt.pem","key_file":"/etc/nginx/ssl/ngg-stage-stigmanager-server.ssc.lmco.com.key.pem"},"revert":false,"password":true},"swaggerUi":{"enabled":false,"authority":"https://ngg-stage-stigmanager-server.ssc.lmco.com:8443/realms/stigman","server":"http://localhost:54000/api","oauth2RedirectUrl":"http://localhost:54000/api-docs/oauth2-redirect.html"},"oauth":{"authority":"https://ngg-stage-stigmanager-server.ssc.lmco.com:8443/realms/stigman","claims":{"scope":"scope","username":"preferred_username","servicename":"clientId","name":"name","privileges":"['realm_access']?.['roles']","email":"email"}},"log":{"level":4,"mode":"combined"}}}
{"date":"2024-01-08T19:54:21.333Z","level":4,"component":"index","type":"client","data":{"client_static":"/snapshot/stig-manager/client/dist"}}
{"date":"2024-01-08T19:54:21.334Z","level":4,"component":"index","type":"client","data":{"message":"succeeded setting up client"}}
{"date":"2024-01-08T19:54:21.335Z","level":4,"component":"index","type":"client","data":{"message":"succeeded setting up documentation"}}
{"date":"2024-01-08T19:54:21.596Z","level":4,"component":"oidc","type":"discovery","data":{"metadataUri":"https://ngg-stage-stigmanager-server.ssc.lmco.com:8443/realms/stigman/.well-known/openid-configuration","attempt":1}}
{"date":"2024-01-08T19:54:21.631Z","level":1,"component":"index","type":"shutdown","data":{"message":"Failed to setup dependencies"}}
```

### Describe your Environment

```markdown
- Hosting: Hosting this ourselves.
- Browser: Firefox
- OS: RHEL8
- Node: ?? Do I need NodeJS installed?
- npm: ?? Do I need npm to accompany NodeJS? (Maybe this is my problem, no nodeJS on this system.)
```

**Comment by gregglowrimore** [comment]
I just installed these:

Node version: v10.24.0
npm version: v6.14.11

Same startup error.

**Comment by cd-rite** [comment]
Hi @gregglowrimore The binaries include Node, so you shouldn't need that installed on your system. (We don't have good insight into how many users deploy with our binaries, so most of our documentation is more Container-oriented).
Were you working with that setup with the previous version, or is this a new deployment?

We recently released 1.4.1, which should have a more informative error message for that "Failed to setup dependencies" log entry.

**Comment by gregglowrimore** [comment]
I started with the binary deployment setup and have stuck with it. I will have to check on that 1.4.1 release and report back by tomorrow. Thanks.

**Comment by gregglowrimore** [comment]
So deploying 1.4.1 does give more information (very grateful!) which now points to:
`{"date":"2024-01-08T21:17:44.148Z","level":1,"component":"index","type":"shutdown","data":{"message":"Failed to setup dependencies","error":{"errno":-2,"code":"ENOENT","path":"/snapshot/stig-manager/api/source/tls/etc/pki/ca-trust/source/anchors/LMChain_pem.pem","pkg":true,"name":"Error","message":"File '/**/stig-manager/api/source/tls/etc/pki/ca-trust/source/anchors/LMChain_pem.pem' was not included into executable at compilation stage. Please recompile adding it as asset or script.","stack":"Error: File '/**/stig-manager/api/source/tls/etc/pki/ca-trust/source/anchors/LMChain_pem.pem' was not included into executable at compilation stage. Please recompile adding it as asset or script.
at error_ENOENT (pkg/prelude/bootstrap.js:657:19)
at readFileFromSnapshot (pkg/prelude/bootstrap.js:1046:29)
at Object.readFileSync (pkg/prelude/bootstrap.js:1094:18)
at getPoolConfig (/snapshot/stig-manager/api/source/service/utils.js:44:25)
at Object.module.exports.initializeDatabase (/snapshot/stig-manager/api/source/service/utils.js:59:22)
at startServer (/snapshot/stig-manager/api/source/index.js:231:77)
at run (/snapshot/stig-manager/api/source/index.js:162:5)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at process.runNextTicks [as _tickCallback] (node:internal/process/task_queues:65:3)
at Function.runMain (pkg/prelude/bootstrap.js:1980:13)
at node:internal/main/run_main_module:17:47"}}}`

So what does that mean to me? Since I'm using the binary installers, what would I "recompile"???

**Comment by gregglowrimore** [comment]
Do if I remove my TLS CRT/KEY and LMChain_pem.pem from the stig-manager.sh script and try starting STIG Mgr up without those, I get a different error:

`{"date":"2024-01-08T22:02:00.483Z","level":1,"component":"index","type":"shutdown","data":{"message":"Failed to setup dependencies","error":{"message":"unable to verify the first certificate","name":"Error","stack":"Error: unable to verify the first certificate`

And:

`"code":"UNABLE_TO_VERIFY_LEAF_SIGNATURE","status":null}}}`

At the very end of the stack trace now.

**Comment by cd-rite** [comment]
@gregglowrimore 
Ah, I was about to ask if you had been running with TLS to the database before, or if that is new configuration?
I'm not sure that the binary versions would be able to access your cert material on your local disk.

**Comment by cd-rite** [comment]
Do you have the NODE_EXTRA_CA_CERTS envvar set? (This is for the Node environment, not STIGMan specific)

**Comment by gregglowrimore** [comment]
No. Shall I re-intro these TLS certs and set that envvar and retry?

**Comment by gregglowrimore** [comment]
Doing what I asked above, Back to the CERT/KEY/Chain not included into executable error again.

**Comment by gregglowrimore** [comment]
Wait a minute.... holding my breadth now..... I removed the CERT/KEY/Chain from stig-manager.sh but left the NODE_EXTRA_CA_CERTS defined in the environment, and attempted a stig-manager.sh run..... and it's holding now! Holy cow! You got it!

**Comment by cd-rite** [comment]
Oh, wow, great!!  
Though now you are stuck using username/pw for db access, without TLS, right? That's ok in some situations, but maybe not optimal.
Were you running the binary with TLS to the db successfully before 1.3.14?  We don't have explicit tests for the binary version using TLS to the db (Like I said, we put most of our efforts towards the containerized version!).

**Comment by gregglowrimore** [comment]
Now it appears to be back onto an NGINX config issue. Would you happen to have an example nginx.conf file on hand for STIG-Man?

Does STIG-Manager respond to https calls or strictly http callbacks?

**Comment by gregglowrimore** [comment]
I'm fine with username/pass for DB access. I am running Keycloak via HTTPS so I just assumed I'd run STIG-Man the same - given how today's web sites are MOSTLY https.

**Comment by cd-rite** [comment]
We respond to http, expecting the proxy to take care of https.
You had the `STIGMAN_DB_*****`    envvars set, so I thought you were addressing getting STIGMan talking to the **_database_** with those certs (which is optional).

**Comment by cd-rite** [comment]
We have a sample nginx config here:
https://github.com/NUWCDIVNPT/stigman-orchestration/tree/main/nginx
It's part of an overall sample Docker orchestration with reverse proxy, but the nginx portion should apply to your scenario as well.

**Comment by gregglowrimore** [comment]
Thanks! I'll have a look. I think I've been to that file before.

**Comment by gregglowrimore** [comment]
Also trying to setup a systemd start script for stig-manager, but how your stig-manager.sh is basically just setting ENVVARs and then calling the stig-manager-linuxstatic, -- systemd doesn't like that.

**Comment by cd-rite** [comment]
Ahh, I don't have experience with that, but you may need to set the envvars however systemd wants them, and then just call the application directly, without our script (the only purpose of the script is to set up those envvars, anyway)

**Comment by cd-rite** [comment]
@gregglowrimore I think we've resolved the STIGMan-specific issues you experienced, so I'll close this issue. 
Feel free to comment with any follow-up, but just ad an @cd-rite to the message so I get notified!
Thanks!
