### ISSUE TITLE
CKL(B) Results Imports showing zero results in all types

### ISSUE THREAD

**Issue by sara-k-99** [NUWCDIVNPT/stig-manager#1206]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version of STIG Manager?

- [ ] I am using the latest [Release](https://github.com/NUWCDIVNPT/stig-manager/releases).
- [X] I am NOT using the latest [Release](https://github.com/NUWCDIVNPT/stig-manager/releases). I am aware that the first thing I will be asked to do is update the application so that I have the latest bugfixes.

### Where are you experiencing the issue?

- [X] API
- [ ] UI or other client
- [ ] Deployment
- [ ] Elsewhere

### Current Behavior

Attempts to upload manually completed STIG reviews in the CKL(B) format is not importing reviews on any rule. The rule IDs match up between the CKL(B) and the current STIGs in the STIGManager library. There is no outputted error from the interface. 

![image](https://github.com/NUWCDIVNPT/stig-manager/assets/51962821/5e43d15f-7b57-49bb-b6b0-be6e031f0764)

Opening the same .cklb in the STIGViewer 3 shows 29 rules that have all been reviewed. 

This seems to occur regardless of the collection, STIG, or .cklb attempted uploads are related to. The proxy max body size has already been increased to successfully import larger STIGs like that of RHEL8. These checklists were converted from .ckl to .cklb with STIGViewer3.

STIG Library imports are able to upload with no issues. 

### Expected Behavior

Following the [collection builder process](https://stig-manager.readthedocs.io/en/latest/user-guide/user-guide.html#collection-builder-process), I expect to be able to upload multiple CKL(B) reviews for assets in a collection, displaying the completed rules that were reviewed manually.

### Describe your Environment

```markdown
- Hosting: Hosting 1.4.0
- Browser: Chrome
- OS: containerized
- Node:
- npm:
```

**Comment by cd-rite** [comment]
Hi @sara-k-99 We were able to add some processing to account for the STIG Viewer .cklb anomalies you found.  Our latest release, 1.4.3, should handle them fine, now.
