### ISSUE TITLE
Issue noticed during mass asset deletion

### ISSUE THREAD

**Issue by vogtjob** [NUWCDIVNPT/stig-manager#1209]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version of STIG Manager?

- [X] I am using the latest [Release](https://github.com/NUWCDIVNPT/stig-manager/releases).
- [ ] I am NOT using the latest [Release](https://github.com/NUWCDIVNPT/stig-manager/releases). I am aware that the first thing I will be asked to do is update the application so that I have the latest bugfixes.

### Where are you experiencing the issue?

- [X] API
- [ ] UI or other client
- [ ] Deployment
- [ ] Elsewhere

### Current Behavior

We are noticing some interesting issues when performing a mass delete of assets.  While the delete is occurring other user access to basically any functionality within the is stalled.  For Example:  A user can select a collection, but no Benchmarks will possible not show up.  Or, if the Benchmarks are there and the user selects one, the Checklist's won't appear in the lower pane.  Once the delete is completed, all user functionality resumes.  We do notice that a large percentage of CPU is consumed by mysql during the deletion and increased resources, but this did not resolve the issues noticed.  

At this point, I'm not sure if this is something that is related to our configuration or an API feature.

In the past, the tablerows metrics were requested.  Below are for our instance.

asset: 35,518
collection: 39
review: 16,575,698
review_history: 6,627,497

Thank you.

### Expected Behavior

Full user functionality is available during mass deletion of assets.

### Steps To Reproduce

Perform a mass deletion of assets.  See interesting behavior.

### Describe your Environment

```markdown
- Hosting: container configuration
- Browser: Edge, Chrome
- OS: RHEL 8, podman containers
- Node:
- npm:
```

**Comment by vogtjob** [comment]
We are running 1.4.2.

**Comment by csmig** [comment]
Thanks for verifying you're on the latest release.

At the moment, we haven't implemented an endpoint that accepts multiple assetIds for deletion. I think it just got overlooked as we worked other areas. Therefore, the web app currently sends multiple DELETE requests to the API rapidly and serially, one for each asset. This is not ideal and is probably causing your problem.

I'll implement a batch DELETE endpoint in the API and wire the web app to use it. That should help.
