### ISSUE TITLE
Dockerfile references Iron Bank base image

### ISSUE THREAD

**Issue by csmig** [NUWCDIVNPT/stig-manager#122]
The primary Dockerfile should be modified to use the Node.js image from Iron Bank (registry1.dsop.io)

**Comment by cd-rite** [comment]
Iron Bank CLI access is not reliable.
May need to host an Iron Bank NodeJS image on Docker Hub ourselves.

**Comment by csmig** [comment]
Opened a PR that updates the CD workflow to add support for an Iron Bank based node image.
