### ISSUE TITLE
Export an entire Collection in archive of .ckls and/or custom JSON format

### ISSUE THREAD

**Issue by cd-rite** [NUWCDIVNPT/stig-manager#123]
**Description**:
To allow Collections to be migrated from one STIGMan instance to another, or submission of an entire Collection as part of the RMF process, we should support the ability to export an entire collection as an archive.  
The exported "Collection" should include:
Collection metadata where appropriate (Maybe in a "helper" file in addition to the collection of .ckls)
Assets
Assigned STIGs
Reviews
Review History - (optional?) N/A for .ckls, I think
Users Grants - N/A for .ckls. Probably not a good idea, as there is the potential for User collisions, and user info might not even translate, as in cases where the tool has been deployed in one environment with username/pw and another with X.509 certificates. 

The export should allow production of an archive of either .ckl format or a more efficient format (JSON).

The ability to import an archive and populate/merge with an existing Collection already exists for .ckls, but will have to be implemented for the notional JSON format. 

**Considerations**:
Should this be done by the API (probably requires new endpoint) or the existing Client, which could use existing endpoints and create the package on the client machine?
API support could enable later STIGMan-to-STIGMan communications, but this is not a use case we currently have, so this will most likely be done in the Client.

Reviews my lose User attribution.

.ckl format will not support STIGMan-specific features and states, such as saved/submitted/rejected statuses, Owner feedback, etc. (We may be able to express Recommended Actions though a convention, but nothing in .ckl supports this info. Recommended Actions is a candidate for removal from the App for this reason.)  The limitations of the .ckl format may mean there will be slightly different behavior between a .ckl migration vs a JSON migration that could include any data we need.  We will either need to document that, or limit what we transfer with JSON for consistency.

How to handle cases where STIGS (or particular ruleId attached to STIG Revision) may not exist in destination system?

**Future**:
NIST OSCAL format

**Comment by csmig** [comment]
@cd-rite This issue is very broad and I think some of the request is currently addressed by #169 . Closing this issue, please open a more targeted issue if the requirement for a Collection export into JSON remains.
