### ISSUE TITLE
Receive "Ext.Ajax.request() failed" when attempting to sign-in to a fresh installation of STIG Manager

### ISSUE THREAD

**Issue by SuperSaiyanMagenta** [NUWCDIVNPT/stig-manager#1268]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version of STIG Manager?

- [X] I am using the latest [Release](https://github.com/NUWCDIVNPT/stig-manager/releases).
- [ ] I am NOT using the latest [Release](https://github.com/NUWCDIVNPT/stig-manager/releases). I am aware that the first thing I will be asked to do is update the application so that I have the latest bugfixes.

### Where are you experiencing the issue?

- [X] API
- [X] UI or other client
- [X] Deployment
- [ ] Elsewhere

### Current Behavior

I'm currently attempting to stand-up a STIG Manager instance for my organization to utilize in conjunction with EvaluateSTIG. 

=== CONFIGURATION ===
- I have the latest version of STIG-Manager and version 24.0.3 of Keycloak with both point to the respective databases and all running in docker using a docker compose file. 
- I also have an NGINX reverse proxy setup to provide HTTPS to both keycloak and STIG-Manager. 
- I have setup the stigman realm to match the 
 STIG-Manager documentation [here](https://stig-manager.readthedocs.io/en/1.3.3/installation-and-setup/authentication.html#keycloak-configuration).
-  I have an account created in the stigman realm that is mapped to the previously created admin realm role.

### Steps To Reproduce

-- I can go to the STIG-Manager URL which then redirects me to Keycloak for authentication.  
-- I use an admin account to sign in and am redirected back to STIG-Manager. 
-- I then receive 'Ext.Ajax.request() failed' under the green shield STIG Manager logo.

### Describe your Environment

```markdown
- Hosting: on-prem
- Browser: Firefox/Chrome
- OS: Windows 10
- Node:
- npm:
```

**Comment by SuperSaiyanMagenta** [comment]
Please le me know if there is anything else you need to help resolve this issue. Thanks again!

**Comment by SuperSaiyanMagenta** [comment]
Here are my logs, docker-compose, Dockerfile for Keycloak, and Nginx conf:
[kc-dockerfile.txt](https://github.com/NUWCDIVNPT/stig-manager/files/15151984/kc-dockerfile.txt)
[sm-nginx-conf.txt](https://github.com/NUWCDIVNPT/stig-manager/files/15151985/sm-nginx-conf.txt)
[STIG Manager docker-compose.txt](https://github.com/NUWCDIVNPT/stig-manager/files/15151986/STIG.Manager.docker-compose.txt)
[stigman-logs.txt](https://github.com/NUWCDIVNPT/stig-manager/files/15151987/stigman-logs.txt)

**Comment by cd-rite** [comment]
Hi @SuperSaiyanMagenta 
I think it might be related to this error from Keycloak in your logs:
`keycloak-1     | 2024-04-29 15:41:55,747 WARN  [org.keycloak.services] (executor-thread-1) KC-SERVICES0091: Request is missing scope 'openid' so it's not treated as OIDC, but just pure OAuth2 request.`
I think this is somewhat new behavior for Keycloak.

You can have the client request this scope by setting the STIGMan envvar `STIGMAN_CLIENT_EXTRA_SCOPES` to include "openid"

Let us know if that resolves the issue!

**Comment by SuperSaiyanMagenta** [comment]
Thanks for the assistance with this issue! 

I've added     STIGMAN_CLIENT_EXTRA_SCOPES="openid"     to my docker compose file under stigManager's ENV settings. 

When I access STIG-Manager now, I just see a spinning circle and the logo for STIG Manager, but no redirect to Keycloak for authentication. I've attached my logs.
[stigman-logs(updated).txt](https://github.com/NUWCDIVNPT/stig-manager/files/15167870/stigman-logs.updated.txt)


Is there a nominal version of Keycloak that I should use with STIG-Manager?

**Comment by SuperSaiyanMagenta** [comment]
I removed the quotes around openid as requested. Now I am redirected to keycloak for authentication. Once I authenticate via Keycloak, I'm back to the original error. I've attached updated log trace as well as a screenshot from chrome dev tools. Thanks again for the assist.


[stigman-logs(30APR2024-1238).txt](https://github.com/NUWCDIVNPT/stig-manager/files/15168923/stigman-logs.30APR2024-1238.txt)
![stigman-chrome-console-ajax-error](https://github.com/NUWCDIVNPT/stig-manager/assets/168110294/496a392f-c4d8-4772-9cb0-d35e398862c5)

**Comment by cd-rite** [comment]
Hi @SuperSaiyanMagenta It looks like your Keycloak implementation is not providing the requested scopes in the access token.
The instructions in the docs are just one way to configure this, but are written for an older version of Keycloak. However, the same configurations should be available in whichever version you use, just organized slightly differently.
We have a pretty new sample container you could spin up and log in to for comparison (it's just doing username/pw, but the scopes should be assigned similarly):
https://github.com/NUWCDIVNPT/stig-manager-auth
admin password for this container here: https://hub.docker.com/r/nuwcdivnpt/stig-manager-auth

You'll need to add the scopes from the docs to the stig-manager client you create in keycloak, and ensure they are added to the token when token requests come from that client. 
There should be a screen that looks something like this:
![image](https://github.com/NUWCDIVNPT/stig-manager/assets/61710958/8dd1c630-cef3-4eb2-86a4-a346b9ffa07c)

**Comment by StevenMcGann** [comment]
I'm struggling with the same or similar issue.  Pretty sure my scopes are set like you have for stig-manager-auth.  I used that realm export to set up my configuration.  I'm still troubleshooting though.

**Comment by cd-rite** [comment]
@StevenMcGann Hmm, perhaps you were reusing a session created before you made other changes? Then, when you logged in today, it created a new session with the confguration changes you made?  Either way, glad it's working now!

@SuperSaiyanMagenta If you're still having trouble, I'd cross-check with our sample container to check for relevant differences, and the keycloak docs.... From your logs, you are producing access tokens that do not have the proper scopes included. There are several ways to get them in there, depending on your other config settings, and the keycloak docs may help there.

Your token from logs:
```diff
{
    "exp": 1714498772,
    "iat": 1714498472,
    "auth_time": 1714498472,
    "jti": "f2519d0e-39d8-4e52-85b8-1d7dba012ca0",
    "iss": "https://stigs.domain.local/realms/stigman",
    "aud": "account",
    "sub": "e424d8c9-2832-4e9d-aca1-1c006241aef7",
    "typ": "Bearer",
    "azp": "stig-manager",
    "nonce": "a08765c4-0ec2-45e2-968c-79053fdcd519",
    "session_state": "be764962-679a-4099-a1a7-3b85afd21916",
    "acr": "1",
    "allowed-origins": [
      "/*"
    ],
    "realm_access": {
      "roles": [
        "offline_access",
        "create_collection",
        "admin",
        "default-roles-stigman",
        "uma_authorization",
        "user"
      ]
    },
    "resource_access": {
      "account": {
        "roles": [
          "manage-account",
          "manage-account-links",
          "view-profile"
        ]
      }
    },
----> "scope": "openid profile email",
    "sid": "be764962-679a-4099-a1a7-3b85afd21916",
    "email_verified": true,
    "name": "Stig Admin",
    "preferred_username": "stigadmin",
    "given_name": "Stig",
    "family_name": "Admin",
    "email": "stigadmin@domain.local"
        }
```


Token with proper scopes (the app is only looking for the "stig-manager" ones):

```diff
  "iat": 1714579854,
  "auth_time": 1714579853,
  "jti": "a34c802a-6da4-4f58-9e4f-9a0be8beecbe",
  "iss": "http://localhost:8080/realms/stigman",
  "aud": [
    "realm-management",
    "account"
  ],
  "sub": "bf87a16f-39e6-46d9-8971-f0ef51dd3f85",
  "typ": "Bearer",
  "azp": "stig-manager",
  "nonce": "61908713-a100-4b38-a863-4d9c195719cf",
  "session_state": "b5b07095-d594-4030-98de-2d75bb6773df",
  "realm_access": {
    "roles": [
      "create_collection",
      "default-roles-stigman",
      "admin",
      "user"
    ]
  },
  "resource_access": {
    "realm-management": {
      "roles": [
        "view-users",
        "query-groups",
        "query-users"
      ]
    },
    "account": {
      "roles": [
        "manage-account",
        "manage-account-links",
        "view-profile"
      ]
    }
  },
---->  "scope": "openid stig-manager:collection stig-manager:user:read stig-manager:op stig-manager:user stig-manager stig-manager:stig",
  "sid": "b5b07095-d594-4030-98de-2d75bb6773df",
  "clientId": "admin",
  "name": "Admin Burke",
  "preferred_username": "admin",
  "given_name": "Admin",
  "family_name": "Burke",
  "client_id": "admin"
}

```

**Comment by SuperSaiyanMagenta** [comment]
Copy that. I've been able to resolve this issue by just exporting the realm from the sample container and importing it into my production Keycloak v24 container. Once I did that, I was able to access STIG Manager. Thanks again for the support! We are really looking forward to utilizing this product in our environment! :)

**Comment by cd-rite** [comment]
@SuperSaiyanMagenta Great, I'll close this issue then! Just make sure you remove those sample users, etc. before you deploy to production!
