### ISSUE TITLE
Issues with STIGMAN_CLIENT_WELCOME_IMAGE 

### ISSUE THREAD

**Issue by SuperSaiyanMagenta** [NUWCDIVNPT/stig-manager#1273]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version of STIG Manager?

- [X] I am using the latest [Release](https://github.com/NUWCDIVNPT/stig-manager/releases).
- [ ] I am NOT using the latest [Release](https://github.com/NUWCDIVNPT/stig-manager/releases). I am aware that the first thing I will be asked to do is update the application so that I have the latest bugfixes.

### Where are you experiencing the issue?

- [ ] API
- [X] UI or other client
- [ ] Deployment
- [ ] Elsewhere

### Current Behavior

I'm attempting to use the variable STIGMAN_CLIENT_WELCOME_IMAGE to display my organization's logo on the welcome screen, but I cannot get the image to appear. I have tried multiple image formats including PNG, JPG, BMP & SVG. I've mounted the local directory with the image file as a volume to the STIG Manager container, then specified the path to the image file as the value for STIGMAN_CLIENT_WELCOME_IMAGE in my docker-compose file. Is there something I'm missing? The documentation does not specify a particular format for the image, nor a size limit. Please assist. Thanks again!

### Describe your Environment

```markdown
- Hosting:
- Browser:
- OS:
- Node:
- npm:
```

**Comment by cd-rite** [comment]
@SuperSaiyanMagenta Ah, I believe the intent there is that you only provide a URL of the image you want to appear there, and would be hosted elsewhere. That image could be served out by, (I think) your NGINX proxy. 

But I agree that's not clear in the docs. I'll double check and let you know (and update the docs).

**Comment by SuperSaiyanMagenta** [comment]
Copy that! I will update my config to host the image from nginx. Thanks again!
