### ISSUE TITLE
Failed to fetch error

### ISSUE THREAD

**Issue by zirus001** [NUWCDIVNPT/stig-manager#1278]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version of STIG Manager?

- [X] I am using the latest [Release](https://github.com/NUWCDIVNPT/stig-manager/releases).
- [ ] I am NOT using the latest [Release](https://github.com/NUWCDIVNPT/stig-manager/releases). I am aware that the first thing I will be asked to do is update the application so that I have the latest bugfixes.

### Where are you experiencing the issue?

- [X] API
- [ ] UI or other client
- [ ] Deployment
- [ ] Elsewhere

### Current Behavior

I am building a new STIG Manager (RHEL 8) to replace our older RHEL 7 server. Everything was moving along just fine until I get to logging into the API portion. I believe the keyloak portion is working properly, I authenticate and I can see my session in keycloak with my ip, same as our other STIG Manager. However, after the authentication piece from keycloak, STIG Manager just throws the below message:
STIG Manager
Failed to fetch

I have also tried putting STIG Manager in debug mode with no additional logs being generated with it.

### Expected Behavior

After authenticating with keycloak the process should have been that STIG Manager create the account and continue to login.

### Steps To Reproduce

1. I was able to export the previous realm we currently use for STIG Manager (minus the user accounts).
2. Imported with only one error due to a private key not being able to be read. Generated a new certificate for this.
3. Imported realm seems to work when initially connecting the new STIG Manager to it aside from the "Failed to Fetch" message.

### Can you provide screenshots, logs, or other useful artifacts?

![image](https://github.com/NUWCDIVNPT/stig-manager/assets/39812270/83ebda4c-a3a2-48c6-ac90-659f96176829)

### Describe your Environment

```markdown
- Hosting: nuwcdivnpt/stig-manager:latest-ironbank
- Browser:Chrome (have tried Edge as well)
- OS: Server Rhel 8 (Windows for the workstation)
- Node: N/A
- npm: N/A

Keycloak 24.0.3 is running on a separate server as we use it for other applications to authenticate too.
STIG Manager/mysqlmysql.x86_64 8.0.36/Apache are running on the same system.
```

**Comment by cd-rite** [comment]
Hi @zirus001 I haven't seen that error before! I am also not able to recreate it.

It sounds like the main configuration change you made (aside from a new host for STIGMan) was that you are now using a different keycloak, and that you have imported the old keycloak realm into the new keycloak?

Can you point your new STIGMan at the old keycloak that worked before, to rule out a keycloak config issue? If that results in the same issue, you could try a different STIGManager container (though nothing seems wrong with the latest-ironbank image that I can tell). If it continues to fail then it may be an issue with your new host.

Alternatively, if you still have it, point your old stigman on the old host at the new keycloak, and see what happens there.

Can you open your browsers devtools, to see if there are any other errors? Either in the console or the "network" tab?
After authentication, are any requests being made to the UI?

**Comment by zirus001** [comment]
I can't believe i didn't think of that..lol So yes pointing the new STIG Manager to the old Keycloak does in fact work as it should and creates the account. I think I will delete the realm and create it from scratch to see if that makes a difference. It could have been something that came over during the import that caused the issue. If you would leave the issue open till I can verify. Thanks!

**Comment by zirus001** [comment]
Ok confirmed. I removed the realm and followed the guide and it was super smooth. Sorry for the false alarm but maybe this will help someone in the future..lol Thanks!
