### ISSUE TITLE
Unable to deploy Quick Start Orchestration on AWS

### ISSUE THREAD

**Issue by hasib-haque** [NUWCDIVNPT/stig-manager#1281]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version of STIG Manager?

- [X] I am using the latest [Release](https://github.com/NUWCDIVNPT/stig-manager/releases).
- [ ] I am NOT using the latest [Release](https://github.com/NUWCDIVNPT/stig-manager/releases). I am aware that the first thing I will be asked to do is update the application so that I have the latest bugfixes.

### Where are you experiencing the issue?

- [ ] API
- [ ] UI or other client
- [X] Deployment
- [ ] Elsewhere

### Current Behavior

I am using the quick orchestration deployment with docker-compose using the default code except routing api port 54000 to AWS instance's port 8081. I have also updated STIGMAN_CLIENT_OIDC_PROVIDER with the internal IP of the EC2 instance in place of localhost.
When I access the internal AWS ip over my vpn connection as in http://10.123.123.123:8081
I get "Secure Context Required" page as below:

Green shield with check STIG Manager
<img width="950" alt="stigman" src="https://github.com/NUWCDIVNPT/stig-manager/assets/3289092/11e0a3ae-54d6-453d-adc2-82e758eab620">

SECURE CONTEXT REQUIRED

The App is not executing in a [secure context](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts) and cannot continue.

To be considered secure, resources that are not local must be served over https:// URLs and the security properties of the network channel used to deliver the resource must not be considered deprecated.

### Expected Behavior

STIG Manager GUI

### Can you provide screenshots, logs, or other useful artifacts?

<img width="950" alt="stigman" src="https://github.com/NUWCDIVNPT/stig-manager/assets/3289092/d0324b5d-8a45-4bb7-b03d-3a7c6614a492">

### Describe your Environment

```markdown
- Hosting:AWS
- Browser:Chrome, Edge, Firefox
- OS: RHEL9
- Node:
- npm:
```

**Comment by hasib-haque** [comment]
I am going to follow the instructions in the discussions forum to resolve this. Thank you

**Comment by petertirrell** [comment]
> I am going to follow the instructions in the discussions forum to resolve this. Thank you

I think we're running into similar issues, trying to wrangle the requirement of HTTPS in our AWS environment.  We're trying to use images set up in ECS, but get the same screen and message as above.  Which discussion instructions did you find to help resolve this?

**Comment by hasib-haque** [comment]
> > I am going to follow the instructions in the discussions forum to resolve this. Thank you
> 
> I think we're running into similar issues, trying to wrangle the requirement of HTTPS in our AWS environment. We're trying to use images set up in ECS, but get the same screen and message as above. Which discussion instructions did you find to help resolve this?
I am trying to make it work without using CAC, for a demo installation. Haven't had success so far. Following this discusstion thread:
https://github.com/NUWCDIVNPT/stig-manager/discussions/1266

**Comment by cd-rite** [comment]
Hi @hasib-haque @petertirrell Closing this, since it is not likely an issue with the app, and trying to encourage discussion in the thread you mentioned: #1266 
We can open another issue for updating guidance in our documentation as needed.
