### ISSUE TITLE
FEATURE REQUEST:  Add ''Does Not Contain' option to text filtering

### ISSUE THREAD

**Issue by bbcallison** [NUWCDIVNPT/stig-manager#1332]
**Is your feature request related to a problem? Please describe.**

limited search ability on filters for detail and comment fields.  You can currently only search for 'contains' type items to find text that matches.  That limits the usability of the field and often have to export results into excel for more text filtering options

**Describe the solution you'd like**

would like to also request a feature to include a 'does not contain' option for filtering the detail and comments field

**Describe alternatives you've considered**

manipulating data into excel format and filtering for strings of text that do not match up with expected results by using the 'does not contain' filter.

**Additional context**

my find other business cases for filtering, but the main use case for me is trying to search for a specific eval-stig string (ex 1.2404.2) and display all items that do not match (so I can bulk reject).

**Comment by cd-rite** [comment]
Hi @bbcallison Thanks for the suggestion! We are going to take at adding this feature to our filters.
