### ISSUE TITLE
Issues Assigning STIGs to assets

### ISSUE THREAD

**Issue by apborba15** [NUWCDIVNPT/stig-manager#135]
I can create a new asset and save, however, when I try to assign a STIG assignment to an asset, I receive the following SQL Syntax Error
![STIGMANSQLerror1](https://user-images.githubusercontent.com/73552358/106947144-04008e80-66f8-11eb-86d6-fc2f890442f9.PNG)
![STIGMANSQLerror2](https://user-images.githubusercontent.com/73552358/106947147-04992500-66f8-11eb-9790-8998ebb9addf.PNG)

If I go to the "STIGs" workplace and click on" attach STIGs" and try to assign a STIG to a workstation that way, I receive a "Undefined" error, as shown here
![undefinedstigman error](https://user-images.githubusercontent.com/73552358/106947341-3ad6a480-66f8-11eb-813e-44b57ab19294.PNG)

**Comment by cd-rite** [comment]
What version of STIG Manager are you running? You can view this on the home tab, next to "STIG Manager"
The current version is 1.0.0-beta.14

**Comment by apborba15** [comment]
Yes, I am using the current version - 1.0.0-beta.14

**Comment by cd-rite** [comment]
So...is that first error when you try to create an asset and make an assignment at the same time, and the second error is when you make an asset without an assignment, then use the STIG panel to assign it? Have you tried a different STIG?

**Comment by apborba15** [comment]
![adding STIG assignment](https://user-images.githubusercontent.com/73552358/106951564-eb937280-66fd-11eb-850d-66b5ab8f32b8.PNG)
I tried to add a STIG assignment in this workspace and this is when I receive the first error

**Comment by apborba15** [comment]
2nd Error is when I try it this way  
![stig2method](https://user-images.githubusercontent.com/73552358/106951771-30b7a480-66fe-11eb-8ab5-41e3bd06471c.PNG)
And yes- i've tried adding different STIGs

**Comment by cd-rite** [comment]
Can you provide your container startup logs?
Also, if you have access to the DB, can you provide the contents of the _migrations table?

**Comment by cd-rite** [comment]
In addition, can you verify that you are using mySQL 8 (preferably 8.0.22, which we have tested with)?

**Comment by csmig** [comment]
I can reproduce this problem using MySQL 8.0.18 or earlier. Our current MySQL implementation requires version 8.0.19, released in January 2020, or greater. We've created issue #136 to add a MySQL version check at startup.

Explanation: The use of a row alias after VALUES [at this line](https://github.com/NUWCDIVNPT/stig-manager/blob/ddf691c717f327e5df0e468cf39cd951d024b09f/api/source/service/mysql/utils.js#L346) was supported beginning with version 8.0.19. I've written the query using this syntax to address the [deprecation Note documented here](https://dev.mysql.com/doc/refman/8.0/en/insert-on-duplicate.html).

**Comment by csmig** [comment]
I rewrote the bothersome query to use the older `VALUES()` syntax for `ON DUPLICATE KEY UPDATE`. This is testing well with MySQL >= 8.0.14
