### ISSUE TITLE
MySQL 8.0.39-0ubuntu* not recognized as a valid MySQL Server version

### ISSUE THREAD

**Issue by visccyberacct** [NUWCDIVNPT/stig-manager#1397]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version of STIG Manager?

- [X] I am using the latest [Release](https://github.com/NUWCDIVNPT/stig-manager/releases).
- [ ] I am NOT using the latest [Release](https://github.com/NUWCDIVNPT/stig-manager/releases). I am aware that the first thing I will be asked to do is update the application so that I have the latest bugfixes.

### Where are you experiencing the issue?

- [X] API
- [ ] UI or other client
- [X] Deployment
- [ ] Elsewhere

### Current Behavior

I deployed the ubuntu version of MySQL as the database. When starting the api, I receive the following error message:

{"name":"TypeError","message":"Invalid Version: 8.0.39-0ubuntu0.24.04.2","stack":"TypeError: Invalid Version: 8.0.39-0ubuntu0.24.04.2\n    at new SemVer (/snapshot/stig-manager/api/source/node_modules/semver/classes/semver.js:38:13)\n    at compare (/snapshot/stig-manager/api/source/node_modules/semver/functions/compare.js:3:3)\n    at lt (/snapshot/stig-manager/api/source/node_modules/semver/functions/lt.js:2:29)\n    at Object.module.exports.initializeDatabase (/snapshot/stig-manager/api/source/service/utils.js:114:7)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Promise.all (index 1)\n    at async startServer (/snapshot/stig-manager/api/source/index.js:261:5)"}

api/source/service/utils.js does not strip away -0ubuntu0.24.04.2 when checking the database version.

### Expected Behavior

MySQL 8.0.39, regardless of the Linux version, should have been recognized as a valid version of MySQL.

### Steps To Reproduce

1. In Ubuntu Server 24.04
2. Install Ubuntu Linux 24.04 (x86, 64-bit), DEB Bundle from MySQL
3. Start api

### Describe your Environment

```markdown
- Hosting: 
- Browser:
- OS:
- Node:
- npm:
```

**Comment by cd-rite** [comment]
Hi @visccyberacct Thanks for pointing that out! We've merged a change that addresses this. If you pull the "latest" version from Docker Hub in a few minutes, you should have the changes. Otherwise, it will be included in our next numbered release, 1.4.16, targeted for early next week.
