### ISSUE TITLE
Add unique index for Asset/version/checkId in review table

### ISSUE THREAD

**Issue by cd-rite** [NUWCDIVNPT/stig-manager#1410]
putReviewsByAsset can sometimes create duplicate reviews when invoked concurrently. A unique index will at least prevent insertion of duplicate reviews, but will throw an error. This is better than creating the duplicate, but still sub-optimal. 
Possible approach to avoid error:
lock asset for review updates when handling putReviewsByAsset 

Adding index will require an operation in the migration cleaning up any existing duplicate reviews before applying index.

**Comment by csmig** [comment]
Resolved by #1416
