### ISSUE TITLE
CSV Export Not Functioning

### ISSUE THREAD

**Issue by mayszs** [NUWCDIVNPT/stig-manager#1419]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version of STIG Manager?

- [ ] I am using the latest [Release](https://github.com/NUWCDIVNPT/stig-manager/releases).
- [X] I am NOT using the latest [Release](https://github.com/NUWCDIVNPT/stig-manager/releases). I am aware that the first thing I will be asked to do is update the application so that I have the latest bugfixes.

### Where are you experiencing the issue?

- [ ] API
- [X] UI or other client
- [ ] Deployment
- [ ] Elsewhere

### Current Behavior

From the Label tab in a Collection the asset list cannot be exported.  The CSV button exists but does not perform any actions.
Function operates properly in Chrome but not Edge.

### Steps To Reproduce

v1.4.16 Click on a Collation --> Select a Label to filter by --> Try to download CSV from Right Hand Middle Pane Assets for [Selected Label]

### Describe your Environment

```markdown
- Hosting: NREN Instance
- Browser: Edge
- OS:
- Node:
- npm:
```

**Comment by cd-rite** [comment]
Hi @mayszs I can't replicate this issue on Edge or Chrome. Are you getting this behavior with all Collections? Does this issue persist through a refresh of the page?

**Comment by cd-rite** [comment]
We can't recreate this issue... Please let us know if you can describe any other factors that led to this problem, and feel free to reopen the issue.
