### ISSUE TITLE
"No host_name in ASSET"

### ISSUE THREAD

**Issue by Ryker49** [NUWCDIVNPT/stig-manager#1420]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version of STIG Manager?

- [X] I am using the latest [Release](https://github.com/NUWCDIVNPT/stig-manager/releases).
- [ ] I am NOT using the latest [Release](https://github.com/NUWCDIVNPT/stig-manager/releases). I am aware that the first thing I will be asked to do is update the application so that I have the latest bugfixes.

### Where are you experiencing the issue?

- [ ] API
- [ ] UI or other client
- [ ] Deployment
- [X] Elsewhere

### Current Behavior

I am testing out the software for my team to use with various STIGS and it won't accept the ckl files I send it. It keeps giving various reasons as to why they won't import, this notification was given in response to a scan. Any help at all is appreciated.

### Expected Behavior

It would accept the imported ckl file.

### Describe your Environment

```markdown
- Hosting:
- Browser:
- OS:
- Node:
- npm:
```

**Comment by cd-rite** [comment]
What tool are you using to create these .ckl files? Valid .ckl files should have an ASSET block that includes a HOST_NAME element that looks something like this:
```
<?xml version="1.0" encoding="UTF-8"?>
<CHECKLIST>
  <ASSET>
    <ROLE>Workstation</ROLE>
    <ASSET_TYPE>Computing</ASSET_TYPE>
    <MARKING>NONE</MARKING>
    <HOST_NAME>hostname</HOST_NAME>
    <HOST_IP></HOST_IP>
    <HOST_MAC></HOST_MAC>
    <HOST_GUID/>
    <HOST_FQDN>hostname.fqdn.etc</HOST_FQDN>
    <TECH_AREA/>
    <TARGET_KEY></TARGET_KEY>
    <WEB_OR_DATABASE>false</WEB_OR_DATABASE>
    <WEB_DB_SITE/>
    <WEB_DB_INSTANCE/>
  </ASSET>
  <STIGS>
    <iSTIG>...
   
....... rest of .ckl file ....

```

**Comment by Ryker49** [comment]
Can't say for certain about the tool, but after I went into the file on Notepad and gave it just "hostname" it worked fine. Appreciate the post, it helped
