### ISSUE TITLE
"error": "Duplicate entry '164576-000795' for key 'rev_group_rule_cci_map.index2'"

### ISSUE THREAD

**Issue by ltran10914** [NUWCDIVNPT/stig-manager#1421]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version of STIG Manager?

- [ ] I am using the latest [Release](https://github.com/NUWCDIVNPT/stig-manager/releases).
- [X] I am NOT using the latest [Release](https://github.com/NUWCDIVNPT/stig-manager/releases). I am aware that the first thing I will be asked to do is update the application so that I have the latest bugfixes.

### Where are you experiencing the issue?

- [ ] API
- [ ] UI or other client
- [ ] Deployment
- [X] Elsewhere

### Current Behavior

I am receiving the below error when trying to import the latest Windows 11 V2R2 xccdf.xml.  I can import V2R1.  

U_MS_Windows_11_STIG_V2R2_Manual-xccdf.xml
{
  "error": "Duplicate entry '164576-000795' for key 'rev_group_rule_cci_map.index2'",
  "stack": "Error: Duplicate entry '164576-000795' for key 'rev_group_rule_cci_map.index2'\n    at PromisePoolConnection.query (C:\\Program Files\\stig-manager-main\\api\\source\\node_modules\\mysql2\\promise.js:93:22)\n    at transaction (C:\\Program Files\\stig-manager-main\\api\\source\\service\\STIGService.js:524:40)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async retryFunction (C:\\Program Files\\stig-manager-main\\api\\source\\service\\utils.js:457:14)\n    at async module.exports.retryOnDeadlock (C:\\Program Files\\stig-manager-main\\api\\source\\service\\utils.js:467:10)\n    at async exports.insertManualBenchmark (C:\\Program Files\\stig-manager-main\\api\\source\\service\\STIGService.js:615:12)\n    at async importManualBenchmark (C:\\Program Files\\stig-manager-main\\api\\source\\controllers\\STIG.js:25:22)"
}
------------------------------------
Done

Any assitance is greatly appreciated. 

### Expected Behavior

Import complete. 

### Steps To Reproduce

1. Logon to STIG Manager
2. Expand Application Management
3. Select STIG Benchmarks
4. Click on Import STIGS
5. Click on Browse
6. Browse to shared directory with STIG ZIP file
7. Click Import
8. Error

### Can you provide screenshots, logs, or other useful artifacts?

U_MS_Windows_11_V2R2_Manual_STIG/U_MS_Windows_11_STIG_V2R2_Manual-xccdf.xml
{
  "error": "Duplicate entry '165095-000795' for key 'rev_group_rule_cci_map.index2'",
  "stack": "Error: Duplicate entry '165095-000795' for key 'rev_group_rule_cci_map.index2'\n    at PromisePoolConnection.query (C:\\Program Files\\stig-manager-main\\api\\source\\node_modules\\mysql2\\promise.js:93:22)\n    at transaction (C:\\Program Files\\stig-manager-main\\api\\source\\service\\STIGService.js:524:40)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async retryFunction (C:\\Program Files\\stig-manager-main\\api\\source\\service\\utils.js:457:14)\n    at async module.exports.retryOnDeadlock (C:\\Program Files\\stig-manager-main\\api\\source\\service\\utils.js:467:10)\n    at async exports.insertManualBenchmark (C:\\Program Files\\stig-manager-main\\api\\source\\service\\STIGService.js:615:12)\n    at async importManualBenchmark (C:\\Program Files\\stig-manager-main\\api\\source\\controllers\\STIG.js:25:22)"
}
------------------------------------
Done

### Describe your Environment

```markdown
- Hosting: Windows Server 2022
- Browser: Edge
- OS: Windows Server 2022
- Node: Node.js v22.4.1.
- npm: ??
```

**Comment by cd-rite** [comment]
HI @ltran10914 - This is a known issue with the last release of the DISA Windows 11 STIG, which included duplicate CCI elements for some Rules. The STIGMan 1.4.17 Release can handle these duplicated elements. 
In the meantime, see this discussion for more info, as well as a de-duplicated version of that STIG that will work with 1.4.16 and lower, and a python script that can remove those duplicate elements from STIGs: https://github.com/NUWCDIVNPT/stig-manager/discussions/1412
