### ISSUE TITLE
CCI Filtering issue

### ISSUE THREAD

**Issue by justinprince** [NUWCDIVNPT/stig-manager#1424]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version of STIG Manager?

- [X] I am using the latest [Release](https://github.com/NUWCDIVNPT/stig-manager/releases).
- [ ] I am NOT using the latest [Release](https://github.com/NUWCDIVNPT/stig-manager/releases). I am aware that the first thing I will be asked to do is update the application so that I have the latest bugfixes.

### Where are you experiencing the issue?

- [ ] API
- [X] UI or other client
- [ ] Deployment
- [ ] Elsewhere

### Current Behavior

When I go to STIG Library > Select a STIG (Doesn't matter which) > and then try and Filter by CCI I get an unhandled error. 

`
{"sourceStack":"    at toLowerCase (src/SM/ColumnFilters.js:118:70)\n    at  (src/SM/Error.js:207:42)\n    at  (src/SM/Error.js:207:42)\n    at  (src/SM/Error.js:207:42)\n    at  (src/SM/Error.js:207:42)\n    at  (src/SM/Error.js:207:42)\n    at filter (src/SM/Library.js:188:16)\n    at  (src/SM/StackTrace.js:4:25)\n    at apply (src/SM/Global.js:426:8)\n    at fireEvent (src/SM/ColumnFilters.js:151:11)\n","name":"TypeError","message":"t.toLowerCase is not a function","stack":"TypeError: t.toLowerCase is not a function\n    at constructor.fn (https://mra.ares.navy.mil/stigmanager/js/stig-manager.min.js:371:19700)\n    at constructor.<anonymous> (https://mra.ares.navy.mil/stigmanager/ext/ext-all.js:21:322020)\n    at Ext.util.MixedCollection.filterBy (https://mra.ares.navy.mil/stigmanager/ext/ext-all.js:21:114936)\n    at constructor.queryBy (https://mra.ares.navy.mil/stigmanager/ext/ext-all.js:21:322950)\n    at constructor.filterBy (https://mra.ares.navy.mil/stigmanager/ext/ext-all.js:21:322516)\n    at constructor.filter (https://mra.ares.navy.mil/stigmanager/ext/ext-all.js:21:322407)\n    at constructor.filterschanged (https://mra.ares.navy.mil/stigmanager/js/stig-manager.min.js:382:40648)\n    at h.Event.fire (https://mra.ares.navy.mil/stigmanager/ext/ext-all.js:21:3699)\n    at constructor.fireEvent (https://mra.ares.navy.mil/stigmanager/ext/ext-all.js:21:687)\n    at constructor.onFilterChange (https://mra.ares.navy.mil/stigmanager/js/stig-manager.min.js:371:20215)","env":{"version":"1.4.17","apiBase":"api","welcome":{"image":"","title":"","message":"","link":""},"commit":{"branch":"main","sha":"16301a3d59","tag":"na","describe":"1.4.17"},"oauth":{"authority":"https://ares-dev.okta.mil/oauth2/default","clientId":"0oab8bpwpIxUGS9in0k6","refreshToken":{"disabled":false},"extraScopes":"openid offline_access profile","scopePrefix":"","claims":{"scope":"scp","username":"sub","servicename":"undefined","name":"sub","privileges":"stigmanager_roles","email":"email"}},"experimental":{"appData":"false"}}}
`

### Expected Behavior

When entering a CCI # into the CCI column Filter field, STIG Controls should be filtered properly.

### Steps To Reproduce

1. Log into STIG Manger UI with permissions to view the STIG Library.
2. Select an imported STIG.
3. Select the CCIs column header.
4. In the Filter field, enter any numbers or letters.

### Can you provide screenshots, logs, or other useful artifacts?

![image](https://github.com/user-attachments/assets/74d064ca-c7dd-4e13-8601-8c15834e1987)

### Describe your Environment

```markdown
- Hosting: Azure App Service
- Browser: Edge
- OS: Windows
- Node: 
- npm:
```

**Comment by cd-rite** [comment]
Thanks, I can confirm this bug. Should have a fix in the next release.
