### ISSUE TITLE
Windows 11 V2R2 stig

### ISSUE THREAD

**Issue by JR-USA** [NUWCDIVNPT/stig-manager#1434]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version of STIG Manager?

- [ ] I am using the latest [Release](https://github.com/NUWCDIVNPT/stig-manager/releases).
- [ ] I am NOT using the latest [Release](https://github.com/NUWCDIVNPT/stig-manager/releases). I am aware that the first thing I will be asked to do is update the application so that I have the latest bugfixes.

### Where are you experiencing the issue?

- [ ] API
- [ ] UI or other client
- [ ] Deployment
- [ ] Elsewhere

### Current Behavior

when uploading Win 11 V2R2 STIG I get the following error:
U_MS_Windows_11_V2R2_Manual_STIG/U_MS_Windows_11_STIG_V2R2_Manual-xccdf.xml
{
  "error": "Duplicate entry '76305-000795' for key 'rev_group_rule_cci_map.index2'",
  "stack": "Error: Duplicate entry '76305-000795' for key 'rev_group_rule_cci_map.index2'\n    at PromisePoolConnection.query (/home/node/node_modules/mysql2/promise.js:93:22)\n    at transaction (/home/node/service/mysql/STIGService.js:524:40)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async retryFunction (/home/node/service/mysql/utils.js:457:14)\n    at async module.exports.retryOnDeadlock (/home/node/service/mysql/utils.js:467:10)\n    at async exports.insertManualBenchmark (/home/node/service/mysql/STIGService.js:615:12)\n    at async importManualBenchmark (/home/node/controllers/STIG.js:25:22)"
}
------------------------------------
Done

### Expected Behavior

STIG it be added to the STIG benchmarks.

### Steps To Reproduce

Manually upload STIG from DISA repo

### Describe your Environment

```markdown
- Hosting:
- Browser:
- OS:
- Node:
- npm:
```

**Comment by JR-USA** [comment]
I have just inherited this application. Can you point me to process for upgrading our latest instance 1.3.14 to 1.4.17.

**Comment by cd-rite** [comment]
Hi @JR-USA The process should be relatively simple, but will depend on your specific deployment.  Just replace the STIGMan webapp portion of your deployment with the latest version. 
There's some information here:
https://stig-manager.readthedocs.io/en/latest/installation-and-setup/installation-and-setup.html#updating-stig-manager
