### ISSUE TITLE
Prior history from scans is deleted?

### ISSUE THREAD

**Issue by SmithR49** [NUWCDIVNPT/stig-manager#1445]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version of STIG Manager?

- [X] I am using the latest [Release](https://github.com/NUWCDIVNPT/stig-manager/releases).
- [ ] I am NOT using the latest [Release](https://github.com/NUWCDIVNPT/stig-manager/releases). I am aware that the first thing I will be asked to do is update the application so that I have the latest bugfixes.

### Where are you experiencing the issue?

- [ ] API
- [ ] UI or other client
- [ ] Deployment
- [X] Elsewhere

### Current Behavior

I was testing whether remarks, details, etc. would carry over between scans of the exact same device, but it seems they all are removed once the new scan is uploaded. Is there a way to keep the old remarks?

### Expected Behavior

Remarks from the previous scan are saved, thereby making reviewing "Need Review" findings able to be handled quickly

### Describe your Environment

```markdown
- Hosting:
- Browser:
- OS:
- Node:
- npm:
```

**Comment by cd-rite** [comment]
Depending on the state of the Reviews in the file you are importing, changing these Collection settings should help:

![image](https://github.com/user-attachments/assets/12ac7079-fb4e-42c4-a3c2-9c8b63b5cecd)

If you have results in the imported file, and there are no details/comments for those Reviews, you could set "Empty detail(or comment) text is:" to "ignored".  This will change the Result for the Reviews in the system, but leave the details/comments alone. 

If you are trying to import files that DO include a result (other than Not_Reviewed) and also have details/comments, then those fields will import, overwriting what the system has stored (but it doesn't sound like that's the situation you are in). 

I think one or a combination of those Import Options settings should get you the behavior you are looking for.
