### ISSUE TITLE
FEATURE REQUEST: Add labels to multiple assets

### ISSUE THREAD

**Issue by jameskane9** [NUWCDIVNPT/stig-manager#1448]
I am using labels to tag assets in my collections, and have to select each asset to add them

**Describe the solution you'd like**
I would like to be able to modify multiple assets to add those labels, instead of doing it asset by asset. 

**Describe alternatives you've considered**
Add the capability to edit multiple assets at a time, even if just limited for labeling

**Comment by cd-rite** [comment]
Hi @jameskane9 From the Manage Collection interface, if you go to the Labels tab and select an asset, then hit the "Tag Assets..." button, you'll get a pop-up that will let you tag multiple assets with that label:
![image](https://github.com/user-attachments/assets/6844647d-5f4c-4f1a-9e29-f377b8e2fe69)
![image](https://github.com/user-attachments/assets/ab7b3de4-7bc2-41e6-872e-98266bd113cc)
