### ISSUE TITLE
Check for event subscriptions that are not unsubbed at destroy time

### ISSUE THREAD

**Issue by cd-rite** [NUWCDIVNPT/stig-manager#159]
Review UI code for properly unsubbing from events when tabs are destroyed

issue found in CollectionAdmin.js:
solution here: 278

    listeners: {
      beforedestroy: () => {
        SM.Dispatcher.removeListener('collectionchanged', onCollectionChanged)
        SM.Dispatcher.removeListener('collectioncreated', onCollectionCreated)
        SM.Dispatcher.removeListener('collectiondeleted', onCollectionDeleted)
      }

**Comment by csmig** [comment]
Checked that all components created and destroyed during run time, that attach listeners to SM.Dispatch, properly remove those listeners when destroyed.
