### ISSUE TITLE
Some way of importing SCAP evaluations from HBSS

### ISSUE THREAD

**Issue by cd-rite** [NUWCDIVNPT/stig-manager#16]
**Describe the solution you'd like**
I'd like a way to import HBSS SCAP evaluations directly into STIG Manager. Thanks, Developers!

**Describe alternatives you've considered**
Exporting from HBSS every day into ckls and then importing into STIG Manager is very cumbersome.

**Additional context**

**Comment by csmig** [comment]
Not in scope for the core API. Should be implemented as a sidecar proxy.
