### ISSUE TITLE
Create endpoint that returns data indicating RMF Control coverage of the included STIGs.

### ISSUE THREAD

**Issue by cd-rite** [NUWCDIVNPT/stig-manager#175]
Could be at the Collection level, or Asset level(?).

**Comment by csmig** [comment]
@cd-rite Could you please provide a bit more detail, perhaps an example output?

**Comment by csmig** [comment]
@cd-rite Bumping

**Comment by csmig** [comment]
CCI info is available from GET /stigs/{benchmarkId}/revisions/{revisionStr}/ccis
