### ISSUE TITLE
Collection->Reports->Status: Rows should link to corresponding Review

### ISSUE THREAD

**Issue by csmig** [NUWCDIVNPT/stig-manager#191]
Double-clicking a row in the Status Report should open the corresponding Review tab

cd-rite edit: Same behavior should apply to Individual Findings in Findings Report.
Collection->Reports->Findings->Individual Findings:Rows should link to corresponding Review

**Comment by cd-rite** [comment]
Same behavior should probably apply to Individual Findings in Findings Report.  
Collection->Reports->Findings->Individual Findings:Rows should link to corresponding Review

*Will make this a new Issue if solution is substantially
