### ISSUE TITLE
BUG: HBSS STIG Import Fails

### ISSUE THREAD

**Issue by nren-matt** [NUWCDIVNPT/stig-manager#192]
**Bug Location**

I found a bug in the:
- [ ] API
- [X ] UI
- [ ] Elsewhere (Please specify)

**Bug Description:**

When Importing four (4) STIG XMLs for HBSS it 

- [X] I have checked to see if there is already an existing issue that describes this bug.

**To Reproduce**
1. Go to 'STIG and SCAP Benchmarks'
2. Click on 'Import STIGs'
3. Click on 'Browse'
4. Select STIG file, click 'Import' and this is where is hangs on 'Initializing'
4. See 'error'  in screenshot
![Clipboard - March 22, 2021 10_37 AM](https://user-images.githubusercontent.com/81172628/112009179-8b655e00-8afc-11eb-8827-ee492c2f22c2.png)

These are the STIGs we can't seem to import:
![issues](https://user-images.githubusercontent.com/81172628/112009490-cd8e9f80-8afc-11eb-88c6-9433a537114e.PNG)
FOUO-Asset Baseline Monitor
FOUO Rogue Sensor
FOUO Distributed Repository
FOUO Policy Auditor

**Expected behavior**
We expect the STIG to import into STIGMAN so we can upload the .ckl files associated with that particular STIG.

**Actual behavior**
Application hangs on 'Initializing' and never imports the STIG. We can't add our .ckl files for review.

**Screenshots**

**Environment or Configuration:**
 - Container or Orchestration info (Kubernetes with Docker)
 - Browser (IE, Google Chrome)
 - Other info

**Additional context**

**Comment by csmig** [comment]
@nren-matt FWIW, the STIG import isn't hanging, the UI is not updating the progress bar text. We'll fix that.

More critically, the JSON response indicates a single Group was imported with no Rules. Which suggests these FOUO STIGs are upsetting our parser.

We haven't tested importing the XCCDF of the FOUO STIGs, because they really should not be any different in structure. But I shall grab them and see if I can replicate your experience.

**Comment by cd-rite** [comment]
@nren-matt We have identified at least a portion of the issue.  Of all the published STIGs, it looks like the ones you reference end in *XCCDF.xml whereas all others end in *xccdf.xml. Our filter was strictly looking for the lower-case version, which we will update in the next Release. 

As a work-around, if you manually unzip the STIGs you mentioned, and import the .xml files themselves, it should work. The filter is not invoked if you are not importing a .zip file.

**Comment by csmig** [comment]
Pushed two commits that address issues I found while researching this. Waiting for the OP to confirm resolution.

**Comment by nren-matt** [comment]
We have resolution, thank you for your assistance.
