### ISSUE TITLE
BUG: Large (over 3MB) .CKL files won't import

### ISSUE THREAD

**Issue by nren-matt** [NUWCDIVNPT/stig-manager#193]
**Bug Location**

I found a bug in the:
- [ ] API
- [X] UI
- [ ] Elsewhere (Please specify)

**Bug Description:**

If a .CKL file is over 2.5-3MB it will not import into STIG MANAGER UI.

- [X] I have checked to see if there is already an existing issue that describes this bug.

**To Reproduce**
1. Go to Upload a completed .ckl file and it errors out on all our Domain Controller Windows Server 2016 and Windows Server 2019 .ckl files that are ~8MB. Evaluate-STIG produces large output for several V-IDs and this makes the size of the file rather large.

![error (1)](https://user-images.githubusercontent.com/81172628/112011076-48a48580-8afe-11eb-911e-3e0031c93995.PNG)

**Expected behavior**
.ckl file and associated findings will upload into STIG MANAGER

**Actual behavior**
Files do not import.

**Screenshots**

**Environment or Configuration:**
 - Container or Orchestration info (Kubernetes and Docker)
 - Browser (Google Chrome, IE)

 - Other info

**Additional context**
Evaluate-STIG outputs a large amount of data on several findings for Domain Controllers. It is possible this code may need altered or the Findings section of the .ckl could be truncated manually. But filesize restriction on STIGMAN could be problematic for large file imports.

**Comment by cd-rite** [comment]
I think this is an issue with your nginx config. It is limiting the size of your uploads. 
This site https://www.tecmint.com/limit-file-upload-size-in-nginx/  suggests  client_max_body_size needs to be increased, and nginx restarted.  I'd suggest setting it to at least 100M, perhaps 1000M to account for large imports. 

Let me know if that works for you, and I'll close this issue.

**Comment by csmig** [comment]
I agree with @cd-rite that the output from @nren-matt  was generated by nginx. So look there to start.

But our API also sets size limits on requests, which can be controlled with environment variables. Specifically:
![image](https://user-images.githubusercontent.com/33138761/112141353-91664800-8bab-11eb-945e-d54d133d7079.png)

**Comment by Ngpriddy** [comment]
Hello,

I was able to increase the body size for our ingress-nginx controller to 20MB. This did not solve our issue though. I also had to set the STIGMAN_API_MAX_JSON_BODY size to the equivalent of 20MB. This allowed the file to fully upload and solved our issue!

With Developer Tools open, it looks like the upload was 7.9MB. @nren-matt can verify, but I believe this is one of our larger, if not the largest, files.

**Comment by cd-rite** [comment]
Wow! That's good to know, thanks! Is that huge size due to the Commentary and Details that Evaluate STIG produces?
If that's the case, we will probably up our default value to 20MB as well, as we know that tool is commonly used.

**Comment by Ngpriddy** [comment]
Yes, the Evaluate STIG output with the Windows domain controller STIG can be very large. I don't think it would have to go as high as 20MB, I could probably lower it to 10MB and not have any issues, but I'd defer to @nren-matt on if they were expecting any larger that 10MB files.

**Comment by csmig** [comment]
@Ngpriddy Thanks for the report about file size from DevTools. I'll second the Wow! from @cd-rite.

You said it was a domain controller STIG. The only DC STIG in the current STIG Library is the Windows 2012 DC STIG with 371 checks. If the JSON representation of those results is 7.9 Mb, then my back of the envelope math says the commentary for each result averages 20kb. That far exceeds our design expectations and experience. What is your team recording in there?

I can't see a validator needing/wanting to consume so much text, but that's not my business. I will note that the UI (especially the Collection review grid) will probably not handle this very well. We might need to consider truncating the commentary text within a grid row and offering a button that opens a large window to display what is essentially a text document. Also, be aware that the database storage will become very large since we store the full-text history of each individual review, and that's a lot of big BLOBs.

**Comment by nren-matt** [comment]
So there are really only 4 (maybe 5) V-IDs that produce large outputs on the Windows Server 2016/2019 STIG when applied to Domain Controllers. The Evaluate-STIG tool is very cut and dry with output, as it uses directly what is referenced in the STIG. This output relates to user accounts, and permissions AD and can be very verbose for a large domain (as in NREN). These 4-5 V-IDs average around 1-3.5 Mbs per Finding Details text.

**Comment by cd-rite** [comment]
Wow! Ok! It's good to know that those really large comments are not evenly distributed throughout the STIG.... It will inform the interface we need to devise to display those comments.  I'll create another issue to address that change specifically.
