### ISSUE TITLE
Add ability to "Pin" the STIG revisions in a Collection

### ISSUE THREAD

**Issue by cd-rite** [NUWCDIVNPT/stig-manager#194]
To support packages at various Steps of the RMF process, the app should allow Collection Owners the ability to "pin" or freeze STIGs that are assigned in their Collections.  The Pinned STIG revision is what would apply in all STIGMan contexts where another Revision is not specified. (.ckl exports, reports, default revision in asset review interfaces, etc)

Changes to:
UI:
In the STIGs Panel of Collection Management UI, allow Owner's to "pin" STIGs assigned to assets in that collection to a particular Release/version 
Reports will likely need to track that revision as well, requiring some consideration in the Status/Findings displays.

API:
Will need endpoints to set this for Collections
Reports will likely need to track that revision as well, which will require changes to statistics calculations. 

Docs:
Tests:
TBD

**Comment by cd-rite** [comment]
Hi @18gold - Thank you for your use cases! 
We recorded this issue because we thought it would be a useful feature for some users, but had not heard much actual demand for it. 
We will use your feedback when we consider what features to implement next! We are a very small team so need to be careful where we put our efforts. 

As a (very) sub-optimal workaround, our next release will include the ability to delete specific revisions of STIGs from the system.  If you've imported a newer version of a STIG, but are still primarily using the older version, you could delete the newest one and the next newest one will become the default.  That would let you export in bulk if needed.  Any results that were for the newer version would still be there but inaccessible until you import the newest one again. 

Regarding updating STIG Manager OSS, unless you are moving from one *instance* of a STIG Manager to another, you should not have to export and then import your data.  All new releases of STIGManager OSS are expected seamlessly migrate from the previous version. 

Hope that helps. Thanks for the input!

**Comment by cd-rite** [comment]
Hi @18gold -

We have released a new version of STIGMan OSS (1.0.41) that includes the STIG revision delete feature. 

One other approach that could speed up your exports (until we implement this feature), is using the Collection Review interface to export your .ckls.
Under each STIG in the NavTree, you can select "Collection Review," and in the top left of the resulting workspace, click the "Checklist" menu pulldown, then select "Revisions ->" and then the Revision you want to export. Then select the "Checklist" menu again and click "Export Results"  -> "CKL (Zip archive".  The resulting .zip archive you download will have results for the STIG revision you selected. 

This would require only one export action for each STIG in your Collection (that has a different default revision than the one you want), rather than for every Asset/STIG combination, which might be faster than what you are doing.

**Comment by TheTroubleshooter** [comment]
I personally will be looking forward to this feature being implemented in the future. I hope the future is sooner than later :-)
