### ISSUE TITLE
Add ability to switch a set of STIG assignments from one STIG to another for an entire Collection.

### ISSUE THREAD

**Issue by cd-rite** [NUWCDIVNPT/stig-manager#197]
For inscrutable reasons of their own, DISA routinely changes STIG IDs for some subset of STIGs from release to release. 
When imported into STIG Manager, these STIGs, though spiritually connected, are treated as new STIGs.  The current STIG assignments will still be pointing at the old STIG ID.  In some cases, this behavior may be desired (ie. the Collection is in RMF step 4, and can remain on the older STIG ID/revision it was originally submitted with), but the ability to quickly switch STIG assignments from one STIG to another would help remedy this situation for Collection Owners/Managers. 

This feature could use the current Collection Management STIG Assignment interface to switch a specific STIGs set of Assets from that STIG to another STIG that currently has no STIG assignments in that Collection.  (For easier implementation of this hopefully relatively rare use case, it should probably be all or nothing...only the STIG can be changed, or Assets, not both in the same operation)

**Comment by jason-henry-keyport** [comment]
Dan Ireland may have some logic that he used in Evaluate STIG that could be useful.
