### ISSUE TITLE
Remove oas-tools dependency

### ISSUE THREAD

**Issue by csmig** [NUWCDIVNPT/stig-manager#220]
[The npm package](https://www.npmjs.com/package/oas-tools) is not maintained to our standards. We've needed to patch important parts of the code and it has unnecessary dependencies exposing us to vulnerabilities. We should consider removing our dependency on it, perhaps by forking [the oas-tools project](https://github.com/isa-group/oas-tools) and maintaining it ourselves.

**Comment by cd-rite** [comment]
Investigating alternative libraries to get this functionality. 
Or possibly forking repo and providing own fixes/modifications.
