### ISSUE TITLE
FEATURE REQUEST: Ability to Drag and Drop multiple times into "Import CKL and XXCDF Files"

### ISSUE THREAD

**Issue by nren-matt** [NUWCDIVNPT/stig-manager#231]
**Is your feature request related to a problem? Please describe.**
If you drag one STIG .zip file into the Import Drag and Drop window you then have to process that file. Sometimes STIG or XXCDF files are in multiple directories and the ability to continue to Drag and Drop files before processing would be extremely convenient. 

**Describe the solution you'd like**
Drag and Drop into Import (and any other window it might be in) should allow multiple Drag and Drop operations before you are required to process the files.

**Describe alternatives you've considered**
You either have to prestage your files for one Drag and Drop operation, or do the process repeatedly.

**Additional context**

**Comment by csmig** [comment]
I'm working this issue along with #233 since they involve the same module.

**Comment by csmig** [comment]
Closed by #659
