### ISSUE TITLE
FEATURE REQUEST: Ability to delete multiple assets in Manager>>Assets Window

### ISSUE THREAD

**Issue by nren-matt** [NUWCDIVNPT/stig-manager#232]
**Is your feature request related to a problem? Please describe.**
You can only delete one asset at a time in the Manage Assets pane.

**Describe the solution you'd like**
Something similar to the Export CKL checkbox solution, but for deleting assets.

**Comment by csmig** [comment]
Decided not to use a tree for this as was suggested by @nren-matt. Instead, the Manage Assets grid now supports multiple selections. Choosing to delete will affect all the selected Assets.
