### ISSUE TITLE
BUG: "Done" button is still 'clickable' when importing data

### ISSUE THREAD

**Issue by nren-matt** [NUWCDIVNPT/stig-manager#233]
**Bug Location**

I found a bug in the:
- [ ] API
- [x] UI
- [ ] Elsewhere (Please specify)

**Bug Description:**
When importing a large amount of CKLs the done button is still accessible and 'clickable'. I'm not sure what adverse results this would have (I was scared to try it), but I think the button should be greyed out during and import. 

- [x] I have checked to see if there is already an existing issue that describes this bug.

**Comment by csmig** [comment]
I'm working this issue along with #231 since they involve the same module.

**Comment by csmig** [comment]
Closed by #659
