### ISSUE TITLE
BUG: Splunk STIG .zip won't Import

### ISSUE THREAD

**Issue by nren-matt** [NUWCDIVNPT/stig-manager#235]
**Bug Location**

I found a bug in the:
- [ ] API
- [ x] UI
- [ ] Elsewhere (Please specify)

**Bug Description:**

The Splunk STIG wouldn't import using the .zip file. I had to use the unzipped XML to import the STIG.

- [x ] I have checked to see if there is already an existing issue that describes this bug.

**Comment by cd-rite** [comment]
Thanks! Another example of inconsistent naming with DISA STIGs.  99% of the STIGs are in files that follow the pattern *xccdf.xml" but the Splunk STIG (And a few others we've now identified) end in "*STIG.xml"
We will adjust our filters for this feature accordingly!
