### ISSUE TITLE
BUG: Check Status of "Unsubmitted" Reads Incorrect Tool Tip

### ISSUE THREAD

**Issue by sagansapien** [NUWCDIVNPT/stig-manager#247]
Unsubmitted rules show the correct icon, but the hover tool tip still reads "Unsubmitted".

![image](https://user-images.githubusercontent.com/53829030/114433414-cdc80b00-9b8f-11eb-8681-152243fc2afa.png)

Thanks guys

**Comment by csmig** [comment]
Thanks, this was fixed by #242 which was included in 1.0.0-beta.26, released 2021-04-09.

**Comment by sagansapien** [comment]
D'oh! I even searched the issues before submitting this and I didn't see that you already closed it. We clearly need to pull beta 26.

Thanks

**Comment by csmig** [comment]
No worries @sagansapien! This was a bug I just noticed and fixed without a corresponding issue, so an issue search would not have revealed :-)
