### ISSUE TITLE
FEATURE REQUEST: Add history for initial import

### ISSUE THREAD

**Issue by sagansapien** [NUWCDIVNPT/stig-manager#255]
![image](https://user-images.githubusercontent.com/53829030/114910406-de74bd00-9deb-11eb-981a-33ee1bee004c.png)

CKLs imported to assets for the first time do not generate a history log. It would be useful to track when checklists were initially added to stigman, instead of waiting for a second CKL to be posted.

Thanks!

**Comment by csmig** [comment]
When a CKL imported, either the first time or subsequently, the imported Reviews become the current Reviews. Current Reviews are not historic yet, so they do not appear in the history. For a current Review, the timestamp you're looking for is found at the bottom of the Review form.

![Review](https://user-images.githubusercontent.com/33138761/114953372-3fb98200-9e26-11eb-86d7-e3aef0c4b22e.png)

If you

**Comment by sagansapien** [comment]
That works, thank you.

**Comment by cd-rite** [comment]
We've actually gotten one other user story with this expectation, so we are thinking we will make changes to address it.
Our proposal is to relabel presentations of "History" as "Log" (this distinction is an artifact of the API/DB implementation, but does not need to be carried forward to the UI). "Log" will include the current state of the Review as the latest entry.
