### ISSUE TITLE
Asset names with invalid filename characters do not work well with .ckl archive exports

### ISSUE THREAD

**Issue by cd-rite** [NUWCDIVNPT/stig-manager#266]
current behavior: 
Asset names that have slashes in them will create a new folder in the zip.
Asset names with ? do not appear in the .zip at all.

Apply filtering/substitution to Asset names (either at create/modify time in UI or upon archive file creation) to be sure files that are generated based on those names are valid. 

This substitution seems to be already happening in the Asset Review individual .ckl export function.

**Comment by csmig** [comment]
This issue affects `GET​/collections​/{collectionId}​/poam` as well.

I recommend addressing this in `/api/source/utils/writer.js`. There are [several methods there](https://github.com/NUWCDIVNPT/stig-manager/blob/1d51792b80e54b0fb503999ccfab3fdaf93b6637/api/source/utils/writer.js#L58-L111) that write an inline file response, whose implementations differ only on the mime type. Would be good to refactor these multiple convenience methods so they each call a common `writeInlineFile` method with the desired MIME type.

The new method could use [the filenamify modue](https://www.npmjs.com/package/filenamify) to transform the proposed filename to a safe name.

**Comment by csmig** [comment]
@cd-rite I just noticed you assigned this to yourself. I wrote that last message for my future-self, so feel free to take the recommendations or not!
