### ISSUE TITLE
BUG: Export CKL problems

### ISSUE THREAD

**Issue by sagansapien** [NUWCDIVNPT/stig-manager#269]
GUI

- Attempting to export CKLs for one Windows 10 asset. Export is successful and results in <asset name>.ckl. STIG Viewer produces error "Checklist failed XML schema validation for Checklist Schema 2.4"

- Attempting to export SQL 2016 Instance and Database assets appears to export successfully and saves a zip file. There should be multiple assets/ckls inside the zip but there is a single file with a partial asset name and no .ckl file extension.

Let me know what other technical details you need to help troubleshoot this issue.

Thanks!

**Comment by cd-rite** [comment]
Hmmm For the first issue it looks like we stopped populating the <Role> element with the last release. If I add it by hand after export STIG Viewer accepts the .ckl.

For the second issue we will need more info....
Can you provide the Asset metadata for the Assets in question, and the Asset elements from the .ckl that was produced?
Were the Assets created by our importer(s) from .ckl files? Can you also provide the source Asset elements from the .ckls?
Thanks.

**Comment by csmig** [comment]
Split into separate issues and closed this one
