### ISSUE TITLE
BUG: Failed to import STIGs from Cyber.mil

### ISSUE THREAD

**Issue by dssmwise** [NUWCDIVNPT/stig-manager#27]
**Describe the bug**
api_1   | [INIT] Importing STIGs...
api_1   | Retreiving list of Compilation files from public.cyber.mil...
api_1   | DOWNLOADED 100.00% of 0.07 mb
api_1   | Retreiving https://dl.dod.cyber.mil/wp-content/uploads/stigs/zip/U_SRG-STIG_Library_2020_07v2.zip
api_1   | DOWNLOADED 4.68% of 204.13 mb
api_1   | DOWNLOADED 9.35% of 204.13 mb
api_1   | DOWNLOADED 14.03% of 204.13 mb
api_1   | DOWNLOADED 18.70% of 204.13 mb
api_1   | DOWNLOADED 23.38% of 204.13 mb
api_1   | DOWNLOADED 28.05% of 204.13 mb
api_1   | DOWNLOADED 32.73% of 204.13 mb
api_1   | DOWNLOADED 37.40% of 204.13 mb
api_1   | DOWNLOADED 42.08% of 204.13 mb
api_1   | DOWNLOADED 46.75% of 204.13 mb
api_1   | DOWNLOADED 51.43% of 204.13 mb
api_1   | DOWNLOADED 56.10% of 204.13 mb
api_1   | DOWNLOADED 60.77% of 204.13 mb
api_1   | DOWNLOADED 65.45% of 204.13 mb
api_1   | DOWNLOADED 70.12% of 204.13 mb
api_1   | DOWNLOADED 74.80% of 204.13 mb
api_1   | DOWNLOADED 79.48% of 204.13 mb
api_1   | DOWNLOADED 84.16% of 204.13 mb
api_1   | DOWNLOADED 88.83% of 204.13 mb
api_1   | DOWNLOADED 93.51% of 204.13 mb
api_1   | DOWNLOADED 98.19% of 204.13 mb
api_1   | DOWNLOADED 100.00% of 204.13 mb
api_1   | Processing ZIP...
api_1   |
api_1   | [1/207] -----------------------------
api_1   | EXTRACTING: U_A10_Networks_ADC_ALG_V1R1_STIG.zip
api_1   | PROCESSING: U_A10_Networks_ADC_ALG_V1R1_STIG.zip
api_1   | PARSING   : U_A10_Networks_ADC_ALG_V1R1_Manual_STIG/U_A10_Networks_ADC_ALG_STIG_V1R1_Manual-xccdf.xml
api_1   | Connection 8 STATS ENTER
api_1   | Connection 8 STATS SELECT
api_1   | Connection 8 STATS UPDATE
api_1   | Connection 8 STATS ERROR Named query contains placeholders, but parameters object is undefined
api_1   | Error: Named query contains placeholders, but parameters object is undefined
api_1   |     at toArrayParams (/home/node/node_modules/named-placeholders/index.js:95:13)
api_1   |     at compile (/home/node/node_modules/named-placeholders/index.js:144:12)
api_1   |     at PoolConnection._resolveNamedPlaceholders (/home/node/node_modules/mysql2/lib/connection.js:486:17)
api_1   |     at PoolConnection.query (/home/node/node_modules/mysql2/lib/connection.js:499:10)
api_1   |     at /home/node/node_modules/mysql2/promise.js:98:11
api_1   |     at new Promise (<anonymous>)
api_1   |     at PromisePoolConnection.query (/home/node/node_modules/mysql2/promise.js:93:12)
api_1   |     at Object.module.exports.updateStatsAssetStig (/home/node/service/mysql/utils.js:425:39)
api_1   |     at runMicrotasks (<anonymous>)
api_1   |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
api_1   |     at async Object.exports.insertManualBenchmark (/home/node/service/mysql/STIGService.js:733:5)
api_1   |     at async processZip (/home/node/utils/fetchStigs.js:140:20)
api_1   |     at async processZip (/home/node/utils/fetchStigs.js:153:7)
api_1   |     at async Object.fetchCompilation (/home/node/utils/fetchStigs.js:80:7)
api_1   |     at async startServer (/home/node/index.js:160:7)

I found a bug in the:
- [X] API

Please include a clear and concise description of what the bug is.
When importing the Docker instance described here (https://hub.docker.com/r/nuwcdivnpt/stig-manager) it appears to fail to retrieve the STIGs from cyber.mil.  After this failure the container loads and I am able to log into the localhost instance of STIG_Manager where I also tried to import them into the running STIG_Manager and that failed with the same errors as above.  My instance of Docker is for windows with the WSL2 installed.  STIG_Manager otherwise appears to be running.  I can log in create a collection and add assets and users.  Just cannot import STIGs against the assets because the benchmark data from cyber.mil was not imported.  All attempts to import completed STIGs are ignored.  

- [X ] I have checked to see if there is already an existing issue that describes this bug.
I also looked over the documentation to ensure that I did not miss anything.  Though I may have somewhere.  I know that Node.js is required but assumed it was part of the Docker Container that was downloaded.  Was not clear in the installation instructions. 

**To Reproduce**
https://hub.docker.com/r/nuwcdivnpt/stig-manager Folow steps here. 

**Expected behavior**
For the STIGs to import as advertised "On initial container startup, STIG Manager will connect to DoD Cyber Exchange and import the latest STIG Library Compilation and any available SCAP content."

**Actual behavior**
What behavior did you actually experience?  Failed to import the STIGS 

**Screenshots**
![image](https://user-images.githubusercontent.com/73548182/97333887-70930400-1852-11eb-902c-e6d538ac4db3.png)

**Environment or Configuration:**
 - Docker Container installed using the Docker folder from the source code using the YML file from https://hub.docker.com/r/nuwcdivnpt/stig-manager
 - Chrome browser
 - Failed when running the "docker-compose up -d && docker-compose logs -f" command to initialize the containers and site.

**Comment by csmig** [comment]
Thanks dssmwise, great reporting. This critical regression has been fixed and a new image is available on Docker Hub.
