### ISSUE TITLE
CKL zips without correct content

### ISSUE THREAD

**Issue by csmig** [NUWCDIVNPT/stig-manager#271]
Split from https://github.com/NUWCDIVNPT/stig-manager/issues/269#issue-868899797 by @sagansapien

Attempting to export SQL 2016 Instance and Database assets appears to export successfully and saves a zip file. There should be multiple assets/ckls inside the zip but there is a single file with a partial asset name and no .ckl file extension.

**Comment by csmig** [comment]
From @cd-rite [here](https://github.com/NUWCDIVNPT/stig-manager/issues/269#issuecomment-827689988) 

> Hmmm For the first issue it looks like we stopped populating the `<ROLE>` element with the last release. If I add it by hand after export STIG Viewer accepts the .ckl.
> 
> For the second issue we will need more info....
> Can you provide the Asset metadata for the Assets in question, and the Asset elements from the .ckl that was produced?
> Were the Assets created by our importer(s) from .ckl files? Can you also provide the source Asset elements from the .ckls?
> Thanks.
> 
> edit: I suspect this issue is due to characters that are not valid in filenames, and we do not yet have our filename filters in place. Do the Asset names and/or metadata have any of these characters in them?
> 
> ```
> < (less than)
> > (greater than)
> : (colon)
> " (double quote)
> / (forward slash)
> \ (backslash)
> | (vertical bar or pipe)
> ? (question mark)
> * (asterisk)
> ```

**Comment by csmig** [comment]
The Asset metadata should not be in play here.

CKL filenames are derived from the STIG Manager Asset name. If possible, please change the name(s) of the Asset(s) having issues to strings without the Windows illegal characters listed by @cd-rite and report the outcome. Thanks.

**Comment by csmig** [comment]
Created an asset with name `Asset-<>:"/\|?*` and exported a CKLzip archive for it.

The quote is a problem vfor sure, the filename is truncated to `Asset-<>:` in the ZIP, which could easily cause collisions and result in just one file instead of many.

Stronger evidence this is related to #266.

**Comment by sagansapien** [comment]
Since Evaluate-STIG was just updated to use double quotes to separate parts of the database/instance field, the asset in stigman had double quotes. I removed the quotes from the stigman asset and the checklist was exported successfully. 

The exported CKL retained the original data with quotes and looked like this:

instance field:

"hostname"_"databaseName"

**Comment by csmig** [comment]
Should be resolved by #273. Closing, please reopen if the issue continues.
