### ISSUE TITLE
Support for Microsoft SQL Server

### ISSUE THREAD

**Issue by cd-rite** [NUWCDIVNPT/stig-manager#274]
Create a new DB service for SQL Server

**Comment by csmig** [comment]
I recommend we initially code against MSSQL 2019 (mainstream support through 2025-01-07) with gentle fallback to MSSQL 2017. However, there doesn't appear to be a STIG for any version after MSSQL 2016, whose mainstream support ends in July 2021. Not sure what to make of that, maybe the STIG is coming soon.

**Comment by cd-rite** [comment]
Received new input from users.  Will not need this feature for foreseeable future.
