### ISSUE TITLE
STIG import too large

### ISSUE THREAD

**Issue by dssmwise** [NUWCDIVNPT/stig-manager#29]
![image](https://user-images.githubusercontent.com/73548182/97449239-d8efed00-1907-11eb-9eb4-0a762b0409d9.png)
When trying to upload the windows 10 STIG CKL file for one of our systems is fails with the attached message.  Post request is too large.  I assume its referring to the size of the file being imported.  The smaller CKL's seem to be importing fine but the 1.5mb Windows 10 CKL files are failing.  They are so large because of all the test data generated by Evaluate-STIG (Tool that generates the CKL's for us)  there is a lot of text in the comments and finding details that we do not want to lose.  

Please let me know if further information is needed to recreate this issue.

**Comment by csmig** [comment]
Hello again, dssmwise! Really appreciate the feedback. Pretty sure this is just hitting a configurable limit on request body size. We haven't generated CKLs that big during testing, but I will go off and generate some. I'm guessing 5 MB might be a reasonable limit that balances potential DDOS with the real-world size of some CKLs?

**Comment by csmig** [comment]
Looks like we're hitting Express' default 100kb limit on JSON request body size. The 1.2MB CKLs we used for testing produced JSON of about 66 kb, so we didn't trigger this limit. @cd-rite I think a 1 MB limit on JSON body could work? But perhaps we'll just end up here again, so maybe shoot higher? 

More background: This issue only affects calls to POST ​/collections​/{collectionId}​/reviews​/{assetId} where the CKL has been serialized in the Web client to JSON (Content-Type application/json). CKLs that are parsed directly by the API (Content-Type multipart/form-data) pass through multer, which has a size limit of Infinity. Perhaps that is a bit too generous.

**Comment by cd-rite** [comment]
Ooh good catch, @dssmwise. Is that about your largest .ckl? How big do they get?
@csmig I think the 5MB limit would be reasonable, considering multiple STIGs can be expressed in one .ckl, and there can be very large comments/details included. 
Perhaps that limit (and the form-data limit) should be configurable?

**Comment by csmig** [comment]
Okay, I'll add envvars for both limits tonight, test and release. Defaults 5mb json and 1gb files

**Comment by dssmwise** [comment]
Great.  Thanks.  Just a note that I have not seen a CKL at my site greater than 2MB but like @cd-rite mentioned, a CKL can have multiple STIGs included in it though in my experience that is rarely done. Thanks for the quick responses on these.

**Comment by csmig** [comment]
Welcome to our nascent community @dssmwise. Your contributions are very helpful. I don't like these show-stopper type bugs! We're really close to having automated Newman tests in our pipeline, but not quite there.
