### ISSUE TITLE
FEATURE REQUEST: Ability to Export Batches of Individual STIGs

### ISSUE THREAD

**Issue by sagansapien** [NUWCDIVNPT/stig-manager#291]
![image](https://user-images.githubusercontent.com/53829030/117065183-2739da80-acf5-11eb-927c-92992e2adaf5.png)

The current "Export CKLs..." wizard exports a single serialized CKL, named simply as the asset name, which contains one or multiple STIGs.

Requesting a second button or export option which tells the export function to create a individual CKL for each STIG selected with file names that match CKL files exported from Collections > Assets > STIG > Checklist drop down > Export CKL.

File name conventions for both methods should be consistent with Navy SCA guidance. Maybe a Collection level preference which enables customization of the file name format?

Thanks.

**Comment by cd-rite** [comment]
After further investigation, it was determined that implementing this feature will require more effort than originally anticipated.
Moving back to the backlog, for now. 

*Suggested workaround:*
From Collection Management screen, start from the *STIG* .ckl export interface, then select and export *one* STIGs worth of Assets (or whichever Assets are selected) at a time. If only one STIG is selected for any given asset via this interface, the exported archive will contain .ckls that only contain that one STIG for that asset.
