### ISSUE TITLE
FEATURE REQUEST: Recycle Bin

### ISSUE THREAD

**Issue by sagansapien** [NUWCDIVNPT/stig-manager#293]
Thanks for adding the drag from history feature!

Respectfully requesting the addition of an instance-level recycle bin where things such as deleted collections are moved to, for a period, before final deletion. Similarly, a collection-level recycle bin where deleted assets are moved to prior to final deletion.

Database backups are a key component for disaster recovery, however database restore operations for simple user-level mistakes may be impractical. Allowing STIG Manager client users the ability to quickly undo certain key actions may be desired.

Low priority! Just dreaming here!

Thanks

**Comment by cd-rite** [comment]
After discussion, found this Issue could be satisfied by providing a mechanism for easily moving Asset(s) from one Collection to another (ie, from a curated Collection associated with Package, to a scrap Collection maintained by the user)
