### ISSUE TITLE
FEATURE REQUEST: Add "Not Reviewed" report

### ISSUE THREAD

**Issue by sagansapien** [NUWCDIVNPT/stig-manager#303]
The "Findings" report is very useful. Requesting an similar report to quantify Not Reviewed checks as well, since ultimately NR checks require action from either the SA or ISSO and ends on the POAM anyways. We consider all NR findings to be Open.

Thanks!

**Comment by jason-henry-keyport** [comment]
Just to support the idea of an NR being open.  Kind of similar to treating a firearm as if it's loaded until verified otherwise.

**Comment by cd-rite** [comment]
New metrics report and Collection panel (1.3.0) makes it easier to get a handle on which Assets and STIGs have large numbers of "NR" reviews by rolling NR and non-compliance Results into an "Assessed" percentage.
