### ISSUE TITLE
FEATURE REQUEST: Binary Evidence

### ISSUE THREAD

**Issue by thomaspari** [NUWCDIVNPT/stig-manager#312]
**Is your feature request related to a problem?** 
When completing benchmarks many times a textual response is accompanied with a screenshot or an image of the evidence.  I do not see this feature as part of the open source version of STIG Manager.   This requires an external file share or repository to manage a file(s) that contain the binary evidence.

**Describe the solution you'd like**
A feature that enabled a user to associate binary evidence or an uploaded attachment as evidence would be a helpful in the central management of the assessment.  Additionally one would need a feature to export the evidence.  Perhaps when one exports the checklist is exports the checklist and the evidence in a zip archive format.

**Describe alternatives you've considered**
Without the central management of binary evidence one has to build a parallel system (Sharepoint, AWS S3 drive, etc) to store the evidence.  Once stored the rule would have to provide a textual link to the binary evidence.

**Additional context**
None at this time.

**Comment by cd-rite** [comment]
Hi @thomaspari At this point, I think this feature is a little beyond the scope of the project as it stands right now, but I've put it in the backlog so it will be on our minds.   Using a purpose-built storage service like S3 or Azure Blob storage would probably have much better performance as well.  

I think if we add support for metadata at the review-level, then clients could make use of that feature to get some pretty good integration with one of these storage solutions.  An identifying guid from, say, Azure Blob Storage could be stored in metadata at the review, asset, or collection level and fetched by a client that understood that metadata entry to generate export archives with the associated evidence included.

In any scenario, supporting metadata at the Review level in the STIGMan API would be the first step to enabling this kind of integration, whether our own solution or an external one. I've created an issue for that #317 
Thanks!
