### ISSUE TITLE
BUG: "All checks" drop down filter doesn't work

### ISSUE THREAD

**Issue by sagansapien** [NUWCDIVNPT/stig-manager#32]
**Describe the bug**

I found a bug in the:
- [ ] API
- [x] UI
- [ ] Elsewhere (Please specify)

There is a drop-down filter for "All checks" under the _Collection review_ node which doesn't appear to work. "Manual checks" and "SCAP checks" are visible but nothing happens when you click them. This is not a problem when viewing a specific asset; the issue is only apparent under the collection review node.

Additionally, the free text filter has no effect here either.

- [x] I have checked to see if there is already an existing issue that describes this bug.

**To Reproduce**
1. Go to Collections > STIGs > (some STIG) > Collection Review
2. Click on "All checks"
3. Try selecting "Manual checks" for "SCAP checks"
4. Nothing happens
5. Type something into the filter text
6. Nothing happens

**Expected behavior**
Filter should be selectable, free text filter should work

**Actual behavior**
Filter options are visible but not selectable. Free text can be entered but nothing happens.

**Screenshots**
![stig_manager_filter](https://user-images.githubusercontent.com/53829030/98042087-f255d500-1df0-11eb-8b70-48d277a72a5b.PNG)

**Environment or Configuration:**
 - Docker community for Windows. STIG Manager version beta 3.
 - Chrome and Microsoft Edge

**Comment by csmig** [comment]
@sagansapien Thanks so much for the well documented report. I replicated this and have fixed it. I'll open a PR now. I expect to merge this fix and a couple others tonight and push a new image to Docker Hub.
