### ISSUE TITLE
Tests for Prune History feature

### ISSUE THREAD

**Issue by cd-rite** [NUWCDIVNPT/stig-manager#334]
Create known number of history entries for given asset/rule in the test collection.
Send request to endpoint specifying deletions, check removed records response against new number of history entries for given asset/rule in the collection.

**Comment by NRENJeff** [comment]
Would it be possible to have this enhancement be time based? Internally I could see the use of having history of everything from the previous year.

**Comment by cd-rite** [comment]
Yep! It is our intent to allow the user to specify either X number of Days worth of history and/or X number of entries to keep.
