### ISSUE TITLE
CKL comment elements should be mappable in UI

### ISSUE THREAD

**Issue by csmig** [NUWCDIVNPT/stig-manager#347]
Users should be able to choose how the `<FINDING_DETAILS>` and `<COMMENT>` CKL elements are mapped to the API Review properties `resultComment` and `actionComment`. This could be offered as a Collection setting or at each import/export

The current UI behavior follows Navy SCA guidance, but Air Force Cloud One does not have the same policy.

Need to discuss how to handle the pop-up help in the Review panel where we currently show the Navy guidance

**Comment by csmig** [comment]
Renamed and expanded the issue to cover a Collection settings feature that allows users to control how the commentary fields are used. My raw notes:
```
Review fields
-----------------
                Active       Requirement
Result comment: [Always]     [Required when failing]

Action:         [Failures]   [Required when failing]

Action comment: [Always]     [Optional]

Default CKL mapping
-------------------
Result comment:  [FINDING_DETAILS]

Action and 
Action Comment:  [COMMENT]

Workflow
--------
[Approvals] [No approvals]


resultComment:
    active: 
        type: string
        enum:
            - always (default)
            - fails
    content:
        type: string
        enum:
            - optional
            - required-always (default)
            - required-fails
```

**Comment by csmig** [comment]
Expanding this issue was not a bright move. I'll open a new issue for the field handling.

**Comment by cd-rite** [comment]
Moving this out of the Out-of-Beta project since it may no longer be needed due to new Review Field requirement options.

**Comment by cd-rite** [comment]
Rather than implementing mappable .ckl elements, we believe this request is satisfied by the new customizable status requirements for Review commentary feature from #442
