### ISSUE TITLE
Alter spec for Review metadata endpoint(s?) specifying the expected return object (or lack thereof)

### ISSUE THREAD

**Issue by cd-rite** [NUWCDIVNPT/stig-manager#349]
requests to PUT /collections/{collectionId}/reviews/{assetId}/{ruleId}/metadata/keys/{key}

always returns 204.
That's probably the desired behavior (or a 200?), but the spec indicates it should return the metadata for that review.

Need to alter spec.

**Comment by csmig** [comment]
Noted with appreciation, but closing the issue because this feature has no open PR and has not yet been merged.
