### ISSUE TITLE
BUG: TypeError: Cannot read property 'trim' of undefined

### ISSUE THREAD

**Issue by NRENJeff** [NUWCDIVNPT/stig-manager#359]
**Bug Location**

I found a bug in the:
- [ ] API
- [x] UI
- [ ] Elsewhere (Please specify)

**Bug Description:**
When looking at any rules in the following STIGs, HBSS_AssetModule V4R8 and HBSS_HIP_8 V5R1, the UI throws an error when clicking on an asset in a collection it throws "TypeError: Cannot read property 'trim' of undefined".

- [x] I have checked to see if there is already an existing issue that describes this bug.

**To Reproduce**
1. Import the following STIGs: HBSS_AssetModule V4R8 and HBSS_HIP_8 V5R1
2. Create asset and assign the above STIGs to them. The same asset has both STIGs applied to it in our environment.
3. Click on the asset under one of the above STIGs and the error apears.
4. When changing to a different Rule Id the error also appears.

**Expected behavior**
No error and the Rule ID should display text.

**Actual behavior**
TypeError: Cannot read property 'trim' of undefined" was thrown by the browser.

**Screenshots**
![Clipboard - July 21, 2021 10_49 AM](https://user-images.githubusercontent.com/87772254/126523403-79ae5364-0002-4fe4-8e40-994adfe24c49.png)

**Environment or Configuration:**
 - Container: nuwcdivnpt/stig-manager:latest-ironbank "1.0.0-beta.35"
 - Browser: Chrome 91.0.4472.114 or Edge 91.0.864.71

**Comment by cd-rite** [comment]
Thanks! We will check this out. Can you verify what STIG-Manager version you are using?

**Comment by NRENJeff** [comment]
Responding here for others to see. We're running "1.0.0-beta.35".
