### ISSUE TITLE
Allow Restricted User access to Collection Review workspace.

### ISSUE THREAD

**Issue by NRENJeff** [NUWCDIVNPT/stig-manager#365]
**Is your feature request related to a problem? Please describe.**
It would be beneficial if the "Review Resources" area would retain it's state when moving to different Rule IDs.

**Describe the solution you'd like**
When I'm looking at a the Result Comment text of one asset and move to the next Rule ID it would be nice if that asset was still expanded.

**Describe alternatives you've considered**
An alternative we would like to propose would be to enable the "Collection Review" area for "Restricted Users". This might be easier to implement.

**Additional context**
Example with "Other Assets" shown, but the request was for that whole section to retain it's state.
![image](https://user-images.githubusercontent.com/87772254/126686842-57e854ed-971b-4d72-84fd-993137aa5f47.png)
Then if you click on the Rule ID below the first.
![image](https://user-images.githubusercontent.com/87772254/126686924-58e11b41-00e8-49b9-9928-d63cb7a6e18c.png)
The "Workstation2" asset is now closed. My users would prefer it if the expanded selection would stay open.

**Comment by cd-rite** [comment]
Hi @NRENJeff  Thanks, we will keep this under advisement. However, If your users are interested in easy access to the "Other Assets" info, the Collection Review workspace may be a more convenient place to work in! 
It shows every Asset's reviews(That the user has access to in that Collection) for a particular rule, and that grid is editable. Just double-click on the field they want to edit:
![image](https://user-images.githubusercontent.com/61710958/126695276-4abdcf63-444f-4f7e-a979-1b6bd9710d50.png)

**Comment by NRENJeff** [comment]
I didn't notice that. I actually think that might work for us as an alternative!

**Comment by NRENJeff** [comment]
Added an alternative that involves giving access, to the "Collection Review" section, to Restricted Users.

**Comment by cd-rite** [comment]
Thanks @NRENJeff we will do this soon. It was actually our intent to expand access to the Collection Review workspace for all users, but it slipped by us.
