### ISSUE TITLE
BUG: vSphere 6.7 (EAM Tomcat, Perfcharts, Photon OS, PostgreSQL, RhttpProxy, STS Tomcat, UI Tomcat, VAMI-lighttpd, Virgo-Client) STIGs not showing expected code

### ISSUE THREAD

**Issue by NRENJeff** [NUWCDIVNPT/stig-manager#378]
**Bug Location**

I found a bug in the:
- [ ] API
- [X] UI
- [ ] Elsewhere (Please specify)

**Bug Description:**
When viewing the VMware vSphere 6.7 EAM Tomcat STIG (specifically V-239385, but the issue happens on at least one Vuln ID in each of the vSphere 6.7 STIGs) it looks like the UI is parsing the code snippets in the check/fix text.

- [X] I have checked to see if there is already an existing issue that describes this bug.

**To Reproduce**
1. Open any of the above STIGs (my screen shots are from the EAM Tomcat STIG)
2. Click on a Vul/Rule ID that has XML in it.
3. See error

**Expected behavior**
XML shouldn't be parsed.

**Actual behavior**
XML was parsed.

**Screenshots**
From the java STIG Explorer:
![image](https://user-images.githubusercontent.com/87772254/127537665-062e01d3-0432-4017-8324-84049969e4fd.png)

From STIG-Manager OSS:
![image](https://user-images.githubusercontent.com/87772254/127537828-6cbf3cd1-aed9-4bb3-8b2d-4dd85f86ba14.png)

**Environment or Configuration:**
 - Container or Orchestration info: NA
 - Browser: latest Chrome/Edge

**Additional context**

**Comment by cd-rite** [comment]
Thanks for catching this! We will start escaping Rule texts for cases like this where they include html-formatted content.
