### ISSUE TITLE
mysql2 bug causes an uncaughtException during container startup

### ISSUE THREAD

**Issue by csmig** [NUWCDIVNPT/stig-manager#381]
Need to override [`Connection._notifyError()`](https://github.com/sidorares/node-mysql2/blob/4e22e33495287c4c46336154ccfba01d3b23e9df/lib/connection.js#L198) to cancel the timeout Timer as is [done here](https://github.com/csmig/stig-manager/blob/010335652d4a4dc0f0d950e2e6c09a994fcb91da/api/source/service/mysql/utils.js#L3-L11)

**Comment by russdj** [comment]
This bug appears to have been fixed in mysql2 2.2.0 according to https://github.com/sidorares/node-mysql2/pull/950
Discussed with Carl, and the error occurred with 2.1.0.  Currently, stig-manager's package.json uses 2.2.5.  Recommend cancelling/closing this issue with no change.
