### ISSUE TITLE
migration files should use await

### ISSUE THREAD

**Issue by csmig** [NUWCDIVNPT/stig-manager#392]
files 0007 - 0009

**Comment by csmig** [comment]
The corresponding lines are the issue in the three files:
https://github.com/NUWCDIVNPT/stig-manager/blob/c00013174670a2babbefe51c1cf3d0167a9e13b5/api/source/service/mysql/migrations/0007.js#L36
https://github.com/NUWCDIVNPT/stig-manager/blob/c00013174670a2babbefe51c1cf3d0167a9e13b5/api/source/service/mysql/migrations/0007.js#L55

**Comment by cd-rite** [comment]
resolved in #476
