### ISSUE TITLE
STIG Manager on OSS

### ISSUE THREAD

**Issue by butterlettuce56** [NUWCDIVNPT/stig-manager#393]
I followed the guide on GitHub using docker-compose. All three containers startup and produce the desired output in the log, but when I visit http://IP_ADDRESS:54000 all I see is a splash screen saying "Loading STIG Manager". What am I doing wrong?

https://hub.docker.com/r/nuwcdivnpt/stig-manager

**Comment by csmig** [comment]
I'm reading between the lines here, but it seems you may be trying to access STIG Manager from a remote browser that is not running on the same host as docker-compose? The default compose file we provide supports only localhost connections, but this can be adjusted.

First, please verify you can run the web client from a local browser running on the same host that is executing docker-compose. Navigate to `http://localhost:54000` and you then should be redirected to the Keycloak login page at `http://localhost:8080`. Once you log in, you should be redirected back to `http://localhost:54000` 

If you wish to allow access to the STIG Manager instance from remote browsers, you'll need to modify your `docker-compose.yml` and uncomment and set the envvar which is noted in our sample:

```
      # Set envvar below if non-localhost browsers will access the API
      # - STIGMAN_CLIENT_KEYCLOAK_AUTH=<the Keycloak authorization URL relative to the Client>
```
For the current beta release, the value of `STIGMAN_CLIENT_KEYCLOAK_AUTH` should be `http://<YOUR_DOCKER_HOST_IP_ADDRESS>:8080/auth`

After doing this, execute `docker-compose down`, followed by `docker-compose up`. You should now be able to use the web client from remote browsers by navigating to `http://<YOUR_DOCKER_HOST_IP_ADDRESS>:54000`. **This requires you have no firewall rules or other impediments that prevent hosts on your network from connecting to TCP ports 54000 and 8080 on your docker-compose host.**

Let us know how it goes...

**Comment by butterlettuce56** [comment]
You nailed it! My host doesn't have a GUI so I went right to editing docker-compose.yml and it works. Thank you very much.

**Comment by csmig** [comment]
Yay! If you're checking out the software features, our [sample demonstration data](https://github.com/NUWCDIVNPT/stig-manager/raw/main/data/appdata/appdata-small.zip) can be a helpful start. The sample data requires [certain STIGs be installed.](https://github.com/NUWCDIVNPT/stig-manager/tree/main/data/appdata)

You load the sample data using the UI. Navigate to Administration -> Application Data -> Replace Application Data. Reload the browser to see the new data set.

The current sample data has reviews for many previous STIG revisions, so unless you were to install earlier STIG revisions, you won't see as many reviews as we'd hoped. We have issue #390 to update the sample data very soon and we know we could document this a bit better.
