### ISSUE TITLE
UI shouldn't try to elevate in Collection Manager

### ISSUE THREAD

**Issue by csmig** [NUWCDIVNPT/stig-manager#397]
[This line](https://github.com/NUWCDIVNPT/stig-manager/blob/d8942e24fd834ff7a374d66b2c3e07b3206b8ee3/clients/extjs/js/collectionManager.js#L29) and [this line](https://github.com/NUWCDIVNPT/stig-manager/blob/d8942e24fd834ff7a374d66b2c3e07b3206b8ee3/clients/extjs/js/collectionManager.js#L167) should be removed.

**Comment by cd-rite** [comment]
Those lines are now removed.
