### ISSUE TITLE
Keep user session alive even when idle.

### ISSUE THREAD

**Issue by cd-rite** [NUWCDIVNPT/stig-manager#405]
To avoid the user having to reauthenticate, requiring a redirect, try to update access token before it expires.

**Comment by csmig** [comment]
Actually, we shouldn't let the refresh token expire. It is okay to let an access token expire, as long as we use the refresh token to get a new set of tokens (access, id, refresh) before the refresh token expires.

**Comment by cd-rite** [comment]
Ah, ok. I thought there was an issue in environments where the refresh token expiration is not provided.  But I guess we wind up in the same place.
