### ISSUE TITLE
Reject counts not provided as part of adminStats projection 

### ISSUE THREAD

**Issue by cd-rite** [NUWCDIVNPT/stig-manager#438]
Since the `adminStats` projection can be invoked by any user, I suggest the value should be changed to `statusStats`.

`adminStats` is a property of the schema `AssetProjected`. It should be updated to:
```
statusStats:
  type: object
  properties:
    stigCount:
      type: integer
    stigAssignedCount:
      type: integer
    ruleCount:
      type: integer
    acceptedCount:
      type: integer
--> rejectedCount:
      type: integer
    submittedCount:
      type: integer
```

This issue should also address the `CollectionStig` schema, which is the response of `GET ​/collections​/{collectionId}​/stigs`:
```
CollectionStig:
  type: object
  properties:
    benchmarkId:
      type: string
    title:
      type: string
    lastRevisionStr:
      type: string
    lastRevisionDate:
      type: string
    ruleCount:
      type: integer
    assetCount:
      type: integer
    acceptedCount:
      type: integer
--> rejectedCount:
      type: integer
    submittedCount:
      type: integer
    savedCount:
      type: integer
```

**Comment by csmig** [comment]
This issue should also address the `CollectionStig` schema, which is the response of:
```
GET ​/collections​/{collectionId}​/stigs
```

**Comment by csmig** [comment]
Since the `adminStats` projection can be invoked by any user, I suggest the value should be changed to `statusStats`.

**Comment by cd-rite** [comment]
We might also consider including the min and max values for the individual minTs and maxTs stats we track.
