### ISSUE TITLE
Endpoints/projections that return STIG->Collection mappings

### ISSUE THREAD

**Issue by csmig** [NUWCDIVNPT/stig-manager#492]
`GET /collections/{collectionId}` includes a projection that returns the STIG mappings for a specific Collection. This endpoint accepts elevated requests.

We should implement a pivot of this: An elevatable endpoint which returns the list of collectionIds mapped to a specific STIG.

Initial proposal:
`GET /stigs/{benchmarkId}/collections`

However, Application Managers would have to iterate over each STIG to get an overall report of which STIGs are mapped.

Therefore, we should also consider a `statistics` projection to `GET /stigs` that includes a count of collections. We would probably need to allow elevated requests for this projection, so this might conflict with our notion to make the `GET /stigs/...` endpoints independent of the STIG Manager DAC and RBAC.

**Comment by cd-rite** [comment]
This might get immediately reopened, but we brushed upon this today in the context of new "Default" Revision property for Collections. Decided that STIGs endpoints should not return Collection-specific content. 
Possible: STIGs could return a flag, indicating whether a particular Revision was set as the Default for 1 or more Collections.
