### ISSUE TITLE
Client: for packages with no assets, STIGs node unrolls to empty STIG leaf

### ISSUE THREAD

**Issue by cd-rite** [NUWCDIVNPT/stig-manager#5]
Issue can be replicated thusly:
Create package with no assets assigned.
Refresh reviews nav tree.
Package displayed in nav tree, but STIGs node can, unintuitively, still be expanded (to empty stig symbol).

**Comment by csmig** [comment]
Fixed by cb913925d94a7a6827dee6f64228039a74b0a8be in branch phase-1-dev
