### ISSUE TITLE
BUG: 1.41 Export CKL does not export CKL comments

### ISSUE THREAD

**Issue by 18gold** [NUWCDIVNPT/stig-manager#504]
**Bug Location**

I found a bug in the:
- [x] API
- [ ] UI
- [ ] Elsewhere (Please specify)

**Bug Description:**

When exporting CKLs from a collection, the CKL comments are not exported. 

- [x] I have checked to see if there is already an existing issue that describes this bug.

**To Reproduce**
1. Go to a collection 
2. Highlight assets to be exported
3. Click "Export CKLs"
4. Review CKLs in external application (STIG Viewer/notepad/etc)

**Expected behavior**
CKLs to be exported with comments

**Actual behavior**
CKLs exported without comments.

**Environment or Configuration:**
 - docker deployment
 - Firefox
 - Version 1.41 and 1.40

**Additional Details**
We have confirmed the issue does not exist in 1.38 but began in 1.40 and persists in 1.41

**Comment by cd-rite** [comment]
Hi @18gold
I am unable to duplicate your issue, so I will need a little more info...
- Did you populate your reviews with an import via the UI, manually evaluating in the UI, or via Watcher??
- Can you confirm you see comments when you look at reviews for individual Assets in the Asset Review workspace?
- Did you update very recently? If you left your browser open to STIGMan, it may be holding on to an older version of the client.... (a simple refresh should fix this, but you can also verify from the little sprite at the top of the hometab).
- Can you try exporting an individual .ckl file from the Asset Review workspace, and see if you have the same issue?

![image](https://user-images.githubusercontent.com/61710958/140392553-55ab5fea-f3a8-41d1-a678-2a0ad2e4503b.png)

Thanks!

**Comment by 18gold** [comment]
1) The reviews were entered manually via the UI
2) We can see the comments for individual assets 
3) We updated 2 days ago from 1.40 but this is the first export we've attempted. We've since closed browsers and also rebooted containers/host
4) Exporting an individual .ckl file results in the same issue

**Comment by cd-rite** [comment]
@18gold 
Ahhhh, thank you! 
We can reproduce this now. We will have a fix for you soon.

**Comment by 18gold** [comment]
Fantastic! Will the fix come as a release or how should we apply the fix to the container?

**Comment by csmig** [comment]
Appreciate the bug report, @18gold . This was an unfortunate regression as we rework the commentary fields to support our sponsor better.

I've published and signed new container images to Docker Hub for for 1.0.42
