### ISSUE TITLE
BUG: Import of CKL with numeric FINDING_DETAILS value fails with the error 'vuln.FINDING_DETAILS.trim is not a function'

### ISSUE THREAD

**Issue by DavidAmond** [NUWCDIVNPT/stig-manager#508]
**Bug Location**

I found a bug in the:
- [ ] API
- [X] UI
- [ ] Elsewhere (Please specify)

**Bug Description:**

Import of any CKL with any check that has a numerical value for FINDING_DETAILS fails with the error 'vuln.FINDING_DETAILS.trim is not a function'.

- Testing shows that this applies to any FINDING_DETAILS with a value which is a positive or negative numerical value (integer or decimal) without any other text.
- White-space before, after, or within the numerical value does not seem to have any effect.
- Inclusion of any character other than digits, whitespaces, decimal points, or the negative indicator (when at the beginning of the numerical value) will result in a successful import.

- Testing shows that this affects checks with a STATUS of 'NotAFinding', 'Not_Applicable', and 'Open'; however it does not appear to affect checks with a STATUS of 'Not_Reviewed'.

- [X] I have checked to see if there is already an existing issue that describes this bug.

**To Reproduce**
1. Go to either the 'Manage' node; to a specific asset under a checklist in the 'STIGs' node; or to a specific checklist under an asset in the 'Assets' nodes under a collection.
2. If under the 'Manage' node, click 'Import CKL or SCAP'; If under the STIGs or Assets nodes, click 'Checklist' > 'Import Results'
3. Drop or use the browser to select a CKL with the above conditions to the Import Results screen.

**Expected behavior**
The CKL file should be properly imported without an error.

**Actual behavior**
The import fails with the error 'vuln.FINDING_DETAILS.trim is not a function' (see attached screenshot).

**Screenshots**
![Import_Error](https://user-images.githubusercontent.com/19519101/140816555-6ffd7f6b-2e53-48a3-bd59-4f03de5063da.png)

**Environment or Configuration:**
 - Using official Docker Image from https://hub.docker.com/r/nuwcdivnpt/stig-manager (version 1.0.42)
 - Multiple browsers affected (tested Chrome and MS Edge)

**Additional context**
Sample file which will reproduce the error is attached (change extension to .ckl).  The numerical value on line 178 is what causes the issue.  It does not appear to matter which STIG is used, so a smaller one was used for testing.
[TEST-ASSET.txt](https://github.com/NUWCDIVNPT/stig-manager/files/7500094/TEST-ASSET.txt)

This error appears to be caused in the file clients/extjs/js/SM/Parsers.js by a call to the trim() function for the vuln.FINDING_DETAILS (line 182); and it appears that the COMMENTS values (line 184) in CKLs will also be affected as it parses those values the same way.

One potential method to fix the issue is to add a check for the type of the variables before using the trim() function as described below:

To address the FINDING_DETAILS issue, replace line 182 with the following code:
`resultComment: (typeof vuln.FINDING_DETAILS == 'string') ? vuln.FINDING_DETAILS.trim() : vuln.FINDING_DETAILS ?? null,`

To address the COMMENTS issue, replace line 184 with the following code:
`actionComment: (typeof vuln.COMMENTS == 'string') ? vuln.COMMENTS.trim() : vuln.COMMENTS ?? null,`

**Comment by cd-rite** [comment]
Wow, great catch, @DavidAmond and thanks for the detailed bug report!
Your fix is also working for me, so we should be able to turn this around pretty quick.  I will @ you in this thread when we release.

Alternatively, since you have a working fix, feel free to fork the project and submit a Pull Request with your fix! You can also add yourself to the Contributors document if you agree to the [DCO and contribution guidelines.](https://github.com/NUWCDIVNPT/stig-manager/blob/main/CONTRIBUTING.md)

Thanks again!

**Comment by csmig** [comment]
Much appreciated @DavidAmond .

I think setting the value of the [fast-xml-parser](https://github.com/NaturalIntelligence/fast-xml-parser) option `parseNodeValue` to `false` on [this line](https://github.com/NUWCDIVNPT/stig-manager/blob/5b3f72cfd78859c98f5550759105baecec52772f/clients/extjs/js/SM/Parsers.js#L53) is the way to go.

I thought this option controlled whether to parse text nodes at all. After looking at the source, I see instead it controls whether the parser attempts to parse text nodes as numbers or boolean. When `false`, all text nodes are parsed as strings, which is what we need/expect here.

**Comment by csmig** [comment]
And it turns out setting the fast-xml-parser option `trimValues` to `true` probably means we can dispense with those two `trim()` calls altogether and let the parser handle that.

**Comment by DavidAmond** [comment]
@cd-rite @csmig Thanks for the quick response, and all the great work on this project!

I am for the easiest solution possible, so if the update to the fast-xml-parser options will address the issue in the future, I'm all for that.  Since we have a work around in our environment, whenever it is implemented in the core release is good for us.  Just wanted to make sure to pass the information back to help anyone else running into the issue.

Thanks again.

**Comment by csmig** [comment]
Great! We'll have a fix for this in the next release.
