### ISSUE TITLE
Item Hyperlinks

### ISSUE THREAD

**Issue by sagansapien** [NUWCDIVNPT/stig-manager#52]
In tables that contain multiple assets, a hyperlink from the asset name " Asset-A" which takes you to the specific STIG checklist shown in that context would be nice. These links could open a new tab.

For instance:

Reports > Findings > Individual Findings table > <Asset Name> --- this could link to the STIG details page for that particular asset / stig checklist. 

Similarly with Reports > Status > <Asset Name> --- this could link to the STIG details page for that particular asset / stig checklist. 

This kind of linking would be useful in drilling down to specific problems so corrective action can be taken.

Thanks!

**Comment by cd-rite** [comment]
Agreed, on this one too.... 
 I've added this to our Enhancement backlog for consideration. As I mentioned in your other issue, we are currently in a bit of a bug-fixing cycle, but will address User Stories like this soon. Thanks for contributing.

**Comment by sagansapien** [comment]
Thanks!

**Comment by cd-rite** [comment]
Closing this Issue. Same feature is being tracked in #191 now.
