### ISSUE TITLE
FEATURE REQUEST: Right-Click Option to Open New Tab to Review Collections, etc., Side-by-Side On Demand

### ISSUE THREAD

**Issue by jeremywood-ai** [NUWCDIVNPT/stig-manager#529]
**Is your feature request related to a problem? Please describe.**
Right-click ability to open another tab for a current review areas, such as Collections --> Collection 2 --> Findings.
This would allow for previous Collection to be open and then add the next Collection in a second tab.

This is an on-demand function and not an accidental behavior that is currently found in STIGMAN 1.10.

**Accidental behavior discovered:**
On occasion, I can force a second tab if:
1. Open a `Collection`
2. Open `Reports`
3. Click on `Findings` --> A tab opens

Attempt to open a second tab:
4. Click on `Collections` --> Current Collection --> `Manage`
5. Then, Click on down arrow for another `Collection`
6. Click `Manage`

_A second tab is open._

[1] **Alternative Technique Discovered:**
1. Click on `Collections` --> <Collection 1> --> `Manage`
2. Click on second `Collections` --> <Collection 2> --> `Manage` 

A second tab opens.

**Describe the solution you'd like**

As an `operator`:
I want to `right-click` on a `Collection` --> `Reports` --> `Findings` :
To open a new tab manage more than one collection at a time.

**Describe alternatives you've considered**

An alternative exists as described in behavior in [Alternative Technique Discovered][1]

**Additional context**

**Comment by cd-rite** [comment]
Hi @jeremywood-ai 
We implement a VS Code-style tabbing system. For non-management interfaces, tabs open transiently, indicated by an italicized label. This means the next transient tab you open (reports, review interfaces) will take the place of that tab. Tabs will become persistent if you double-click on their label, indicated by their label changing to non-italicized text.  Then the next tab you open of that type will then get its own new transient tab. 

Hope that helps!

**Comment by csmig** [comment]
[The documentation](https://stig-manager.readthedocs.io/en/latest/user-guide/user-guide.html#content-panel) calls these "transient" tabs by the name "Preview tabs".

> When a Review Workspace tab is opened with a single-click on a Navigation Tree Node, it opens in a Preview tab in the Content Panel. This tab will be replaced by the next tab that is opened. To make this tab permanent, double-click on the tab title at the top of the Content Panel, or edit the workspace’s contents. Opening a tab with a double-click on the Navigation Tree node will open the tab in a permanent state.

We will review whether the documentation is clear enough on this point and synchronize any conflicting terminology.
