### ISSUE TITLE
BUG: Docker example only works for localhost

### ISSUE THREAD

**Issue by dbussert** [NUWCDIVNPT/stig-manager#54]
**Describe the bug**

I found a bug in the:
- [ ] API
- [ ] UI
- [ X ] Elsewhere (Please specify) Custom keycloak image

Assessing the docker-compose up result will never load on http://serverip:54000/ because the call to keycloak is hard coded to be 

http://localhost:8080/auth/realms/stigman/protocol/openid-connect/3p-cookies/step1.html

This can be seen in the `keycloak.json` which contains

```
{
  "realm": "stigman",
  "auth-server-url": "http://localhost:8080/auth",
  "ssl-required": "external",
  "resource": "stig-manager",
  "public-client": true,
  "confidential-port": 0
}
```
- [ X ] I have checked to see if there is already an existing issue that describes this bug.

**To Reproduce**
1. Copy Dockerfile to a server
2. Run `docker-compose up`
3. Attempt to access server at `http://serverip:54000`

**Expected behavior**

Expected behavior is the STIG manager UI loads to the interface. The example docker will be more useful if it does not require installing on a local machine only. A good fix would be additional docker ENV configurations that one that override the `auth-server-url` in the image at runtime. 

**Actual behavior**

![image](https://user-images.githubusercontent.com/2479487/101585074-0cb13e80-39ad-11eb-89fc-f61d9830ec07.png)

**Comment by csmig** [comment]
Having trouble understanding your steps. There is no dependency on any service being on localhost. Tthe Dockerfile is used to build a container image (docker build) and not by the docker-compose.yml example we provide on [Docker Hub](https://hub.docker.com/r/nuwcdivnpt/stig-manager)

The API accepts [environment variables](https://nuwcdivnpt.github.io/stig-manager/#/Environment_Variables) to configure the location of Keycloak. The keycloak.json file is regenerated at API runtime from keycloak.json.template and the envvars.

**Please provide the docker-compose.yml file you are using, along with a description of your environment.**
Thanks.

**Comment by dbussert** [comment]
I should've been more clear, the issue with with the Dockerfile, it's with the `docker-compose.yml` described on this page https://hub.docker.com/r/nuwcdivnpt/stig-manager

After reviewing the env variables I found the issue is `STIGMAN_CLIENT_KEYCLOAK_AUTH`, which defaults to `localhost:8080`. It would be user friendly to add that explicitly to the `docker-compose.yml` and in the `STEPS` documentation, reference changing that value to the user-facing url that docker-compose is being run on

**Comment by csmig** [comment]
Ah, I understand now. Your browser is not on the same host running the orchestration. You've set the correct envvar and we'll add comments about this in the compose file to help others in with this use case.
Thanks!
