### ISSUE TITLE
BUG:  Description not updated on post (Create Collection method of API)

### ISSUE THREAD

**Issue by dante2365** [NUWCDIVNPT/stig-manager#547]
**Bug Location**

I found a bug in the:
- [x ] API
- [ ] UI
- [ ] Elsewhere (Please specify)

**Bug Description: The post method of creating a collection doesn't update the description field of the collection.  On the put method it works as designed.**

- the api is the /collections endpoint
- 
![image](https://user-images.githubusercontent.com/53409387/148601592-4d471ed0-0a3f-4e4f-9cc3-f33529aa222a.png)

- [ x] I have checked to see if there is already an existing issue that describes this bug.

**To Reproduce**

**Expected behavior**
Expect the description field to not be null

**Actual behavior**
Description field is null

**Screenshots**

**Environment or Configuration:**
 - Container or Orchestration info
 - Browser
 - Other info

**Additional context**

**Comment by csmig** [comment]
The query [here](https://github.com/NUWCDIVNPT/stig-manager/blob/main/api/source/service/mysql/CollectionService.js#L557-L562) was not updated to include the "description" field when it was introduced.
