### ISSUE TITLE
FEATURE REQUEST: Add configurable labels for assets to enable filtering on Collection > STIG, Collection > Asset views, and others.

### ISSUE THREAD

**Issue by callison32** [NUWCDIVNPT/stig-manager#561]
**Is your feature request related to a problem? Please describe.**

The problem at Crane is we have multiple Operations Teams that perform STIG work on specific assets that they are responsible for (VMware Team, Infra Team, App Server Team, Linux team, etc).  But we would still like all admins to see all the various Teams STIGs to reference as needed.  The Restricted permissions do not work for us.  We have not found a good way to filter on the assets/stig views other than using the restricted permissions.

**Describe the solution you'd like**

We want to utilize the existing Metadata functionality to create an entries for each Team.  Such as Team = App Server Team, etc.  Then we can add that metadata entry for each asset.  

The solution we are looking for and requesting is the ability for us to search/filter for a specific metadata property, under the Collection > STIG and Collection > Asset views.  Being able to filter for only assets/stigs related to Team = App Server Team, etc  would facilitate internal team reviews and ISSO/ISSM discussions with the various teams during Quarterly STIG review meetings.  

**Describe alternatives you've considered**

Using restricted permissions to allow see the team specific assets/stigs.  But we have STIGs on various teams that we need our "junior" admins to be able to reference and see how other teams addressed similar stigs.

**Additional context**

**Comment by cd-rite** [comment]
Hi @callison32, thanks for the suggestion! 
It sounds like you are trying to make a distinction between "visibility" (ie. the overall access you grant to users) vs. "responsibility" (ie. assets/STIGs a user is actually responsible for evaluating).  
Using metadata on assets would be a great way to accomplish that, if you could filter on them!

We will have to discuss internally about priority and level of effort for this.  From your description, I think you want a way to filter what you are seeing in the Navtree on the left, which we have not done in the app before. 
My first thought is that an easier place to implement this would be in the Collection Review interface, where we already have a flexible and extensible filtering option (though it does not yet include metadata). 
Would this satisfy your use case?
We will also assess the feasibility of a filter-able Navtree.

In the meantime, you could consider these workarounds, though neither of them may be optimal for your use case:

- Adopt a naming convention for Assets that includes a string you want to filter on (something like: **[asset-name]-[team-name]**).  Then use the Collection Review workspace and filter on Asset Name for the Team Name you are looking for. 

- If you find it feasible, you could try creating more numerous and smaller Collections, perhaps targeted to the groups you mentioned, and give those team members full access.  Then when "complete" (or whenever you want to)  you can "Transfer" the assets from one Collection to another, central one if so desired.  The transfer would require a user with "owner" or "manage" grants in both original and destination Collections.   
  - This would have the added benefit of providing Reports that span just the Assets in that Collection, which could be handy if you are reviewing by Team, etc.  




Thanks for using STIGMan!

**Comment by csmig** [comment]
I like the spirit of this request. Perhaps we could implement #object #tags for this requirement?

"Tagging" an Asset with one or more strings is conceptually similar to metadata -- tags are essentially keys without values. But users are probably more familiar with the tagging pattern since it is widely implemented in modern tools. To filter the Asset lists, users would specify the tags instead of needing to specify both the desired metadata keys AND their values.

If we go this route, we could add tagging support to Collections and Assets at first, then maybe to individual Reviews.

**Comment by callison32** [comment]
Tags would be great and accomplish what we need.  And yes, the Collection
Review and Assets area would be a good place to start.

 

Thank you,

 

Brandon Callison

Alternate Information System Security Manager (A-ISSM)

Naval Surface Warfare Center, Crane Division, (NSWC Crane)

Code 104, Bldg. 3173

300 Highway 361

Crane, IN  47522-5001

Ph:  812.854.3693

DSN: 482-3693

Email:   ***@***.***> ***@***.*** 

 

 

 

From: csmig ***@***.***> 
Sent: Friday, January 21, 2022 7:10 AM
To: NUWCDIVNPT/stig-manager ***@***.***>
Cc: ***@***.***; Mention ***@***.***>
Subject: [URL Verdict: Neutral][Non-DoD Source] Re:
[NUWCDIVNPT/stig-manager] FEATURE REQUEST: Metadata filter on the Collection
> STIG and and Collection > Asset views (Issue #561)

 

I like the spirit of this request. Perhaps we could implement #object #tags
for this requirement?

"Tagging" an Asset with one or more strings is conceptually similar to
metadata -- tags are essentially keys without values. But users are probably
more familiar with the tagging pattern since it is widely implemented in
modern tools. To filter the Asset lists, users would specify the tags
instead of needing to specify both the desired metadata keys AND their
values.

If we go this route, we could add tagging support to Collections and Assets
at first, then maybe to individual Reviews.

-
Reply to this email directly, view it on GitHub
<https://usg01.safelinks.protection.office365.us/?url=https%3A%2F%2Fgithub.c
om%2FNUWCDIVNPT%2Fstig-manager%2Fissues%2F561%23issuecomment-1018450610&data
=04%7C01%7Cbrandon.b.callison.civ%40us.navy.mil%7Cedc41e7b0c064cb4fe9f08d9dc
d7140e%7Ce3333e00c8774b87b6ad45e942de1750%7C0%7C0%7C637783638589307900%7CUnk
nown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXV
CI6Mn0%3D%7C3000&sdata=lFK4VdZkWuq0LYlmV%2BCPlDZUfdSgVO4RiD%2BNZeEXm%2F4%3D&
reserved=0> , or unsubscribe
<https://usg01.safelinks.protection.office365.us/?url=https%3A%2F%2Fgithub.c
om%2Fnotifications%2Funsubscribe-auth%2FAR2E4KTL53BXWV2OADWPMATUXFELBANCNFSM
5MN47ZGA&data=04%7C01%7Cbrandon.b.callison.civ%40us.navy.mil%7Cedc41e7b0c064
cb4fe9f08d9dcd7140e%7Ce3333e00c8774b87b6ad45e942de1750%7C0%7C0%7C63778363858
9307900%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6
Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=bmU07wTB2svZRLBQHza%2B3100K32eM5YZ1drBjM
VMBAA%3D&reserved=0> .
Triage notifications on the go with GitHub Mobile for iOS
<https://usg01.safelinks.protection.office365.us/?url=https%3A%2F%2Fapps.app
le.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8
%26pt%3D524675&data=04%7C01%7Cbrandon.b.callison.civ%40us.navy.mil%7Cedc41e7
b0c064cb4fe9f08d9dcd7140e%7Ce3333e00c8774b87b6ad45e942de1750%7C0%7C0%7C63778
3638589307900%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLC
JBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2F7s8qJb7p%2FdYmJH%2FEl81s%2FvgTG
hjqT6zPjSaTPVCWao%3D&reserved=0>  or Android. 
You are receiving this because you were mentioned.
<https://github.com/notifications/beacon/AR2E4KUNXZRPKB3JJ7G7EOTUXFELBA5CNFS
M5MN47ZGKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOHS2FFMQ
.gif> Message ID: ***@***.***
***@***.***> >

**Comment by callison32** [comment]
Yes, the collection review area would be a good place to add the extra
filtering and/or tags.  That would be a much better alternative than
renaming assets.

 

We've considered multiple collections per Team, but don't like the idea of
looking through 3-4 collection reviews of Windows OS stigs when we're trying
to aggregate everything.  A single collection with filters/tags would be
much more feasible.

 

I guess the naming convention name could work.  We use Eval-STIG and it
completes the hostname fields of the CKLs then we feed it to STIGMAN.  Would
this cause any issues then next time we pass a new CKL to STIGMAN after we
appended the Team name?

 

Tags/filters is still our preference because that would allow us to use them
for additional purposes.  Such as tag RDT&E systems that are currently
documented in a "short term test" so we could exclude them from a STIG
review until the system goes back to production, etc.

 

Thank you,

 

Brandon Callison

Alternate Information System Security Manager (A-ISSM)

Naval Surface Warfare Center, Crane Division, (NSWC Crane)

Code 104, Bldg. 3173

300 Highway 361

Crane, IN  47522-5001

Ph:  812.854.3693

DSN: 482-3693

Email:   ***@***.***> ***@***.*** 

 

 

 

 

From: cd-rite ***@***.***> 
Sent: Thursday, January 20, 2022 11:49 PM
To: NUWCDIVNPT/stig-manager ***@***.***>
Cc: ***@***.***; Mention ***@***.***>
Subject: [URL Verdict: Neutral][Non-DoD Source] Re:
[NUWCDIVNPT/stig-manager] FEATURE REQUEST: Metadata filter on the Collection
> STIG and and Collection > Asset views (Issue #561)

 

Hi @callison32
<https://usg01.safelinks.protection.office365.us/?url=https%3A%2F%2Fgithub.c
om%2Fcallison32&data=04%7C01%7Cbrandon.b.callison.civ%40us.navy.mil%7Ce3c629
bedfe543aff78208d9dc997d59%7Ce3333e00c8774b87b6ad45e942de1750%7C0%7C0%7C6377
83374079056804%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiL
CJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=gbNPTyq%2Be57yR70hd9DnrFGUQ168LIo
OTniMJyIqdTk%3D&reserved=0> , thanks for the suggestion!
It sounds like you are trying to make a distinction between "visibility"
(ie. the overall access you grant to users) vs. "responsibility" (ie.
assets/STIGs a user is actually responsible for evaluating).
Using metadata on assets would be a great way to accomplish that, if you
could filter on them!

We will have to discuss internally about priority and level of effort for
this. From your description, I think you want a way to filter what you are
seeing in the Navtree on the left, which we have not done in the app before.
My first thought is that an easier place to implement this would be in the
Collection Review interface, where we already have a flexible and extensible
filtering option (though it does not yet include metadata).
Would this satisfy your use case?
We will also assess the feasibility of a filter-able Navtree.

In the meantime, you could consider these workarounds, though neither of
them may be optimal for your use case:

*       Adopt a naming convention for Assets that includes a string you want
to filter on (something like: [asset-name]-[team-name]). Then use the
Collection Review workspace and filter on Asset Name for the Team Name you
are looking for.

*       If you find it feasible, you could try creating more numerous and
smaller Collections, perhaps targeted to the groups you mentioned, and give
those team members full access. Then when "complete" (or whenever you want
to) you can "Transfer" the assets from one Collection to another, central
one if so desired. The transfer would require a user with "owner" or
"manage" grants in both original and destination Collections.

*	This would have the added benefit of providing Reports that span
just the Assets in that Collection, which could be handy if you are
reviewing by Team, etc.

Thanks for using STIGMan!

-
Reply to this email directly, view it on GitHub
<https://usg01.safelinks.protection.office365.us/?url=https%3A%2F%2Fgithub.c
om%2FNUWCDIVNPT%2Fstig-manager%2Fissues%2F561%23issuecomment-1018177773&data
=04%7C01%7Cbrandon.b.callison.civ%40us.navy.mil%7Ce3c629bedfe543aff78208d9dc
997d59%7Ce3333e00c8774b87b6ad45e942de1750%7C0%7C0%7C637783374079056804%7CUnk
nown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXV
CI6Mn0%3D%7C3000&sdata=D6gP4pFZpcgFfmphCEM8Sxc%2By4Jk0MyG2p57tApJ82A%3D&rese
rved=0> , or unsubscribe
<https://usg01.safelinks.protection.office365.us/?url=https%3A%2F%2Fgithub.c
om%2Fnotifications%2Funsubscribe-auth%2FAR2E4KTLPEX3QQNSN7DTXLLUXDQVPANCNFSM
5MN47ZGA&data=04%7C01%7Cbrandon.b.callison.civ%40us.navy.mil%7Ce3c629bedfe54
3aff78208d9dc997d59%7Ce3333e00c8774b87b6ad45e942de1750%7C0%7C0%7C63778337407
9056804%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6
Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=AMS3S5h1LHb08dJbuDRpqdVxYvgVn2Q6b7mTGipH
BaM%3D&reserved=0> .
Triage notifications on the go with GitHub Mobile for iOS
<https://usg01.safelinks.protection.office365.us/?url=https%3A%2F%2Fapps.app
le.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8
%26pt%3D524675&data=04%7C01%7Cbrandon.b.callison.civ%40us.navy.mil%7Ce3c629b
edfe543aff78208d9dc997d59%7Ce3333e00c8774b87b6ad45e942de1750%7C0%7C0%7C63778
3374079056804%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLC
JBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=E4%2BAToxMKtXim%2B%2BzXrqnunDjc0XC
LkloEkRKRJYfCH8%3D&reserved=0>  or Android. 
You are receiving this because you were mentioned.
<https://github.com/notifications/beacon/AR2E4KR6UP2MEPX2ZRSIDH3UXDQVPA5CNFS
M5MN47ZGKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOHSYCR3I
.gif> Message ID: ***@***.***
***@***.***> >

**Comment by cd-rite** [comment]
Great, thanks @callison32 !
We think tags will be a lot more user friendly for accomplishing the goal of quickly limiting/filtering the Assets (and/or Collections and Reviews) you are presented with.  

Our initial thoughts (subject to change!) on implementation would require a Collection Owner/Manager to set up a list of the Tags they'd like to use in their Collection.  Then items from that list of Tags could be assigned to the Assets or other components in a Collection.  Filtering the various views could then use a selectable pull-down of the available Tags to actually alter the view of Assets presented.

**Comment by callison32** [comment]
Great. I think letting the collection owner/manager to setup a list of tags
is a very good idea.

 

I know I listed a couple examples already, but we actually thought of a
third use case for tags from another STIGMAN implementation discussion
today.  We have an consolidated our standalone A&A packages down to the
department level, so tagging the assets down to the division level (w/
separate ISSO's and admins involved in that sustainment) is another very
useful case for Crane. Each division is only focused on their assets and
anything else added to the mix will just add confusion.  A&A analysts would
like to see everything as a whole and do not want multiple collections.

 

Thanks again for the help and quick response.  If I can provide any
additional details or anything to assist then I'd be more than happy to.

 

Thank you,

 

Brandon Callison

Alternate Information System Security Manager (A-ISSM)

Naval Surface Warfare Center, Crane Division, (NSWC Crane)

Code 104, Bldg. 3173

300 Highway 361

Crane, IN  47522-5001

Ph:  812.854.3693

DSN: 482-3693

Email:   ***@***.***> ***@***.*** 

 

 

 

From: cd-rite ***@***.***> 
Sent: Wednesday, January 26, 2022 1:47 PM
To: NUWCDIVNPT/stig-manager ***@***.***>
Cc: ***@***.***; Mention ***@***.***>
Subject: [URL Verdict: Neutral][Non-DoD Source] Re:
[NUWCDIVNPT/stig-manager] FEATURE REQUEST: Metadata filter on the Collection
> STIG and and Collection > Asset views (Issue #561)

 

Great, thanks @callison32
<https://usg01.safelinks.protection.office365.us/?url=https%3A%2F%2Fgithub.c
om%2Fcallison32&data=04%7C01%7Cbrandon.b.callison.civ%40us.navy.mil%7Ca70ddb
1f7d24460996bf08d9e0fc6de7%7Ce3333e00c8774b87b6ad45e942de1750%7C0%7C0%7C6377
88197057599708%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiL
CJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=r63RcM%2F6u%2FWhpstdbrYZczHNtzJLT
KvF9iSql2ZyeNU%3D&reserved=0>  !
We think tags will be a lot more user friendly for accomplishing the goal of
quickly limiting/filtering the Assets (and/or Collections and Reviews) you
are presented with.

Our initial thoughts (subject to change!) on implementation would require a
Collection Owner/Manager to set up a list of the Tags they'd like to use in
their Collection. Then items from that list of Tags could be assigned to the
Assets or other components in a Collection. Filtering the various views
could then use a selectable pull-down of the available Tags to actually
alter the view of Assets presented.

-
Reply to this email directly, view it on GitHub
<https://usg01.safelinks.protection.office365.us/?url=https%3A%2F%2Fgithub.c
om%2FNUWCDIVNPT%2Fstig-manager%2Fissues%2F561%23issuecomment-1022489386&data
=04%7C01%7Cbrandon.b.callison.civ%40us.navy.mil%7Ca70ddb1f7d24460996bf08d9e0
fc6de7%7Ce3333e00c8774b87b6ad45e942de1750%7C0%7C0%7C637788197057599708%7CUnk
nown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXV
CI6Mn0%3D%7C3000&sdata=q92IaQ69qx4Tii3tgWIyNJO3muA%2F8q59ur3zMbvnWQI%3D&rese
rved=0> , or unsubscribe
<https://usg01.safelinks.protection.office365.us/?url=https%3A%2F%2Fgithub.c
om%2Fnotifications%2Funsubscribe-auth%2FAR2E4KWPQNI4OOVJCCFFSJTUYA6UBANCNFSM
5MN47ZGA&data=04%7C01%7Cbrandon.b.callison.civ%40us.navy.mil%7Ca70ddb1f7d244
60996bf08d9e0fc6de7%7Ce3333e00c8774b87b6ad45e942de1750%7C0%7C0%7C63778819705
7599708%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6
Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=FMK%2FmjDMk4WMgK6jpZefZ25wumssVERmuww9CW
Vx6Jo%3D&reserved=0> .
Triage notifications on the go with GitHub Mobile for iOS
<https://usg01.safelinks.protection.office365.us/?url=https%3A%2F%2Fapps.app
le.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8
%26pt%3D524675&data=04%7C01%7Cbrandon.b.callison.civ%40us.navy.mil%7Ca70ddb1
f7d24460996bf08d9e0fc6de7%7Ce3333e00c8774b87b6ad45e942de1750%7C0%7C0%7C63778
8197057599708%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLC
JBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2FmiaM1bo4yeL2uQ2l6FInqowMd6VG%2B
fhNTQYhBc%2F5vQ%3D&reserved=0>  or Android. 
You are receiving this because you were mentioned.
<https://github.com/notifications/beacon/AR2E4KV2ZX5OVQD6YCTGGZDUYA6UBA5CNFS
M5MN47ZGKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOHTY7GKQ
.gif> Message ID: ***@***.***
***@***.***> >

**Comment by cd-rite** [comment]
Initial work for this feature being tracked with Issue #566

**Comment by dtester1** [comment]
I am looking forward to seeing how this gets implemented.  We have very similar concerns where I work about how assets in assets view are all going to be in one bucket so to speak (possibly network gear, workstations, severs, etc.)

**Comment by cd-rite** [comment]
Editing the title of this Issue to better reflect the feature(s) we will be implementing to enable this ability.

**Comment by cd-rite** [comment]
Closing this issue as work for this feature is now being tracked with issue #566 .
Issue #602 will track additional enhancements in this area.
