### ISSUE TITLE
Add OAS definitions and API endpoints to enable labeling of Assets in a Collection, preview UI feature.

### ISSUE THREAD

**Issue by cd-rite** [NUWCDIVNPT/stig-manager#566]
Need endpoints that will enable the ability to "Tag" or "Label" Assets in a Collection. 
The available Labels should be managed at the Collection level. 

- [x] OAS endpoints added 
- [x] API endpoints implemented 
- [x] UI Preview feature (NavTree filtering)
- [x] API tests completed 
- [x] #603

Include initial "Preview" use of this feature in UI (NavTree filtering), before broader UI implementation.

Issue spawned from User Story #561

**Comment by cd-rite** [comment]
Initial definition and considerations:

Tags that will be available will be created at Collection level, by owners/managers, made available for attachment to Assets. (possibly Reviews and Collections themselves at later date). Limit of 128 possible tags per Collection. 
If label/tag is removed, it is removed from all objects it is attached to. 
If label/tag is updated, objects it is attached to should keep the tag. 
Available Tags attached to Assets, limited 16.
Tag length:  32 chars?

Other Considerations:

Will tags transfer with Assets when they move Collections?

**Comment by tylerforajter** [comment]
Just wanted to check in on this topic, Is there a status on this implementation?  This will be very helpful when complete.   There are several business cases that we want to use this with.

**Comment by csmig** [comment]
Closed by merging #605
