### ISSUE TITLE
Manage Collection -> CKL/SCAP import -> job display

### ISSUE THREAD

**Issue by csmig** [NUWCDIVNPT/stig-manager#57]
The final wizard panel should
- output better descriptions of the job progress (the definition of 'better' can be discussed in this issue)
- a summary line about the batch (statistics, etc.) would be helpful
- allow saving the output to a file, which is consistent with other widgets.

**Comment by csmig** [comment]
See final comment from #55 regarding performance degradation as display output grows

**Comment by csmig** [comment]
@sagansapien observed 1500 imports in 3 minutes, but it took 10 minutes to do 3442. That should have taken around 7 minutes. So there's probably still a performance degradation as the output display grows. Should take this into consideration when working this.

**Comment by cd-rite** [comment]
This issue is likely OBE, as Manage Collection interface now provides live statistics in response to imports.
Imported messages have been made friendlier.
Save function provided by Copy&Paste for now.
