### ISSUE TITLE
FEATURE REQUEST: Mass Edit Functionality

### ISSUE THREAD

**Issue by mayszs** [NUWCDIVNPT/stig-manager#587]
**Is your feature request related to a problem? Please describe.**
One of our collections contains 249 network switches of which 247 of them have identical configurations. In the event a change is made to correct an open vulnerability it takes more time to update the 247 applicable records in STIGMan than it takes the network team to deploy the change. 
Another example would be the Virtual Machine STIG.  All of our VMs are deployed from templates so the Virtual Machine confirmation, as it applies to STIG Checks, are identical.  Once again if a change is made to the configuration all 200+ assets have to be modified individually.
The same issue occurs when GPOs are deployed.

**Describe the solution you'd like**
The ability to apply changes to the same vulnerability/rule ID across multiple assets.  Ideally the changes would be made from Collection Review under the STIG.

**Describe alternatives you've considered**
Manual updates are incredibly time consuming for bulk changes so the only real alternative would be to waiting until the next scheduled run of EvaluateSTIG for updates but unfortunately many of the STIGs applicable to large numbers of assets (switches) are not supported by EvaluateSTIG.

**Additional context**

**Comment by mayszs** [comment]
Sounds great!
Thank you

**Comment by cd-rite** [comment]
This feature request is now being tracked with issue #615 and its subtasks.

@mayszs
