### ISSUE TITLE
BUG: VOIP STIG exports with incorrect schema

### ISSUE THREAD

**Issue by 18gold** [NUWCDIVNPT/stig-manager#589]
**Bug Location**

I found a bug in the:
- [X] API
- [ ] UI
- [ ] Elsewhere (Please specify)

**Bug Description:**
Exporting VOIP (V3 R14) STIGs create an invalid schema error when attempting to load into STIG Viewer. When loading back into STIG Manager, the STIG imports but contains no data. 

- [X] I have checked to see if there is already an existing issue that describes this bug.

**To Reproduce**
1. Assign VOIP STIG (V3 R14) to asset
2. Complete (fully or partially) STIG items
3. Export VOIP STIG 
4. Load into either STIG Viewer or back into STIG Manager (another collection)
5. Review STIG. It is blank (STIG Manager) or produces invalid schema error (STIG Viewer)

**Expected behavior**
Exported STIG should contain valid schema.

**Actual behavior**
Invalid schema error or blank STIG.

**Environment or Configuration:**
 - STIG Manager 1.2
 - Chrome/Firefox

**Additional context**
Indicates the export is somehow changing the schema for this particular STIG.

**Comment by cd-rite** [comment]
Hi @18gold 
Thanks for the bug report, I am able to reproduce this issue.
I will update when we have more info.
