### ISSUE TITLE
BUG: CKL Review/Comments fields

### ISSUE THREAD

**Issue by sagansapien** [NUWCDIVNPT/stig-manager#59]
Not really sure if this is a bug or feature request.

Collections > Assets > _asset name_ > _STIG name_ > "Review on _asset name_"  > "Evaluation" section.

![image](https://user-images.githubusercontent.com/53829030/101936597-ba3f7000-3bae-11eb-8630-0cd9ba5690ec.png)

The "Comment" box is pulling text from the CKL "Finding Details" node. As user, this is misleading. Shouldn't this text box be labeled "Finding Details"?

The actual "Comments" node from the CKL is not visible in this area of STIG Manager. For open findings, I need to verify the CKL comments field is populated with a mitigation statement. I would prefer to be able to collapse the "Review Resources" box and have both the CKL Comments and Finding Details boxes available for review/edit.

Thanks!

**Comment by csmig** [comment]
Some background: When we started this in 2012 our intention was not to emulate CKL terminology, which we thought Navy was applying in a non-intuitive manner. Why should a result of "NotAFinding" have a Finding Detail (it is not a finding, right?). So we settled on the "Comment" label for both the Evaluation and Recommendation sections. Over time, NUWCDIVNPT reduced use of STIG Viewer significantly and exported CKLs (from STIG Manager itself) only when an upstream process (NAVSEA reviewers) required them. So the terminology mismatch became much less meaningful.

But our intention is to nevertheless conform to the Navy convention around CKLs that requires <FINDING_DETAILS> for all results and <COMMENTS> for only Open results. So after importing a CKL, you should see your <COMMENTS> text in the Recommendation section, labeled as "Comment", for all reviews where the Evaluation result is "Open" (fail)

Is this not happening for some/all of your files?

**Comment by csmig** [comment]
In addition, STIG Manager requires information that is not stratightforward to map to a CKL. Specifically, the Recommended Action is a discrete value separate from the Comment. We have an (undocumented!) way of handling this, but would appreciate further discussion.

Our approach is to see if the COMMENTS text starts with `Mitigate:` or `Remediate:` or `Exception:` and use that as the drop down value. Again, this is not documented right now, so we should get that addressed

**Comment by cd-rite** [comment]
Hi @sagansapien 
We should have a new release with the fix available for the "Comments" text not being imported on Monday. 
However, regarding your issue, you mentioned that the "Comments" text box was not visible, and it is not in your screenshot. Were you referring to the fact that that text did not import, and you just did not include that area, or do you actually not see the "Comment" box in the "Recommendation" section below the Evaluation, seen here:
![image](https://user-images.githubusercontent.com/61710958/102034372-dd734680-3d8b-11eb-90a1-108d71082f16.png)

**Comment by sagansapien** [comment]
I can see the Recommendation/Comment area in stigman, I just cropped it out in the screenshot. We'll download and test the change, thanks!

**Comment by sagansapien** [comment]
Comments are importing now.

I did notice that it didn't like the " & " character from one of our comments fields, It should have read "RDT&E" but is reading "RDT&amp;E"

**Comment by csmig** [comment]
Created new issue to address @sagansapien's lastr comment. Closing this one.
