### ISSUE TITLE
Possible Bug: Missing Fields in CKL Export Compared to STIG Viewer

### ISSUE THREAD

**Issue by jeremygifford** [NUWCDIVNPT/stig-manager#601]
While comparing STIG Viewer generated CKL (with Microsoft DotNet Framework 4.0 STIG v2r1) to the resulting file after importing/exporting it from STIG-Manager version 1.2.3 , noticed the following content missing or discrepancies:

Under <CHECKLIST><STIGS><iSTIG><STIG_INFO>
-Missing classification <SID_DATA> for <SID_NAME>classification</SID_NAME>
-Originating file name of the STIG changed from the *Manual-xccdf.xml to stig-manager-oss for <SID_NAME>filename</SID_NAME>
-UUID changed for <SID_NAME>uuid</uuid>
-missing <TARGET_COMMENT>
-<TARGET_KEY> value changed

Missing <CHECKLIST><STIGS><iSTIG><VULN><STIG_DATA><VULN_ATTRIBUTES> for:
-Check_Content_Ref
-Weight
-Class
-TargetKey
-STIG_UUID
-LEGACY_ID

Are the fields imported/exported with the database hard coded rather than dynamically parsed from the CKL and STIG definition file (*Manual-xccdf.xml)? Seems like a good code improvement to prevent being out of sync with the latest STIG releases.

**Comment by cd-rite** [comment]
Thanks, @jeremygifford we will take a look at this.
We do not intend for our output to be completely identical to STIG Viewer output, but we don't want to lose any information. 

One of the issues is that to our knowledge, DISA does not publish their .ckl definition, so there isn't really a "correct" .ckl file. 
We strive to stay compatible with STIG Viewer, but that makes it difficult.  Only certain fields seem to be required (indicated by failure to import into STIG Viewer), and obviously the ones you listed do not seem to be "required" by STIG Viewer.

We will investigate and update this Issue.

**Comment by jeremygifford** [comment]
@cd-rite Isn't the schema file (U_Checklist_Schema_V2.xsd) basically the CKL definition? All the fields mentioned are present in it.

**Comment by jason-henry-keyport** [comment]
@jeremygifford I see where you are on this.  Some of the fields can be very useful, like Legacy_ID, for helping to figure out where things should get mapped to in various updated STIGs.  I haven't looked deeply at any of the additional fields, but is there a specific thing you are looking to solve with the additional fields that we currently do not bring across?  I intend to look thru each field to see what the mapping is and if something I know is required is missing, but I am all ears if you have any specifics.  We can discuss in another forum if you so desire, just let me know.

**Comment by cd-rite** [comment]
Hi @jeremygifford -
It definitely sounds like that would be the definition, but I've never seen that before.... It's not in the DISA document library, the Tools downloads, or in the STIG Viewer .zip.  Where did you get that? Thanks!

**Comment by jeremygifford** [comment]
In case it sounds like I'm overly critical, I do like what STIG-Manager is trying to do and think its' current form is a good foundation. I appreciate the tool and the work the team is putting into it, STIG-Manager definitely provides value for the Navy and really the DoD as a whole.

@cd-rite Yeah, I was struggling to find the schema for a while before I started to reverse engineer and poke around STIG Viewer. I wish DISA would do a better job around releasing STIG Viewer technical documentation.

Your comment on not being a .ckl manager is bit concerning to me though. Granted this is my view-point /opinion, but I would be careful with that mentality (in the same vain as it being "your data"). STIGs and their content are owned by the DoD and the RMF process we are supporting is certainly governed by it, and the powers that be have been pretty permissive to the home-brew type efforts by the sub-echelons on implementing their own tools/processes to implement it. If we start to "rock the boat" in a negative why by promoting tools that generate evidence we submit that which is inconsistent with the DoD provided tools (and basically defacto standards), we're likely to loose a lot of that leeway. CKL files are the official way of recording our implementation/compliance with STIGs and are core to the effort. All that above is basically my long-winded way of saying that absolute-fidelity to CKLs should absolutely be one of your team's core goals/tenants.

I like your mention of "Multiple .ckl files that describe the same Asset could conflict with each other, or with the results of an SCAP scan." That's actually a big area where I'm starting to see STIG-Manager could improve in. I'm still finding the ins and outs of STIG-Manager so there may be things I'm unaware of; but, if the tool is to be used throughout a package/system/enclave's lifecycle, it'll need to do a good job handling continuous cycles of importing, merging, and exporting CKLs (and the other sources). GIT-style version control and collection-level "snap-shots in time" will probably be important and a big area of provided value to an organization. 

@jason-henry-keyport The information missing from those fields, besides Legacy_ID, isn't really a problem in itself from an end user standpoint. 
Context story: I'm just starting to poke around STIG-Manager and familiarize myself with it for NSWC PHD's first trial run on one of our packages. The Classification and Legacy IDs missing (from the top-right section under the STIG title / version info when viewing in STIG Viewer) jumped out at me right away from the STIG-Manager export and got me curious at looking deeper into the differences. I tried to verify the integrity of the CKLs by comparing the file hashes pre and post STIG-Manager ingestion (with no changes via the UI between). The different hashes got me comparing the two at the XML content level which is where I started noticing the differences. The different XML comments at top and use of white-space in the file text itself were benign enough, but the missing XML fields started to concern me.

**Comment by cd-rite** [comment]
Hi @jeremygifford @jason-henry-keyport 
Thanks for the input!  Just to be clear, when I mentioned fidelity to the .ckl file, I meant we will not produce a .ckl file that is *exactly* like a .ckl file that was imported, ie. the hashes will not be the same, etc.   STIG Manager's goal is to present data that is the sum of imported .ckl files, SCAP results, and manual user input such that it reflects the "current" evaluation status for an asset as accurately as possible.  We also need to reflect that our tool produced the .ckl, so the hashes will never match.  However, we will continue to make every effort to ensure we do not *lose* any data that was imported, and the actual Reviews will be the same. 

We absolutely intend to produce valid .ckl files on export for as long as that file format is in use, and that .xsd will help greatly in this effort!!  Thanks again for mentioning it. Just knowing it actually existed helped me find it. 

We also keep a history of the state of every Review, so while this is not a feature currently in the UI, the API is capable of providing data that would let you determine what the state of your Reviews were at a given date/time.  We think this will be very useful in the future for providing the "snapshot" views you mentioned.

**Comment by jeremygifford** [comment]
@jason-henry-keyport @cd-rite I'm excited for the future additions and just want to say thanks again for the effort and product you (and team) are providing.
