### ISSUE TITLE
FEATURE REQUEST: Add Select All Button to the UI for Assets in Collection Review and Management workspaces. 

### ISSUE THREAD

**Issue by jeremygifford** [NUWCDIVNPT/stig-manager#611]
**Is your feature request related to a problem? Please describe.**
To select all assets (for use-cases like exporting all STIGs for all assets) from the collection>Manage>Assets table currently requires highlighting using multi-select with ctrl + shift and scrolling to the bottom of the table.

**Describe the solution you'd like**
A "select all" button would be more user friendly.

**Describe alternatives you've considered**
Adding selection check boxes to the list instead of just highlights may be another related user-friendly-ness addition to consider.

**Comment by cd-rite** [comment]
Hi @jeremygifford thanks for the suggestion! 
We will take this under advisement for our next pass over that UI. 
For now, it may be easier to export via the STIG panel from the Collection Management screen. From there, you can highlight all the STIGs (presumably fewer things to click on than Assets), hit "Export CKLS..." and the interface that pops up will have every asset selected by default.
