### ISSUE TITLE
FEATURE REQUEST: Add UI for Creating Custom Reports

### ISSUE THREAD

**Issue by jeremygifford** [NUWCDIVNPT/stig-manager#613]
**Is your feature request related to a problem? Please describe.**
Pre-built reports lack coverage of many things reviewers (Validators exc) might want to quickly check and export to csv. eMASSter's "compliance" tab is a good reference for some of the things.

Examples:

Are there any security overrides?
Are there any checks with missing Finding Details?
Are there any checks with missing Comments?
Are the checks done on the latest available STIG version?
What are the cumulative totals for each type of thing? (the UI table displays some of this like Cat 1, Cat 2, Cat 3, but doesn't appear to export to csv)

**Describe the solution you'd like**
UI page for creating reports and the ability to save/import/export custom report definitions. Selection lists derived from the available database fields.

**Comment by cd-rite** [comment]
HI @jeremygifford 
We envision STIGManager working as part of a toolchain that would still include eMASSter, so we do not want to duplicate any of their features or introduce any redundancies. 

As for being able to check for missing fields, this is something you can enforce with the "Review Fields" requirements in the Collection Management - Settings tab.  If you require Findings Details or Comments for your reviews, or Comments for Opens only, etc,  you can set that requirement and users will not be able to "Submit" their Reviews until they meet them.  Then you can be sure that all the "Submitted" review statistics you see ensure that the Reviews meet the requirements you specify. 

The statistics you see displayed are always calculated against the latest reference STIG you have imported into the system from the Application Management interface.  It is up to the Application Manager to ensure that they have their desired STIGs in the system. In some cases, this is not always the latest release from DISA. 

The Status report .csv export does not currently export the totals, only the raw data grid numbers.  We are intending to enhance this report at some point, and we will make sure to include that. 

While we intend to enhance the reports we currently make available, creating a report builder is a bit out of our scope at the moment.  However, we fully document our API and expect that other reporting frameworks should be able to connect to it and build reports based on their local users requirements.  

I think I've addressed everything you've brought up in this issue, so I will be closing this, but if you have something in a more specific area please feel free to create another!
Thanks!
