### ISSUE TITLE
FEATURE REQUEST: STIG Version/Release Library Comparison

### ISSUE THREAD

**Issue by jeremygifford** [NUWCDIVNPT/stig-manager#614]
**Describe the solution you'd like**
A page for showing comparisons between two (or maybe even more) selectable STIG versions. This would be helpful for quickly viewing changes like rule additions/removals/updates and to include changes to the Check, Fix, and Discussion fields.

**Comment by cd-rite** [comment]
Hi @jeremygifford I agree that this would be a useful tool, but out of scope for STIGMan and our current efforts.  
However, we also welcome third parties to create clients for our API that could satisfy these requests! 
Thanks!
