### ISSUE TITLE
POST /stigs -> UTF-8 encoding not being handled properly.

### ISSUE THREAD

**Issue by cd-rite** [NUWCDIVNPT/stig-manager#62]
**Describe the bug**

I found a bug in the:
- [ ] API
- [ ] UI
- [x] Elsewhere (Please specify)

Please include a clear and concise description of what the bug is.

Some STIG text displayed in STIGMan shows invalid/wrong characters due to improper handling of unicode in STIG source files.

- [ x] I have checked to see if there is already an existing issue that describes this bug.

**To Reproduce**
View rule SV-77809r3_rule in the WIN10 STIG. Manual check has line that reads:
"System type" is not "64-bit operating systemâ¦", this is a finding."

**Comment by csmig** [comment]
The check for the example rule (SV-77809r3_rule) is C-64053r3_chk
