### ISSUE TITLE
Change UI alerts/error messages to be more transparent

### ISSUE THREAD

**Issue by cd-rite** [NUWCDIVNPT/stig-manager#620]
Currently they generally create fairly generic pop-up alert boxes. 

Several types of errors should be addressed:
Client error messages
API error responses
Keycloak Auth error responses

related: #443

**Comment by csmig** [comment]
I think some API changes could be helpful here, too. Currently, error responses from the API do not include a stack trace (although they are present in the API log stream). I think we did this based on our experience with closed source projects, where we do not want to disclose info about our internal code structure.

For this OSS project, our source is public so there's little upside to omitting the stack traces and lots of downsides. When users post screenshots of errors they receive in the UI, having the stack trace visible would be a great help!
