### ISSUE TITLE
FEATURE REQUEST: Import Staging/Review Screen

### ISSUE THREAD

**Issue by jeremygifford** [NUWCDIVNPT/stig-manager#622]
**Is your feature request related to a problem? Please describe.**
The import feature provides no information on what checklist/finding details/comments will be affected by the import before the process completes. Also, no easy way to roll-back changes in mass.

**Describe the solution you'd like**
UI screen that compares the import files against the collection repository, with the ability to abort and, ideally, select files/checklists to ignore. Possible example being two columns, left side showing the current state of the repository and the right side showing the repository after importing with new Assets/STIGs highlighted one color and Assets/STIGs being changed another color. To extend the idea even further, another view could pop up when selecting a specific Asset/STIG comparing the rules (Status/Finding Details/ Comments) between the existing and import checklist.

**Comment by cd-rite** [comment]
Hi @jeremygifford Thanks for all the suggestions! These could all be useful tools, but we do not have the resources to implement them at this time.  Please fork the project if you or anyone you know are able to contribute features such as these to our reference UI, or create another client that can accomplish some of these tasks! 

A few features we do have that could accomplish some of what you are looking for:

- The .ckl import interface from the Manage Collection workspace is designed to handle somewhat large numbers of .ckl files, and that would become quite challenging to display and go through in the manner you describe. However, we do provide a summary of each file that is imported in that interface, displaying the Asset, the STIG, the total number of checks with NF, NR, O, and NA results, the originating filename, and the file modified date. We feel this is a pretty good compromise between displaying all info from the imported files, and none. 
- The .ckl import interface from the specific Asset-STIG workspace does display the actual checks that will be imported, and provides the option to only update reviews that have changed.  Right now we are putting more efforts into being able to support continuous and automated workflows where picking and choosing parts of a .ckl file to import will be less useful. 
- We don't have a roll-back option for imports, as this would be somewhat antithetical to the concept of the Review History we maintain, but you can drag and drop from entries in the history tab to your current reviews in the Asset-STIG workspace.  

That said, we will keep your suggestions in mind if/when we get more resources, or hear of another group doing STIGMan-related development that wants to implement these kinds of features. 

Hope that helps! Thanks for using STIG Manager OSS!

**Comment by cd-rite** [comment]
@jeremygifford Please note, I am closing this issue as we have no resources to address it at this time, but I am tracking these types of submissions in the Back Burner project for reference if needed.
