### ISSUE TITLE
Large CKL Files Produce Errors During Upload

### ISSUE THREAD

**Issue by lp177344** [NUWCDIVNPT/stig-manager#625]
Greetings, 

I have deployed STIG Manger v1.2.3 to a Windows Server 2019 OS using the "source code" deployment option (e.g. nodejs, mysql, java, keycloak). We've successfully uploaded over 100k checklists into STIG Manager (our administrators love it), but edge cases have arisen where large .ckl files fail to upload successfully. 

The largest .ckl files we are producing are between 9-11MB, generated by Active Directory Domain, Splunk Enterprise, and an assortment of other STIG checklists. I have been asked to see if we can adjust the upload size limit to accommodate these large checklist files. 

When adding a large .ckl file I get the following error, "request entity too large." 
![image](https://user-images.githubusercontent.com/81931396/159397337-476f3842-8216-4d50-af66-6c10d1755429.png)

I have reviewed existing items listed under "issues" and saw a reference to an environment variable titled "STIGMAN_API_MAX_JSON_BODY" which has a default value of "5242880."

I figured this might be my issue and added environment variable "STIGMAN_API_MAX_JSON_BODY" and modified the value to "15728640" followed by a reboot of the server. 

![image](https://user-images.githubusercontent.com/81931396/159397452-661b115d-c4f1-4bf2-96b5-cf4dc6160d2f.png)

Unfortunately, when uploading a large checklist file another error occurred, "cannot add new command when connection is in a closed state": 

![image](https://user-images.githubusercontent.com/81931396/159397918-71ec57b2-c998-405a-acc1-fc44059247f8.png)

I have attempted to remediate this error by googling it and attempting several "fixes" however, nothing I've attempted has been successful. I wanted to reach out and see if you could be of assistance, please. 

Thank you!

**Comment by csmig** [comment]
Hi there! Thanks for the report, let's try to figure this out. I think you solved the original error ("request entity too large"), so the second error ("Can't add new command...) is my focus.

That error message is probably from the MySQL library used in the API and it usually indicates the connection to MySQL has been dropped for some reason. To verify that, I need to see the stack trace (which we really should report in the web app!). If you aren't doing so already, please redirect the API's log output to a file. You could then use the `jq` script below to filter the log records to only show the errors:
```
jq -s 'map(select (.level == 1))' <path_to_your_logfile>
```
So my first request is to please respond with the full log record that corresponds with the error reported in the web app. Thanks!

In addition, and I don't want to go too far with the following idea, but a common reason the MySQL connection goes away in the middle of a session is if a query exceeds the size of the MySQL server variable `max_allowed_packet`. The default for that variable is 64M, which should be sufficient, but it would be worth checking it out in your environment and changing if necessary.

Finally, we sometimes encounter users who report an issue but are then unwilling/unable to share the source CKL/SCAP files that cause the error. This does complicate troubleshooting. So with that in mind, I am going to stand up a new repo that will contain code to generate "sanitized" or redacted versions of CKL, XCCDF, and JSON data that will retain the overall structure and size of the original, but remove the real host data and turn the commentary into gibberish. I'll write back here when that is available for you to use.

Thanks again for reporting this and for your help in figuring out a cause.

**Comment by lp177344** [comment]
Greetings!

Success! following your suggestions, I logged into MYSQL Server 8.0 and executed command "SHOW VARIABLES LIKE 'max_allowed_packet'; which was set to 4m. Additionally, I executed the command "SET GLOBAL max_allowed_packet=15m;" (this didn't appear to work as I continued to experience the errors previously noted).

Additional reading suggested this value would be reset when the operating system rebooted (unconfirmed). The article suggested I locate and modify the "my.ini" configuration file located here: c:\programdata\mysql\mysql server 8.0" as this would ensure the value was persistent. 

![file_location](https://user-images.githubusercontent.com/81931396/159605625-671abd8d-b648-4be1-bdb9-bec74468f5e5.JPG)

Within the "my.ini" configuration file was a setting "max_allowed_packet=4m." I modified this value to "max_allowed_packet=15m" and rebooted the operating system. 

This modification, as well as the addition of the environment variable "STIGMAN_API_MAX_JSON_BODY" noted previously, appeared to be the two changes required to enable larger checklist files to be uploaded. I was able to successfully upload checklist files up to 11MB (largest .ckl file we have at the moment). 

![max_allowed_packet_setting](https://user-images.githubusercontent.com/81931396/159605954-305970e9-e982-453d-8d37-b6b1352eb193.JPG)

I thank your all of your assistance! 

References:
https://stackoverflow.com/questions/8062496/how-to-change-max-allowed-packet-size

**Comment by csmig** [comment]
Awesome! Its helpful to know the default for `max_allowed_packet` is 4M for at least some of the MySQL distributions. I thought it was much higher.

Also, we should consider raising our default value for `STIGMAN_API_MAX_JSON_BODY`, it seems many users are importing more data at a shot than we originally estimated. I've opened #628 to get this idea in our pipeline.
