### ISSUE TITLE
HTML entities in CKL are not decoded

### ISSUE THREAD

**Issue by csmig** [NUWCDIVNPT/stig-manager#63]
Comments are importing now.

I did notice that it didn't like the " & " character from one of our comments fields, It should have read "RDT&E" but is reading "RDT&amp;E"

EDIT: GitHub is formatting the second one automatically. screenshot attached:

![image](https://user-images.githubusercontent.com/53829030/102121562-2837a180-3e12-11eb-9496-5b9557b612a3.png)

_Originally posted by @sagansapien in https://github.com/NUWCDIVNPT/stig-manager/issues/59#issuecomment-744632572_

**Comment by csmig** [comment]
Issue is present in both API and client code that use fast-xml-parser
API: reviewsFromCkl() in `api/source/utils/parsers.js`
Client: reviewsFromCkl() in `clients/extjs/js/SM/Parsers.js`

In object `fastParseOptions`, assign to properties `attrValueProcessor` and `tagValueProcessor`. Use `he.decode` to decode any HTML entities.

**Comment by sagansapien** [comment]
Nice, thanks!
