### ISSUE TITLE
FEATURE REQUEST: Change in Informational Rules

### ISSUE THREAD

**Issue by ZBoyerNSWCCD** [NUWCDIVNPT/stig-manager#635]
**Is your feature request related to a problem? Please describe.**
To start, Evaluate-STIG applies Not Reviewed to many checks that it either cannot evaluate, cannot fully evaluate, fails to evaluate, and does not have an answer file provided that changes this status. Due to this, informationals can continuously occur for particular checks so each time Eval-STIG is re-ran and checklists are then uploaded these checks will change from Open, NF, or NA to NR again in STIGMAN. Due to this constant change in status the only sustainable option for ISSOs and Admins is to ignore informationals when looking into standard STIG review completions (not speaking to detailed reaccreditation review, etc. which may force a more detailed review). However, currently it appears that Informationals can occur even if a workstation has never had it's status submitted so ignoring these informationals could currently be ignoring potential findings. 

**Describe the solution you'd like**
While I'm not sure of another/better option than to import Not Reviewed items as Informationals the first time, I STRONGLY suggest that checks that have been marked as Open and submitted should not be able to change to Informational status and should instead only change via Admin status change or if has been later evaluated as Not a Finding via a future checklist import. 

**Describe alternatives you've considered**
Only alternative is to always require status changes for Informational checks but several Warfare Centers run (or will run) Evaluate-STIG weekly which could cause these Not Reviewed and subsequent Informational findings to return every week again and again.

**Additional context**
Example for context: Evaluate-STIG evaluates Windows 10 V-220712 (Administrator Rights on System) as a Not Reviewed but provides a list of accounts with the associated permissions. We require our admins to review these on each system to ensure they have to perform at least one check on each system to track completion and due to difficulty of providing an answer file for this check. For the large majority of systems this check was admin-marked as NF or imported as NF due to the checklist already being edited. Once it was run again and imported it now shows Informational in STIGMAN and can either be changed to NF and saved again or ignored. However, if it was imported as Open or marked as Open when it is reran and reimported it will be placed to Informational again and could likely be ignored (or even inadvertently marked as NF by an admin who is in a hurry) even if it was submitted as an Open and should have been resolved previously.

**Comment by cd-rite** [comment]
Hi @ZBoyerNSWCCD 
It sounds like your issue could be resolved with an option you could select to exclude rules that are "Not Reviewed" when importing Reviews from .ckl files. 
That way if Eval STIG, or whatever other tool might have created the .ckl, does not have an answer for a particular rule it won't wipe the one that's currently present.

We have thought about adding this option in the past. Would that resolve your issue?

**Comment by ZBoyerNSWCCD** [comment]
@cd-rite I probably haven't given it enough thought to be incredibly confident, but I believe that could work as long as the Not Reviewed will be imported if, at a minimum, the machine is new (checklists are not being overwritten upon import, new workstation ID being generated) to ensure that some kind of status is imported for each check at least once (which will be very useful for those who perform all reviews using STIGMAN and newly imaged workstation ckls are being uploaded from STIGWatcher without having their checklists modified), or alternatively the exclude only prevents overwriting a true status (O, NA, NF) upon import.

**Comment by cd-rite** [comment]
@ZBoyerNSWCCD Our intent is to give you the option to pick which behavior you want when you import.  We've learned enough that there is no one-size fits all behavior we could implement!

**Comment by csmig** [comment]
Closed by #659
