### ISSUE TITLE
FEATURE REQUEST: Expandable Collection Review Fields

### ISSUE THREAD

**Issue by ZBoyerNSWCCD** [NUWCDIVNPT/stig-manager#636]
**Is your feature request related to a problem? Please describe.**
Currently Rule ID is cutoff and cannot expand to view full rule, and only two digits are viewable (with ... after) for the status fields which prevents the ability to view an accurate number of checklists (if over 99) with that status without creating a full report.

**Describe the solution you'd like**
I am requesting that the "Collection Review" fields (Rule ID, O, NF, NA, submitted, etc.) under the "STIGs" utility be expandable to allow for the review of the full details provided in each field.

**Comment by cd-rite** [comment]
Hi @ZBoyerNSWCCD 
I think we already support what you are asking for. 
If you hover over the border between the Rule Id and Rule Title column headers, your cursor should switch and allow you to shift the border between these fields.  
You can also shrink the NavTree down on the left with the button indicated. This should free up more space for you to see the data fields.  
You can also adjust the size of the panels by hovering over the green borders between them, and dragging when your cursor changes. 
We are trying to convey a lot of information with that screen, so things are slightly tight in places.  That said, I am unable to recreate your problem even when I lower my resolution to 720p.  What resolution monitor are you using? Are you using your browser at full screen? 

![image](https://user-images.githubusercontent.com/61710958/161670417-5a08a798-796a-4184-827b-59e8151a927b.png)

**Comment by ZBoyerNSWCCD** [comment]
@cd-rite My apologies, it would appear I was incorrect with the Rule ID and I can, in fact, expand that section (along with CAT & Rule Title) whether or not the leftmost window is expanded or not. However, the status fields (O, NF, NA, NA, Submitted, etc.) do not seem to be expandable for me (v1.2.6) and for my NF findings all I can view is "12.." so it could be 126 or 126,689 and I couldn't tell

**Comment by cd-rite** [comment]
@ZBoyerNSWCCD Thanks for clarifying! We will investigate and try to get those fields displaying reliably with these larger counts.
