### ISSUE TITLE
FEATURE REQUEST: Add approval option to asset view

### ISSUE THREAD

**Issue by jrharden23** [NUWCDIVNPT/stig-manager#645]
**Is your feature request related to a problem? Please describe.**
- No it is not.

**Describe the solution you'd like**
- When searching for an asset within a collection, I'd like to be able to approve a check that has been submitted for review when browsing it's applicable ckls. Currently, a user can submit a finding for review from this screen, but the approver cannot approve submitted requests.

**Describe alternatives you've considered**
- Currently, you must go into collection review to have the option of approving submitted requests.

**Additional context**

Current options available within asset view (no accept/approve option):
![Only Options within asset view](https://user-images.githubusercontent.com/104012036/164020116-ed266e47-aa30-40da-87a9-fda2ecb4459d.JPG)

Current options available within collection view (has all available options):
![Options available within collection view](https://user-images.githubusercontent.com/104012036/164020159-66b2abd8-1622-46a5-8176-97f8fc89c7e9.JPG)

**Comment by csmig** [comment]
Thanks, this is a reasonable request that I will look at implementing.
