### ISSUE TITLE
Status Report update

### ISSUE THREAD

**Issue by ZBoyerNSWCCD** [NUWCDIVNPT/stig-manager#647]
(Version 1.2.7)

Currently, viewing the Status report shows machine's Tag data which is (more like could be) helpful for tracking overall or by-code (area) completion, submission, pending checks, etc. but report takes a VERY long time to load (when memory errors don't occur and force a page refresh) when changing views (STIG to Asset, minimizing all, etc.) and more critically cannot be filtered/sorted by tag (or any other field) which greatly limits its usefulness. 

**Describe the solution you'd like**
While revisiting this feature and refining it with additional functionality would be nice in the future I believe (what should be) an quick and easy-to-implement temporary solution is the use of the CSV export feature to export the data where it can be filtered, sorted, and edited however Excel will allow for and seems to be formatted quite well for **but** export does not seem to currently include the Label field which provides a much more definable characteristic to limit workstations to for review.

**Comment by csmig** [comment]
When saying Tag Field you mean Labels Field, correct? If so we should change the title.

I agree we need to revisit the Status report soon. Some of the issues:

- doesn't scale to large Collections (STIGs x Assets) because it renders too many grid rows in the DOM
- CSV export doesn't include the grouped-by column, so not useful as is
- Doesn't provide any filtering features (e.g. #602)

**Comment by ZBoyerNSWCCD** [comment]
Yes, I did mean Labels and the title has been edited. 

And thank you for your continued work. As I stated I believe a good temporary solution if you don't have time for a full code revisit prior to the next release would be to ensure all the pertinent report data is included in the CSV export as just about any desired manipulation should be achievable using Excel.

**Comment by cd-rite** [comment]
Hi @ZBoyerNSWCCD Thanks for the Issue, we will revisit the Status report soon.
For now, we do have a workaround to get the data you want into the .csv export.
It's not visible, but there are some Column display controls available if you click the far right of any column header:
![Screenshot 2022-04-26 135701](https://user-images.githubusercontent.com/61710958/165363896-1a6a4fda-0942-4ea2-ac91-906abcdf15eb.png)
Click in the space indicated, and DE-select "Show in Groups":
<img width="204" alt="Screenshot 2022-04-26 140137" src="https://user-images.githubusercontent.com/61710958/165363999-d7d14398-81b6-4d26-8690-a683919bc1cf.png">
Then expand the Columns menu item, and make sure Asset, Labels, and Checklist are all checked (plus any other columns you want in the export):
<img width="272" alt="image" src="https://user-images.githubusercontent.com/61710958/165364268-3b5fbf3d-84cd-4935-9d29-3c5ba49e76d3.png">

Now, when you export the .csv, you should have the fields you need to manipulate the data as needed.

**Comment by cd-rite** [comment]
This issue now being tracked in Issues #699 and #700 
Above workaround still applies for now.
