### ISSUE TITLE
BUG: Align sample appdata, and sample keycloak

### ISSUE THREAD

**Issue by cd-rite** [NUWCDIVNPT/stig-manager#65]
**Describe the bug**

I found a bug in the:
- [ ] API
- [ ] UI
- [x] Elsewhere (Please specify)

Please include a clear and concise description of what the bug is.
If it is in the API, please specify endpoint.
Including your actual request may be helpful as well.

- [ ] I have checked to see if there is already an existing issue that describes this bug.

**To Reproduce**

**Expected behavior**

**Actual behavior**
What behavior did you actually experience?

**Screenshots**

**Environment or Configuration:**
 - Container or Orchestration info
 - Browser
 - Other info

**Additional context**

**Comment by csmig** [comment]
I'm have renamed this issue to not reference [test/api/form-data-files/appdata.json.](https://github.com/NUWCDIVNPT/stig-manager/blob/main/test/api/form-data-files/appdata.json) That's the "test" appdata, correct? I think that should remain as is.

I will update the "sample" appdata at [data/appdata](https://github.com/NUWCDIVNPT/stig-manager/tree/main/data/appdata) so it is aligned with the current API release. In addition, I'll provide a README that explains which STIGs must be installed for the sample data to be accepted.
