### ISSUE TITLE
New Feature - Collection - Manage - Assets - Add Automatic Remove Option

### ISSUE THREAD

**Issue by lp177344** [NUWCDIVNPT/stig-manager#655]
Morning, 

Issue: Currently managing several thousand Windows 10 Assets within the single Collection. "Stale or Unused" assets are removed from the network fairly often as they are "lifecycled" out. However, the DISA STIG checklists associated with these assets continue to remain within STIG Manager until they are manually removed by an administrator. These "stale" assets tend to skew the compliance picture when reviewed by various stakeholders. 

I tend to use the Collections "Newest" Column as a guide to determine which assets are "stale" records and manually remove them as needed at set intervals.   

Request: Would it be possible to create an option to remove "stale" assets within STIG manager at set intervals (e.g. 30, 60, 90, 100, etc, days)?

Little pseudo code to exemplify my request: If(Asset.NewestField >= "60"){Remove Asset from Collection}  

If this seems excessive that is ok, you can close this request. Our organization still loves using STIG Manager as is! 

Thank you!

**Comment by cd-rite** [comment]
HI @lp177344 
Thanks for the suggestion, but this option isn't really in scope for this project. 
However! If you have access to developer resources yourself, this would be a great candidate for a lightweight command-line client that could connect to our API and do these kinds of maintenance tasks for you.  We **highly** encourage people to create their own clients to hit the STIGMan API!

Our Watcher client could act as a model for you: [https://github.com/NUWCDIVNPT/stigman-watcher](https://github.com/NUWCDIVNPT/stigman-watcher)

You could rip out most of Watcher's options and guts, and alter it to make it very single-purpose. You could even store your preference in the free-form Collection metadata via the UI, from the Collection Manage workspace, and have the client request and obey that preference. 
Heck, if you are feeling really ambitious, you could write a client that also connects to your Asset Management system and adds/removes Assets from STIGMan to keep them in sync. 

Please let us know if you wind up creating something like that, and I'd encourage you to share it on GitHub too! 
Glad you are enjoying the tool!
