### ISSUE TITLE
Allow RuleId to match on just the SV-number portion, excluding revision string.

### ISSUE THREAD

**Issue by tylerforajter** [NUWCDIVNPT/stig-manager#658]
**Is your feature request related to a problem? Please describe.**
When a new STIG version is loaded into STIGMAN.  It appears that it does not handle rule revision mismatches.  For example:

In the v6r2 Firefox STIG, vulnerability ID V-251557 has the rule ID SV-251557r820752.

In the v6r1 Firefox STIG, vulnerability ID V-251557 has the rule ID SV-251557r807143.

Since the rule ID changed, STIGMAN is leaving the results blank and is not importing the results from the previous version of the STIG. 

I believe this to be incorrect, or maybe possible should be a feature request.

DISA STIG viewer has this set as an option:
![image](https://user-images.githubusercontent.com/100237457/168108576-b614f2bf-9be6-49a8-a068-dc1164dd5abe.png)

**Describe the solution you'd like**
The Allow Rule Revision Mismatches option that STIGVIEWER has should be integrated into STIGMAN.

**Describe alternatives you've considered**
Possible solution is to allow time for automated ckl evaluation tools to run at the new version.  However, this hinders us during certain documentation efforts. 

**Additional context**

**Comment by cd-rite** [comment]
Hi @tylerforajter 
Thanks for the suggestion, this is a slightly tricky area. In our experience, we have found that in most cases, a change to the revision portion of the RuleID indicates that there was some actual content change to that rule. If that change was to the check or fix for a Rule, for example, then older Reviews shouldn't really be valid any more, because they would have used an out-of-date standard.

The fact that STIG Viewer supports that option does carry at least _some_ weight, so we will follow up.
However, we will likely not get to this soon, even if approved, so your workaround of running new Evaluations with the latest 
 tools would be the best approach for now.

**Comment by csmig** [comment]
Perhaps I'm barking up the wrong tree here, but the Review tabs allow for selecting the revision of a STIG that is displayed. 

![image](https://user-images.githubusercontent.com/33138761/168166653-68722cb5-cec4-40e7-bea0-ed3e0f597318.png)

Does that help with your documentation effort as you await results against the latest STIG? 

I think the STIG Viewer approach violates good data management practices. This problem domain has been riddled with that kind of thing for too long! If a RuleID has changed, presumably it is a different Rule than earlier versions. If DISA is gratuitously changing these primary key identifiers while not changing the underlying object, then I would think this is an issue for them?

**Comment by tylerforajter** [comment]
@csmig 

Going back a version can be helpful in some cases, but I'm mostly speaking about when new STIGs are released and we want to upgrade to the newest version.  When some documentation efforts are underway, it is essential that we have the latest version of the STIG to provide, thus we need a method that can rapidly do the upgrade that doesn't cause a lot of manual labor. 

The only difference between the two items that I listed above is a set of brackets that they placed in the fix text:

In the v6r2 Firefox STIG, vulnerability ID V-251557 has the rule ID SV-251557r820752
In the v6r1 Firefox STIG, vulnerability ID V-251557 has the rule ID SV-251557r807143.

v6r1:
Linux "policies.json" file:
Add the following in the policies section:
"InstallAddonsPermission": false

v6r2:
Linux "policies.json" file:
Add the following in the policies section:
"InstallAddonsPermission": {
      "Default": false
}

In this case here, I have no issue simply importing the results from r1 into r2.  I do agree that there could be an issue if the check is significantly changed, however I think we should have the ability to make this change.

I would argue:
1. Since DISA provides this functionality in a tool that is accessible to the entire DOD, this method is most likely widely used and accepted.
2. Even if the check did change significantly, it should still be the judgement of the local security personnel to determine if a previous answer is still valid.

I just think that we should have the option to do the matching like stig viewer does.  It certainly does not have to be the default configuration.

Happy to discuss this more.  Also happy to provide my email if you'd like to setup a virtual meeting for further discussions.

**Comment by csmig** [comment]
@tylerforajter 

TLDR; Good helpful points, thanks. The team certainly wants to accelerate the assessment process, so let's flesh out your request a bit more. Are you on Navy Flankspeed by any chance?

But if you will indulge me a bit ... What would be very helpful to the project is a deeper discussion about these RuleIDs. I work this problem domain as a developer/data guy, I'm not "in the trenches" doing assessments as you are. So I might talk funny, please bear with me. 

**Do you, or anyone reading, have a formal specification from DISA about the semantics of the Rule identifiers (or anything else XCCDF, really)?** A specification is more reliable than deducing a data model from the behavior of a closed-source tool like STIG Viewer.

STIG Viewer's feature is suggesting the left portion of the RuleID (splitting on `r`) is sufficient to be a primary key that identifies a compliance requirement. Does this mean the right half can be treated as a minor/patch indicator that has no impact on the compliance requirement? This is not how STIG Manager is currently modeled (it follows the XCCDF specification and assumes the entire RuleID is meaningful).

Confounding this for me is the XCCDF specification makes the `<version>` element available to `<Rule>` for the exact purpose of storing the rule version. I would not expect the identifier itself to carry versioning info, but here we are. Looks like the STIG sources (XCCDF from DISA) set the values of `<Rule><version>` to strings that map to some other data. An example is:

```
<Rule id="SV-238196r653763_rule" weight="10.0" severity="medium">
  <version>UBTU-20-010000</version>
  <title>The Ubuntu operating system must provision temporary user accounts with an expiration time of 72 hours or less.</title>
  ...
</Rule>
```

Perhaps someone in the community could help me understand the utility of that `UBTU-20...` value?

Although I'm pretty sure we could devise a solution to your request using the current STIG Manager data model, in either the frontend or the API itself, the solution will seem like a workaround to an incorrect data model (to me at least). I'm not dogmatically opposed to that in the interest of accelerating the process, but I'd rather re-define the data model's keys if necessary than develop a tool that requires workarounds to be helpful.

**Comment by tylerforajter** [comment]
@csmig 
Yes I am indeed on FS.  

If you search my last name, you should be able to find me.

**Comment by cd-rite** [comment]
Hi @tylerforajter 
Please join our STIG Manager OSS Team on FlankSpeed! We are trying to build a self-supporting community of users to share, improve, and help others learn how to use the tool.
Our Teams code is: qrym6dn

**Comment by cd-rite** [comment]
We will revisit this issue if need be.  Future efforts with automated scanning should alleviate this need quite a bit.
