### ISSUE TITLE
Support "Not Reviewed" status for reviews

### ISSUE THREAD

**Issue by sagansapien** [NUWCDIVNPT/stig-manager#67]
Greetings,

CKLs that have Not Reviewed items but do have Finding Details written for those items do not import the Finding Details to stigman.

Expected to import this item as NR but show any Finding Details or Comments from the CKL for that item.

Thanks!

**Comment by cd-rite** [comment]
Hmmmm interesting case... STIGMan does not have an explicit "Not Reviewed" state, as it is implied by the lack of a review for a rule. As a consequence, we do not import anything from rules in CKLs that have the "not reviewed" status, but this could change...

You basically have notes you want to keep/import about a rule, but haven't made a decision as to the actual evaluation yet?

**Comment by sagansapien** [comment]
Basically, yes. With Evaluate-STIG, it's possible to have a check save as NR but it includes finding details. Would be helpful to have that data in stigman so it can be reviewed right there.

Thanks

**Comment by cd-rite** [comment]
Hmmm...for now, I will mark this as a Feature Request, as by deisgn STIGMan does not support the concept of a "Not Reviewed" Review.   However, I can see why this behavior might be wanted, and there is a "notchecked" state in the XCCDF standard, so we may implement it to more fully support the standard. 
Thanks!

**Comment by csmig** [comment]
@sagansapien Your scenario describes what the XCCDF spec would call an `informational` result, which cannot be expressed unambiguously in CKL. Evaluate-STIG is not willing to assign an actual compliance category (`pass`, `fail`, `notapplicable`) to the test result, although it gathered some useful information.

I've open PR #307 which is intended to, among other things, address this issue.
