### ISSUE TITLE
Collection Review -> Export/Copy Results 

### ISSUE THREAD

**Issue by sagansapien** [NUWCDIVNPT/stig-manager#68]
I'm reviewing open findings for a bunch of systems using the Collection Review node. So, I have X number of systems with the same finding. Imagine I have a script that I can use to remediate this finding but I need to get a list of the hostnames or IPs.

In the "Reviews of <STIG Rule ID_rule>" pane, it would be super if I could sort/filter by status, then have some ability to copy a the column of asset names. Or, a function to export this view to CSV where I could filter, sort, select-down all relevant asset names. This would help in finding open issues and then remediating them. Or, just for reporting. I might need to send a list of systems with X Open STIG finding to the respective administrators.

Thanks!

**Comment by cd-rite** [comment]
This has been on our radar too, both additional filtering options and more exports. I believe the intent is to, at minimum, offer CSV exports of each grid in the app. Should be possible to support applying the active filters to the export. 
Thanks!
