### ISSUE TITLE
Add new mappings for Firefox SCAP benchmark IDs to STIG benchmark ID

### ISSUE THREAD

**Issue by cd-rite** [NUWCDIVNPT/stig-manager#689]
The latest release changed the ***SCAP*** benchmark IDs from
Mozilla_Firefox_RHEL to MOZ_Firefox_Linux 
and 
Mozilla_Firefox_Windows to MOZ_Firefox_Windows

The ***STIG*** benchmark ID has changed twice, from:
Mozilla_Firefox or
Mozilla_Firefox_STIG
to
MOZ_Firefox_STIG

(Need to investigate a better way to handle these changes than hard coding them....)

**Comment by dtester1** [comment]
This isn't just affecting SCAP name changes.  Recent name changes have happened with Firefox, Defender and Windows 10.  It creates brand new entries in overall STIG List (DISA Content) and thus new entries in each collection under STIGS.

**Comment by cd-rite** [comment]
Hi @dtester1 This is actually a slightly different, but related problem to the one you describe.  In this case, SCAP benchmarks were released with different STIG IDs from the Manual STIGs, and these mappings resolve that issue. 

In the cases you describe, DISA changed the actual Identifier in the manual STIG, often while continuing the existing version/release progression!!! 
This makes it impossible to resolve automatically, as they changed the one piece of information that links the new version to the old ones. Our solution will be to provide an easy, but manual way to convert all the old Asset-STIG assignments from the old STIG ID to the new ID.  
This is being tracked here, and I will move it up the priority list as you have indicated it is affecting your work: 
https://github.com/NUWCDIVNPT/stig-manager/issues/197

I would urge you to contact DISA about this issue as well, as this problem originates from their inconsistent treatment of identifiers: [https://public.cyber.mil/email-directory/](https://public.cyber.mil/email-directory/)
