### ISSUE TITLE
BUG: Import fails to display in UI and all Benchmarks are missing in SIG and SCAP Benchmarks

### ISSUE THREAD

**Issue by ibjohn** [NUWCDIVNPT/stig-manager#692]
**Bug Location**

I found a bug in the:
- [ ] API
- [X] UI
- [ ] Elsewhere (Please specify)

**Bug Description:**
A. Importing of the latest Defender Antivirus V2R4 STIG doesn't produce an entry in the UI.  Refreshing the page doesn't help.
B. No benchmarks appear in STIG and SCAP Benchmarks (old or newly imported).  Imports have no errors, but do not display.  Does the "STIG checklists" tab filter out benchmarks and a Benchmark tab need to be added???

- [X] I have checked to see if there is already an existing issue that describes this bug.

**To Reproduce**
A. Steps to reproduce the behavior:
 1. Click on STIG and SCAP Benchmarks
 2. Go to '...'STIG CHECKLIST tab
 3. Click on '....'IMPORT STIGS, 
 4. Browse to .zip file 
 5. Select OPEN
 6. Select IMPORT.
 7. No error messages - says "Done"
 8. Log is on classified system...  Log contains stig:0, revision:0, rule:0, check:0, fix:0, revGroupMap:0, revGroupRuleMap:0, revGroupRuleCheckMap:0, revGroupRuleFixMap:0, RuleCciMap:0, currentRev:1, currentGrouRule:41, stats:41

B: 
 1.  Click on STIG and SCAP Benchmarks
 2. Go to '...'STIG CHECKLIST tab
 3. Not a single benchmark displays.

**Expected behavior**
Should display in STIG and SCAP Benchmarks list

**Actual behavior**
Does not display in STIG and SCAP Benchmarks list

**Screenshots**
Can't do - on classified system

**Environment or Configuration:**
 - Container or Orchestration info
 - Browser: Chrome 102.0.5005.115
 - Other info

**Additional context**

**Comment by cd-rite** [comment]
Hi @ibjohn 
I can't recreate this issue. Are you using the latest version of STIGMan?
And you are trying to import the DISA reference STIGS, provided here: [https://public.cyber.mil/stigs/downloads/](https://public.cyber.mil/stigs/downloads/) either individually or as the compilation library? NOT xccdf or .ckl result files?

Do see any log entries like this in the import window?
![image](https://user-images.githubusercontent.com/61710958/176244935-04da720d-bf02-45cf-ab6b-30c2ba327251.png)

**Comment by ibjohn** [comment]
Arg... we are on version 1.0.42...  I'll get it updated and I assume that
will be the fix.

Thanks,
John

John Snell, CISSP, CEH, ITIL
(907) 250-0427
