### ISSUE TITLE
BUG:Cannot "CTRL A" in Collection Review box

### ISSUE THREAD

**Issue by cnaylr** [NUWCDIVNPT/stig-manager#707]
**Bug Location**
Collection Review of a rule

I found a bug in the:

UI

**Bug Description:**

When attempting to utilize CTRL A to select all the items in the collection review box, it affects another box. Screenshot is attached of the issue. I have tried using Edge and Chrome browsers. 

- [ ] I have checked to see if there is already an existing issue that describes this bug.

![Bug stigman](https://user-images.githubusercontent.com/109249539/178843690-1ebee9bb-de35-40ae-b726-a3ced7b8f346.jpg)

**To Reproduce**

**Expected behavior**
Using CTRL A when in the collection review box should select all items within that box to allow faster processing of the batch edit feature. 

**Actual behavior**
Pressing CTRL A or trying to drag all items that I want to batch edit does not work and I am forced to CTRL click each item one by one . 

**Screenshots**
Please refer to screenshot here 
![Bug stigman](https://user-images.githubusercontent.com/109249539/178844162-50be9ede-a1a2-4a63-9cc3-08524bbfb947.jpg)

**Additional context**
![Bug stigman](https://user-images.githubusercontent.com/109249539/178844162-50be9ede-a1a2-4a63-9cc3-08524bbfb947.jpg)

**Comment by cd-rite** [comment]
Hi @cnaylr 
Thanks for the suggestion!  At the moment, we intend to leave the CTRL-A shortcut reserved for selecting text blocks.
**However!** We do support SHIFT-Click behavior, so if you select the first item in the list, and then SHIFT-Click on the bottom one, all intervening Assets will be selected (you can then de-select certain items if you need to with CTRL-Click). It's a couple more clicks than you are asking for, but much less than clicking each Asset!

We also intend to implement a "Select All" button for some views. This is currently being tracked in issue #611 . I've noted that it should apply to the Collection Review workspace you are using too, and bumped up its priority in response to your issue. 

I expect this should supply the functionality you are looking for, so I'll be closing this issue. 
Keep an eye on #611! 
Thanks for using STIG Manager OSS!

**Comment by csmig** [comment]
Have opened #710 which supports the requested behavior for focused multi-select grids.
