### ISSUE TITLE
Collection Review - Move "Reject" functionality to top toolbar

### ISSUE THREAD

**Issue by cd-rite** [NUWCDIVNPT/stig-manager#714]
All other Status functions are in the top Asset list toolbar, "reject" function is an outlier.

Move Reject function to asset toolbar (enabled after selection of one or more reviews that are submitted), creating a modal pop-up on click for providing Status Text and confirming the action.
Relabel "Reject" tab in bottom panel to "status text" and make it display-only.

**Comment by csmig** [comment]
Will not implement the last item: Relabel "Reject" tab in bottom panel to "status text" and make it display-only
