### ISSUE TITLE
Streaming API STIG Export Issue

### ISSUE THREAD

**Issue by jeremygifford** [NUWCDIVNPT/stig-manager#719]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version of STIG Manager?

- [X] I am using the latest [Release](https://github.com/NUWCDIVNPT/stig-manager/releases).
- [ ] I am NOT using the latest [Release](https://github.com/NUWCDIVNPT/stig-manager/releases). I am aware that the first thing I will be asked to do is update the application so that I have the latest bugfixes.

### Where are you experiencing the issue?

- [X] API
- [X] UI or other client
- [ ] Deployment
- [ ] Elsewhere

### Current Behavior

![streamingExportError](https://user-images.githubusercontent.com/78163427/181108237-1219664f-4ee2-4468-ac47-01588deab321.PNG)

Firstly, wow! Soooo much faster, at least 15x. Even adding 5 minutes troubleshooting and working around the bug, it was still way faster than doing it all the original way.

Okay, so the bug: it seems to error out and kill the whole process when it hits one of these (error message generated with the original export method):
Fetching checklist for RDTECE01/Windows_Server_2019_STIG: Error: missing 'Content-Disposition'

Out of the 3100 CKLs there were 3 showing "Error: missing 'Content-Disposition' " on two different STIGs (Windows_Server_2016_STIG and Windows_Server_2019_STIG)

### Describe your Environment

```markdown
- Hosting: NREN
- Browser: Chrome 103.0.5060.134, Edge 103.0.1264.71
- OS: Windows 10
```

**Comment by cd-rite** [comment]
issue found to be due to insufficient sort buffer on deployment side. More generalized issue addressing error handling created: #728
