### ISSUE TITLE
Assigning a STIG to Assets in a Collection Removes all Assignments of that STIG from All Other Collections

### ISSUE THREAD

**Issue by david-a-army** [NUWCDIVNPT/stig-manager#756]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version of STIG Manager?

- [x] I am using the latest [Release](https://github.com/NUWCDIVNPT/stig-manager/releases).
- [ ] I am NOT using the latest [Release](https://github.com/NUWCDIVNPT/stig-manager/releases). I am aware that the first thing I will be asked to do is update the application so that I have the latest bugfixes.

### Where are you experiencing the issue?

- [ ] API
- [X] UI or other client
- [ ] Deployment
- [ ] Elsewhere

### Current Behavior

When using the 'Assign STIG' option from the Manage Collection screen or when updating Asset Assignment from the 'STIG Assignments' screen/modal, any STIG that is applied to assets within the collection will remove all other assignments of the checklist from all collections.

Based on testing, it appears that it will remove the assignment of the STIG from all assets within other collections regardless of the level of permissions that the user performing the assignment has to the other collections.

The issue does NOT appear to occur when a STIG is Assigned from the 'STIG Assignments' section on the 'Asset Properties' screen/modal (either when adding a new asset, or when updating an existing one), but only when the 'STIG Assignments' screen/modal is used.

Testing was performed on the previous version (1.2.13) and did not appear to be present.

### Expected Behavior

The STIG Assignment will be applied to the selected Asset(s) without impacting other assignments.

### Steps To Reproduce

1. Go to 'Manage' under a collection.
2. Click 'Assign STIG...' under the 'STIGs' pane on the Collection Management screen; OR
Select a Benchmark from the 'STIGs' pane on the Collection Management screen and click 'Modify...'; OR
Double-click on a Benchmark in the 'STIGs' pane on the Collection Management screen.
4. On the 'STIG Assignments' modal, select a benchmark, assign it to an asset.
5. Save the assignment on the 'STIG Assignments' screen.
6. Refresh the UI, and the assignments from other Collections will be gone.

### Can you provide screenshots, logs, or other useful artifacts?

Logs or other artifacts available upon request.

### Describe your Environment

```markdown
- Hosting: Self-hosted via nuwcdivnpt/stig-manager:latest-ironbank Docker Image
- Browser: Tested in Chrome, Firefox, and MS Edge
- OS: RHEL 7.9
- Node: v16.17.0 (provided by container image)
- npm: 8.15.0 (provided by container image)
```

**Comment by cd-rite** [comment]
Hi @david-a-army Thank you for the issue and detailed recreation procedure!
We have released a hotfix with a resolution to this issue. New containers with the -latest tag include our fix.  A point release (1.2.15) will be available this afternoon.

**Comment by david-a-army** [comment]
> Hi @david-a-army Thank you for the issue and detailed recreation procedure! We have released a hotfix with a resolution to this issue. New containers with the -latest tag include our fix. A point release (1.2.15) will be available this afternoon.

Thanks!  The quick response/fix is greatly appreciated.
