### ISSUE TITLE
FEATURE REQUEST: Expand Reporting Features

### ISSUE THREAD

**Issue by GISA-Beep** [NUWCDIVNPT/stig-manager#765]
Allow the ability to create a report/s and select content from existing reports within established collections.

I'd like for Managers/Owners have the ability to create an independent report (I'd request that a separate section like a collection be created - see .jpg) and have the ability to select reports from established collections and the option to select all collections.

![StigManager](https://user-images.githubusercontent.com/114646468/192964794-033f3ff9-6dc4-4a25-97ef-5ec90cfcefcb.JPG)

**Comment by csmig** [comment]
This feature is coming. Currently, the collection-level metrics report is being revised to provide more interactivity and download options. The new code has been developed to support the next iteration of reporting, which will give views across multiple collections.

Still a week or so out from releasing the new reporting interface, early preview below:
![image](https://user-images.githubusercontent.com/33138761/193026319-a9b2d225-7782-4446-9ab9-4bebfd6843a6.png)
