### ISSUE TITLE
POST /collections/{collectionId}/reviews/{assetId} -> CKL -> strict checks

### ISSUE THREAD

**Issue by cd-rite** [NUWCDIVNPT/stig-manager#79]
* This issue originally recorded in AZDO item 155:

POST of ckl file to /collections/{collectionId}/reviews/{assetId} 
is not performing strict asset check or benchmark check

CKL imports should (optionally?) check that they:
1. contain results that match the asset specified in the endpoint
2. contain results that match rules associated with that assets assigned STIGs.
3. if level 1 user is performing import, that user has grants that allow modifications to included ruleset.

**Comment by csmig** [comment]
Removing CKL import functionality
