### ISSUE TITLE
FEATURE REQUEST: add timestamp history and user to metrics report tab

### ISSUE THREAD

**Issue by alexisdafonseca** [NUWCDIVNPT/stig-manager#812]
Looking to have the timestamp and user history added to the metrics reports rather than having to click on the asset or stig to make it easier for the management to be able to view all on one screen.

**Comment by cd-rite** [comment]
Unfortunately, those fields don't really resolve to one answer.
History actions for Users and other properties is being considered with another issue. 
Thanks!
