### ISSUE TITLE
FEATURE REQUEST: The new Overview is great.  Would it be possible to add the capability to select STIGs to be shown in the same way?  This would be beneficial when working with NAVSEA CSCA tool.

### ISSUE THREAD

**Issue by denisekennedy** [NUWCDIVNPT/stig-manager#813]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by cd-rite** [comment]
HI @denisekennedy 
Can you explain a little more about what you are asking for? We already offer STIGs as a way to navigate and organize your view of the data in the new Metrics report, as well as Assets and Labels.
Thanks!

**Comment by denisekennedy** [comment]
We have identified labels for all of our assets. We would like to be able to filter the "Metrics Overview" results by Label so that we narrow our inventory, findings, and review ages to a targeted set of parameters, rather than export those specific STIG checklists and use a secondary application like eMASSter.  Please let me know if this helps.

**Comment by cd-rite** [comment]
Hi @denisekennedy 
Ah, ok.... I think I understand what you are looking for, and believe we already have that feature.
If you filter your view from the Navtree, those filters will apply to the overall Metrics report and all the data that it presents to you. You can filter by clicking the label icon for your Collection, and selecting what you want to see. The active label filters are indicated in the navtree and at the top of the Overview panel:
<img width="470" alt="image" src="https://user-images.githubusercontent.com/61710958/200622349-f607626b-1f85-472a-ba94-5438cb73a6fd.png">

If that's what you are looking for, I'll close this issue.
Thanks!

**Comment by cd-rite** [comment]
Closing this as functionality is already present. In the near-future Navigation update, this capability will be made a more distinctive part of the "Overview" panel header options.
Nav update tracked here: https://github.com/NUWCDIVNPT/stig-manager/issues/820
