### ISSUE TITLE
CVS Export on Assets Window not working

### ISSUE THREAD

**Issue by dtester1** [NUWCDIVNPT/stig-manager#815]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version of STIG Manager?

- [X] I am using the latest [Release](https://github.com/NUWCDIVNPT/stig-manager/releases).
- [ ] I am NOT using the latest [Release](https://github.com/NUWCDIVNPT/stig-manager/releases). I am aware that the first thing I will be asked to do is update the application so that I have the latest bugfixes.

### Where are you experiencing the issue?

- [ ] API
- [X] UI or other client
- [ ] Deployment
- [ ] Elsewhere

### Current Behavior

Under Collection -> Manage -> Assets Window --> CVS Export not exporting.

### Expected Behavior

Under Collection -> Manage -> Assets Window --> CVS Export -- Export CVS formatted file.

### Can you provide screenshots, logs, or other useful artifacts?

Discussed with another user today on our instance and the smae issue is occuring.

### Describe your Environment

```markdown
- Hosting:
- Browser:
- OS:
- Node:
- npm:
```

**Comment by cd-rite** [comment]
HI @dtester1 Thanks for this report. We are working on a fix, shooting for later in the week.

**Comment by cd-rite** [comment]
oops....hit the wrong button!
