### ISSUE TITLE
Replace Application Data fails with error.

### ISSUE THREAD

**Issue by vogtjob** [NUWCDIVNPT/stig-manager#843]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version of STIG Manager?

- [X] I am using the latest [Release](https://github.com/NUWCDIVNPT/stig-manager/releases).
- [ ] I am NOT using the latest [Release](https://github.com/NUWCDIVNPT/stig-manager/releases). I am aware that the first thing I will be asked to do is update the application so that I have the latest bugfixes.

### Where are you experiencing the issue?

- [X] API
- [ ] UI or other client
- [ ] Deployment
- [ ] Elsewhere

### Current Behavior

When using the Replace Application Data from a working configuration the following error occurs:

 "Cannot add or update a child row: a foreign key constraint fails (`stigman`.`stig_asset_map`, CONSTRAINT `FK_STIG_ASSET_MAP_2` FOREIGN KEY (`benchmarkId`) REFERENCES `stig` (`benchmarkId`) ON DELETE CASCADE ON UPDATE CASCADE)"

The import fails with only partial data imported.

### Can you provide screenshots, logs, or other useful artifacts?

Waiting for API response...
Starting import
Parsed appdata
Deleting: reviewHistory
Deleting: review
Deleting: userStigAssetMap
Deleting: stigAssetMap
Deleting: collectionGrant
Deleting: assetLabel
Deleting: collectionLabel
Deleting: collection
Deleting: asset
Deleting: userData
Inserting: userData chunk: 0
Inserting: collection chunk: 0
Inserting: collectionLabel chunk: 0
Inserting: collectionGrant chunk: 0
Inserting: asset chunk: 0
Inserting: assetLabel chunk: 0
Inserting: stigAssetMap chunk: 0
Cannot add or update a child row: a foreign key constraint fails (`stigman`.`stig_asset_map`, CONSTRAINT `FK_STIG_ASSET_MAP_2` FOREIGN KEY (`benchmarkId`) REFERENCES `stig` (`benchmarkId`) ON DELETE CASCADE ON UPDATE CASCADE)

### Describe your Environment

```markdown
- Hosting:
- Browser:
- OS:
- Node:
- npm:
```

**Comment by cd-rite** [comment]
Hi @vogtjob That error will occur when you are importing AppData that includes STIG Assignments for STIGs that do not exist on your system. It should be resolved by importing the DISA reference STIGs (the whole library, or just the ones you need) prior to importing the AppData file. 

Also, just FYI, that feature is marked "experimental" and is mainly used for testing and development, and should **never** be used to backup production data!

**Comment by vogtjob** [comment]
Thanks for that information.  It was being tried for a systems migration.

**Comment by cd-rite** [comment]
HI @vogtjob Ok! Some alternatives could include backing up the MySQL data volume and restoring it in the new deployment (assuming compatible MySQL instances), or exporting all your Assets/STIGs in xccdf or .ckl formats, and importing them in bulk into the new instance (Though this would not preserve Review History data).
