### ISSUE TITLE
FEATURE REQUEST: Exportable User List

### ISSUE THREAD

**Issue by mayszs** [NUWCDIVNPT/stig-manager#851]
**Is your feature request related to a problem? Please describe.**
Effective user managemnt is difficult within the STIGMAN System.

**Describe the solution you'd like**
Add a .csv export of the User Grants page.

**Describe alternatives you've considered**
The only way to get a user list from the GUI is to screenshot the page and run it through OCR to get a spreadsheet list of user accounts which can be compared with AD accounts to ensure user lists are accurate and current.

**Additional context**

**Comment by cd-rite** [comment]
Hi @mayszs Thanks for identifying this omission. Our intent is to offer .csv downloads of all of the data grids we present, but we missed that one.
