### ISSUE TITLE
FEATURE REQUEST: Additional User Account Fields/User Groups

### ISSUE THREAD

**Issue by mayszs** [NUWCDIVNPT/stig-manager#852]
**Is your feature request related to a problem? Please describe.**
In depleoyments where users of various organizations and roles will be accessing the same STIGMAN instanace it is difficult track which users below to which organization which ties into user grants.
It would also be advantagious to be able to assign user grants based on group membership.  For large deployments, with numerous users this would be significantly more efficient than having to manage individual users at the asset or collection level.

**Describe the solution you'd like**
Additional fields be available in User Grants to allow better tracking and user managment.  
Specifically - Site/Unit, email address and Location

**Describe alternatives you've considered**
If Labels could be made available to users and the labels would apply to any collection the user is granted access to it would work.

**Additional context**

**Comment by cd-rite** [comment]
User groups being implemented as part of #1289
