### ISSUE TITLE
Assets Not Sorting Alphabetically

### ISSUE THREAD

**Issue by sagansapien** [NUWCDIVNPT/stig-manager#853]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version of STIG Manager?

- [X] I am using the latest [Release](https://github.com/NUWCDIVNPT/stig-manager/releases).
- [ ] I am NOT using the latest [Release](https://github.com/NUWCDIVNPT/stig-manager/releases). I am aware that the first thing I will be asked to do is update the application so that I have the latest bugfixes.

### Where are you experiencing the issue?

- [ ] API
- [X] UI or other client
- [ ] Deployment
- [ ] Elsewhere

### Current Behavior

Collections > [collection1] > Assets

The list of assets is not sorted alphabetically.

### Expected Behavior

The list of assets is sorted alphabetically.

### Steps To Reproduce

Expand 

Collections > [collection1] > Assets

### Can you provide screenshots, logs, or other useful artifacts?

![Picture1 - Copy](https://user-images.githubusercontent.com/53829030/205354237-8d66b675-79ea-4913-9b37-566bc0f81675.png)

### Describe your Environment

```markdown
Windows Server
binary executable
Microsoft Edge
```

**Comment by cd-rite** [comment]
Thanks, @sagansapien I am able to repeat this issue. We will address it!
Right now, the ordering seems to be going by underlying AssetID, not the name of the Asset.
This only seems to be affecting the top level Collections->Assets node of the NavTree. Assets listed in the expanded STIG node of the Navtree are ordered properly by their name.
