### ISSUE TITLE
Reject status not changing

### ISSUE THREAD

**Issue by alexisdafonseca** [NUWCDIVNPT/stig-manager#866]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version of STIG Manager?

- [ ] I am using the latest [Release](https://github.com/NUWCDIVNPT/stig-manager/releases).
- [X] I am NOT using the latest [Release](https://github.com/NUWCDIVNPT/stig-manager/releases). I am aware that the first thing I will be asked to do is update the application so that I have the latest bugfixes.

### Where are you experiencing the issue?

- [ ] API
- [X] UI or other client
- [ ] Deployment
- [ ] Elsewhere

### Current Behavior

When rejecting stig collection reviews, the function works but tends to stop allowing rejections after about 60 assets.

After a few hours users are able to reject per each check again but keep falling into the issue of the reject function not working after they hit that number of assets.

### Expected Behavior

ability to reject as many assets as possible at a time

### Describe your Environment

```markdown
- Hosting:
- Browser:
- OS:
- Node:
- npm:
```

**Comment by cd-rite** [comment]
Implementation for setting the Reject status for multiple reviews changed significantly with Release 1.2.21. Please update and inform us if you still experience this issue!  Thanks!
