### ISSUE TITLE
FEATURE REQUEST: Creating a copy option in STIG Manager

### ISSUE THREAD

**Issue by dtester1** [NUWCDIVNPT/stig-manager#870]
**Is your feature request related to a problem? Please describe.**
Issue with Continuous vs Snap Shot in time

**Describe the solution you'd like**
Create an option for snapshot in time.

Possible copy options:
Copy asset just like transfer of Asset (currently present).
Copy all assets associated to a STIG to another collection.
Copy whole collection.

**Describe alternatives you've considered**
Only current alternative is a manual process of exporting and reimporting data to another collection.

**Additional context**
Definitely the continuous vs snapshot in time needs discussed further.

**Comment by cd-rite** [comment]
Thanks, @dtester1 We will be investigating the effort and best approach for this!

**Comment by cd-rite** [comment]
This feature request is now being tracked in issue #954
