### ISSUE TITLE
FEATURE REQUEST: Under Reporting > Metrics view, the dashboard shows Unassessed but can't view/export data

### ISSUE THREAD

**Issue by bbcallison** [NUWCDIVNPT/stig-manager#872]
**Is your feature request related to a problem? Please describe.**
Being able to further review unassessed assets quickly from this view would be very helpful.  We like having the Unassesed % in dashboard, but would like to export data to contact those responsible for execute STIGs. You can do that on all other fields but this one.

**Describe the solution you'd like**
Add Unassessed to the Aggregations table of the Metrics view.  Currently has other data sets but not Unassessed. Would like to see this in all 3 tabs (stigs, labels, assets)

**Describe alternatives you've considered**
Using the various collection review tabs, but I really like this Metrics report.  

**Additional context**
may be considered a problem/bug, but submitting as feature request.

**Comment by cd-rite** [comment]
Hi @bbcallison I don't think I follow what you are looking for.... The "Unassessed" percentage would just be 100 minus the Assessed percentage, which is already displayed in the panels  you mentioned, and in the exported data.  Could you explain a bit more?  Thanks!

We have a little more about what we mean by "Assessed" here in our documentation, in case it is useful: https://stig-manager.readthedocs.io/en/latest/user-guide/user-guide.html#metrics-report-workspace

**Comment by bbcallison** [comment]
We're really just looking to dig into the unassessed data and take quick action to ensure we are properly review everything, especially the unassessed CAT I findings.  I'd recommend a better/cleaner way to quickly visualize those unassessed/not reviewed assets instead of drilling into assessed view, sorting by % , etc. From a risk perspective, I also wouldn't mind an Unassessed CAT I/CAT II/CAT III metric under the  Metrics Overview > Findings area as well.

**Comment by cd-rite** [comment]
Hi @bbcallison 
If you used the "Labels" feature to designate responsibility, you could use that view to contact those who most need to address something.  You can export a .csv from each of the Metrics panels. 
Our latest release also includes Breakouts for Assessments by Severity, available in the "Detailed" .csv metrics download.  This might help you determine STIGs with many CAT Is you want addressed. 

Are you suggesting that anything Not Reviewed should automatically count as Open, as far as the Metrics are concerned?  That's arguably the way it should be, but that should probably be the start of a new Issue. 
Other than that I'm not sure if there what we can address specifically in the Metrics or any other status report we have at present, but what you are suggesting may be relevant to a Review Aging Report, which has it's own issue.
Thank you!
