### ISSUE TITLE
FEATURE REQUEST: max characters in Review Status Text

### ISSUE THREAD

**Issue by alexisdafonseca** [NUWCDIVNPT/stig-manager#877]
total max characters is 255, Looking to have the max characters set to 500

**Comment by cd-rite** [comment]
Thanks, @alexisdafonseca We should be able to do this. For now, the next version will have an indicator (text box turns red, button disabled) when users exceed the limit.

**Comment by cd-rite** [comment]
Dev note:
Will require changes to:
MySQL:
db migration - Review table, statusText column size to varchar(512)
UI:
text field validation, make input box a bit more roomy
API Spec:
Wherever the status object is specified, the "text" property will need to be redefined with a new data type.
From String255Nullable to, say String512Nullable (this type does not exist yet)
