### ISSUE TITLE
Unable to export collection, error "l is null"

### ISSUE THREAD

**Issue by steelwing** [NUWCDIVNPT/stig-manager#884]
In our STIG Manager instance, on the RHEL 7 STIG in the "collection review" screen, we get the following error when we try to export the collection of STIGs:
l is null
handler@https://<servername>:54000/......./stig-manager.min.js:144:4092
What do we do with this?

**Comment by steelwing** [comment]
Further details:  In some places where we can mass-export STIGs from STIG Manager, we get a specific error for RHEL 7 STIG for some of our hosts:  missing Content Disposition.  What does that mean, and how do we fix it?  It's only affecting STIG information for a few of our hosts.

**Comment by cd-rite** [comment]
Hi @steelwing Can you please provide some more information?
What version of STIGMan OSS are you running? Can you provide the error response for the request from Chrome Dev tools?
Do your API logs indicate a response was sent, or an error?  Are you using a proxy? Do it's logs indicate a proper response was sent?
Are you successfully exporting RHEL 7 .ckls for other Assets? Are you able to export single .ckls from the Asset Review workspace for RHEL 7 on an asset that is triggering your error in the bulk-export options?
More info like this will help us diagnose the issue. Thanks.

**Comment by steelwing** [comment]
What version of STIGMan OSS are you running? - 1.2.13
Can you provide the error response for the request from Chrome Dev tools? - 500 Internal Server Error, from stig-manager.min.js:143.
Do your API logs indicate a response was sent, or an error? - Error, as shown above.
Are you using a proxy? - No proxy
Are you successfully exporting RHEL 7 .ckls for other Assets? - This specifically affects only the RHEL 7 STIG for 7 of our hosts.  We can export (singly or bulk) any other STIGs for the affected assets, and we can export RHEL 7 STIGs for any asset besides the 7 affected.
Are you able to export single .ckls from the Asset Review workspace for RHEL 7 on an asset that is triggering your error in the bulk-export options? - No

**Comment by cd-rite** [comment]
Hi @steelwing 
Please update to the latest version of STIGMan and try again. We have made significant changes since 1.2.13, including in our approach to .ckl exports.

**Comment by steelwing** [comment]
It's going to take a while for me to be able to update.  We're on a disconnected network, so getting the updated docker stuff is a significant hassle.

**Comment by steelwing** [comment]
I just learned that a coworker was able to discover that all the affected RHEL7 STIGs had at least one STIG item with very long entries in their details or comments fields (over 100 lines long).  Once the very long entries were truncated to under 100 lines, the exports started working again.  So that's your fix, there. :)

**Comment by cd-rite** [comment]
Hi @steelwing Ahh, ok. That's a good clue. The issue is likely in your database config... MySQL has a very small  `sort_buffer_size` set by default (256k, I believe). I'd suggest trying different values, starting with 2M (2097152) or even up to 64M, if you need those very long comments. 
We mention this in the [Configure MySQL](https://stig-manager.readthedocs.io/en/latest/installation-and-setup/db.html#configure-mysql) section of our documentation. Over 64M is probably excessive, I'll adjust it down in our next docs update.
