### ISSUE TITLE
FEATURE REQUEST: Grid Selections

### ISSUE THREAD

**Issue by tylerforajter** [NUWCDIVNPT/stig-manager#886]
**Is your feature request related to a problem? Please describe.**

In some grids, a mis-click will cause all selected items to be deselected.  This is frustrating when trying to select many things in a grid, because one mis-click will wipe out your progress.

**Describe the solution you'd like**

A mis-click should not deselect anything.

**Describe alternatives you've considered**

Changing grids to a different format. 

**Additional context**

**Comment by cd-rite** [comment]
Grid checklist behavior has been changed in latest releases, or in some cases grid checklists replaced with new interface
