### ISSUE TITLE
Import CKL Error - Empty Import

### ISSUE THREAD

**Issue by SpaceBass11** [NUWCDIVNPT/stig-manager#896]
Import CKL error causing empty results. These results are reproduced with my account on a custom test collection I am owner of.

Under left side bar "Collections > My Collection > Manage". Then under the "Assets" window pane. I click "Import CKL or XCCDF..."

From there I click "Add files to queue..." and select my completed CKL. It shows the results in the opened window pane. I check mark the CKL and click continue.

It parses the file and brings me to the next page showing my CKL results properly. I click "Add to Collection".

At this point I get a permissions error that pops up. Screenshots are attached. After clicking OK on the error it closes the import window pane.

After this, you can see in the screenshots, the imported CKL has no saved, submitted, accepted, rejected.

If you click on the STIG or asset drop-down in the left side bar now that the CKL is imported you see everything as empty as if nothing imported.

EDIT1: Even if I create an empty asset, assign a STIG, then go to that asset page and try "Importing Results" I will get this same error and nothing imports.

![1-Import-Review](https://user-images.githubusercontent.com/8725850/212710811-104eba95-2e11-4eae-97d1-62433c158187.png)
![2-Importing-Results-Error](https://user-images.githubusercontent.com/8725850/212710816-fbda3b24-ff81-4d60-b596-96bb7a6dd5fb.png)
![3-Importing-Results-Error](https://user-images.githubusercontent.com/8725850/212710817-709eaa06-d141-4c0e-bcd3-e89623d62228.png)
![4-Imported-Results-Empty](https://user-images.githubusercontent.com/8725850/212710819-0b40f67b-54c3-4300-860c-af56192d3b08.png)
![5-Empty-Import](https://user-images.githubusercontent.com/8725850/212711659-1a927ee4-ad30-473e-a2f3-96993f785f42.png)

**Comment by cd-rite** [comment]
Hi @SpaceBass11 
Are the contents of that .ckl file especially large? Are you able to successfully import other .ckl files?
If that's the case, I think it's likely you need to increase the size of your deployments `STIGMAN_API_MAX_JSON_BODY` [environment variable](https://stig-manager.readthedocs.io/en/latest/installation-and-setup/environment-variables.html). Our next release will include a larger default value for this (31457280). 
If you have deployed with a proxy, the problem could also be a configuration there (For example, the client_max_body_size  in nginx).
Feel free to re-open the issue with more information (API logs, Chrome Dev tool errors, the problematic file, etc.) if the above does not resolve your issue.
