### ISSUE TITLE
API: parameter validation for "revision" not working for various requests

### ISSUE THREAD

**Issue by cd-rite** [NUWCDIVNPT/stig-manager#9]
expected: Validator should only allow properly formed revision strings or "latest."
seen: request with rev string of "current" was passed on to api service, which returned error

**Comment by csmig** [comment]
The latest oas-tools library (2.1.7) has very a buggy validator. I've patched it in 05299f880fad4cbbd0992deb04be3d2259b74bec to work better, but I'm concerned that the implementation was so obviously wrong. At some point we should evaluate our dependency on oas-tools.
