### ISSUE TITLE
Modify user grants

### ISSUE THREAD

**Issue by alexisdafonseca** [NUWCDIVNPT/stig-manager#905]
Inside the collections, it would be beneficial to have a modify user grants button to change a user if their permissions have changed within that collection.

**Comment by cd-rite** [comment]
Hi @alexisdafonseca I think we already do what you are asking....Just double-click on the User you want to change, and pick the new grant from the pulldown:
<img width="269" alt="image" src="https://user-images.githubusercontent.com/61710958/213514031-ab37f954-101d-4dd8-a321-ad9c2c54f0c8.png">
