### ISSUE TITLE
STIGMAN Watcher Not Following Import Settings

### ISSUE THREAD

**Issue by tylerforajter** [NUWCDIVNPT/stig-manager#913]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version of STIG Manager?

- [X] I am using the latest [Release](https://github.com/NUWCDIVNPT/stig-manager/releases).
- [ ] I am NOT using the latest [Release](https://github.com/NUWCDIVNPT/stig-manager/releases). I am aware that the first thing I will be asked to do is update the application so that I have the latest bugfixes.

### Where are you experiencing the issue?

- [ ] API
- [X] UI or other client
- [ ] Deployment
- [ ] Elsewhere

### Current Behavior

I am experiencing some strange behavior.  One of my collections is importing just fine, and another is having the issue below.  

These are my collection settings:
![image](https://user-images.githubusercontent.com/100237457/215103569-0ea5ab3a-4441-4fe0-b5b4-b6319dd23b3c.png)
According to these settings, newly imported reviews should be set to "Submitted" if possible.  However, they are not being set to submitted, they are being set to "saved".  I believe that the reviews meet all the criteria to be "submitted" see below:
![image](https://user-images.githubusercontent.com/100237457/215103982-89cab7e8-e16c-44fc-bd6e-3b6e59a45cc9.png)
![image](https://user-images.githubusercontent.com/100237457/215104028-7ad807c3-83dd-43dc-bce5-af54e5735221.png)

### Expected Behavior

Expected behavior would be for the review to be set to submitted upon import by STIGMAN watcher. 

### Steps To Reproduce

1. Create two collections 
2. Apply the same import settings to both collections
3. use stigman watcher to import data into both collection
4. see if one collection submits and one collection does not. 

### Can you provide screenshots, logs, or other useful artifacts?

See above.

**Comment by tylerforajter** [comment]
Follow up: I placed the same file show above in the current behavior section in a directory that imports to the working collection and it worked!
![image](https://user-images.githubusercontent.com/100237457/215109504-7ee044cf-2cc6-47e7-b595-eed00d57bb56.png)
So there must be some bug that the import settings are not working properly for all collections.

**Comment by cd-rite** [comment]
Hi @tylerforajter 
Hmmm I suspect there must be some other difference in the collection.... 
There are collection settings defining the requirements to submit a review.... do both collections have the same requirements there as well?
Do you get the same behavior if you import the same .ckl file via the UI in the different collections? 
Does the Watcher user have the same grant level in both collections?

**Comment by tylerforajter** [comment]
Hey @cd-rite!

Yes, the collection settings are identical to each other.  Left me scratching my head LOL

If I import using the UI, it does the proper "Submit" on any collection.

And watcher does have the same grant level on all collections.

**Comment by csmig** [comment]
>> 

> If I import using the UI, it does the proper "Submit" on any collection.

That seems to indicate a bug in Watcher, not STIG Manager? The reference web app and Watcher share the same CKL parsing and review POSTing code, so results should match. But, that code needs the collection settings to calculate which status to use for each review in the POST body. There could be a bug in Watcher around passing the collection settings to the parse/POST code, that's where I will look.

Perhaps move this issue to the Watcher repo?

**Comment by csmig** [comment]
Please provide the responses to `GET /collection/{collectionId}` for both collections. The output should look like this example:
```
{
  "collectionId": "1",
  "name": "Quahog RDTE-Windows",
  "description": null,
  "settings": {
    "fields": {
      "detail": {
        "enabled": "always",
        "required": "always"
      },
      "comment": {
        "enabled": "findings",
        "required": "findings"
      }
    },
    "status": {
      "canAccept": true,
      "resetCriteria": "result",
      "minAcceptGrant": 3
    },
    "history": {
      "maxReviews": 15
    }
  },
  "metadata": {
    "importOptions": "{\"autoStatus\":\"submitted\",\"unreviewed\":\"never\",\"unreviewedCommented\":\"informational\",\"emptyDetail\":\"ignore\",\"emptyComment\":\"ignore\",\"allowCustom\":true}"
  }
}
```

**Comment by cd-rite** [comment]
Resolution: Certificate issue on host machine was preventing update to latest Watcher version.
