### ISSUE TITLE
Keycloak container won't start after upgrading rhel8 kernel, prior kernel had no issues

### ISSUE THREAD

**Issue by st3v1s** [NUWCDIVNPT/stig-manager#932]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version of STIG Manager?

- [ ] I am using the latest [Release](https://github.com/NUWCDIVNPT/stig-manager/releases).
- [X] I am NOT using the latest [Release](https://github.com/NUWCDIVNPT/stig-manager/releases). I am aware that the first thing I will be asked to do is update the application so that I have the latest bugfixes.

### Where are you experiencing the issue?

- [ ] API
- [ ] UI or other client
- [X] Deployment
- [ ] Elsewhere

### Current Behavior

The following docker-compose.yml successfully starts up 3 containers when running on RHEL8 kernel 4.18.0-425.3.1.el8.x86_64.

docker-compose.yml:

version: "2.1"
services:
  auth:
    image: nuwcdivnpt/stig-manager-auth
    ports:
      - 8080:8080
  db:
    image: mysql:8.0
    ports:
      - 50001:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpw
      - MYSQL_USER=stigman
      - MYSQL_PASSWORD=stigman
      - MYSQL_DATABASE=stigman
    cap_add:
      - SYS_NICE

  api:
    image: nuwcdivnpt/stig-manager:latest
    environment:
      - STIGMAN_OIDC_PROVIDER=http://IP/realms/stigman
      - STIGMAN_CLASSIFICATION=U
      - STIGMAN_DB_HOST=IP
      - STIGMAN_DB_PORT=50001
      - STIGMAN_DB_PASSWORD=stigman
      - STIGMAN_INIT_IMPORT_STIGS=true
      - STIGMAN_CLIENT_OIDC_PROVIDER=http://IP/realms/stigman
    init: true
    ports:
      - 54000:54000
    depends_on:
      - auth
      - db
I bring down the containers with command: docker compose stop and run yum update --security, reboot, run docker compose start
I get an error with the auth container regarding "Could not parse MediaTypes"

Docker Engine - Community
Client/Server Version: 20.10.21
API: 1.41
RHEL8.7, fapolicy disabled, selinux enforcing

Thoughts on what it could be? I have tried removing the images/containers and importing images and starting up but no luck.

### Expected Behavior

Upon executing docker compose start, I expect all 3 containers to start up with no problem.

### Describe your Environment

```markdown
- Hosting:
- Browser: Chrome
- OS: RHEL8
- Node:
- npm:
```

**Comment by cd-rite** [comment]
Hi @st3v1s We can't really provide too much guidance here, and this would be better taken up directly with Keycloak.  We offer that particular container as a convenience but can't guarantee it is appropriate for all circumstances.  Artifacts to build that image locally are available here, if you want to experiment: https://github.com/NUWCDIVNPT/stig-manager-auth  
All the stigman-auth container does is import a realm with some demo users, and set the admin user/password. You might try running vanilla Keycloak to see if it comes up in your environment, or building off of one of DoD Iron Bank's Keycloak offerings, to see if it works in your new environment.  If you find something that we can address please feel free to re-open the issue and let us know! Thanks!

**Comment by cd-rite** [comment]
Our other demo orchestration is here.... It includes a commented out line that you could move(uncommented) into your current docker-compose file: https://github.com/NUWCDIVNPT/stigman-orchestration/blob/2865b1a14074bd43e16a13ebc99a420f6ff76398/docker-compose.yml#L37-L38
