### ISSUE TITLE
DEL of reviews returns 204, and does not delete the review.

### ISSUE THREAD

**Issue by cd-rite** [NUWCDIVNPT/stig-manager#94]
**Bug Location**

I found a bug in the:
- [x] API
- [ ] UI
- [ ] Elsewhere (Please specify)

**Bug Description:**

request to DEL collections/{collectionId}/reviews/{assetId}/{ruleId}
always returns a 204 even if review exists, and does not delete the review (Except in case of test user collectionCreator, which has no permissions on the collection. Properly returns a 403 to that user.)

sample request:

curl --location --request DELETE 'localhost:64001/api/collections/21/reviews/42/SV-106179r1_rule?elevate=false&projection=rule&projection=history&projection=stigs' --header 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJGSjg2R2NGM2pUYk5MT2NvNE52WmtVQ0lVbWZZQ3FvcXRPUWVNZmJoTmxFIn0.eyJleHAiOjE2NzAzOTQzNDcsImlhdCI6MTYwNTYzMTQxMiwiYXV0aF90aW1lIjoxNjA1NTk0MzQ3LCJqdGkiOiJkYWY4Yjc0MS03M2QxLTRlYmEtOTZhZi1mODU1YWIwYmQyMjYiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODAvYXV0aC9yZWFsbXMvc3RpZ21hbiIsImF1ZCI6WyJyZWFsbS1tYW5hZ2VtZW50IiwiYWNjb3VudCJdLCJzdWIiOiJlYjk2NWQxNS1hYTc4LTQzZmMtYTJhNi0zZDg2MjU4YzFlZWMiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJzdGlnLW1hbmFnZXIiLCJub25jZSI6IjczOTM3YmUzLTRjY2MtNGZhNy04MjAyLTQ1Njg1NTIzZGQyYyIsInNlc3Npb25fc3RhdGUiOiI1YWMyYTkzOC0xMDc0LTRlNmEtOGM0Yi1lODNlNGU3ZDc2M2IiLCJhY3IiOiIwIiwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbImNyZWF0ZV9jb2xsZWN0aW9uIiwiYWRtaW4iLCJ1c2VyIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsicmVhbG0tbWFuYWdlbWVudCI6eyJyb2xlcyI6WyJ2aWV3LXVzZXJzIiwicXVlcnktZ3JvdXBzIiwicXVlcnktdXNlcnMiXX0sImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoib3BlbmlkIHN0aWctbWFuYWdlcjpjb2xsZWN0aW9uIHN0aWctbWFuYWdlcjpzdGlnOnJlYWQgc3RpZy1tYW5hZ2VyOnVzZXI6cmVhZCBzdGlnLW1hbmFnZXI6b3Agc3RpZy1tYW5hZ2VyOnVzZXIgc3RpZy1tYW5hZ2VyOnN0aWciLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6InN0aWdtYW5hZG1pbiJ9.IOk6RLhBwX8o29dmAC7QeSzr86B5w8C8gkyetn5uOhhgh-aEjWJSqLk74WvLjwfKnYgonfAMm-gbdiACFwMd7u7O5wNUNV5EQO8-6JKSUYyTvujS5NMY7rO-QtgskvKWvB8Vyrm33DvcUon-Kh_6LeSujcNczadN6oDbe-j1A1w'

**Expected behavior**
If user has proper grants, return code 200 and JSON representation of deleted review.
OR, remove API endpoint to delete reviews.

TEST NOTE:
Test for proper behavior currently in collection, but commented out starting with note:
"//START AZDO #154"

**Comment by cd-rite** [comment]
Now that we support a Not_Reviewed result, perhaps a DEL action against a review is no longer needed?

Or, could be used as a shortcut for setting a Review to Not_Reviewed, without having to provide a body, etc.

**Comment by csmig** [comment]
The result 'notchecked' is distinct from the notion that a review does not exist. This endpoint is still required and should be implemented.
