### ISSUE TITLE
FEATURE REQUEST: Import of Benchmark Data from Redseal

### ISSUE THREAD

**Issue by mayszs** [NUWCDIVNPT/stig-manager#953]
I am trying to evaluate the possibility of using XCCDF exported out of Redseal as a semi-automated data source for STIG data.  
The issue I am running into is that the XCCDF file appears to have vulnerability data for rules that are not in the STIG in question so I get an error when importing into STIGMan.  

I am able to create a checklist in STIG Viewer, import the XCCDF data, save the checklist as a CKL then import the CKL into STIGMAN but this would become a rather time consuming process for every networking device.
Would it be possible to provide you with the XCCDF as output from Redseal and a copy of the CLK for evaluation to see if there is a way for STIGMan to import that the applicable vulnerability checks and ignore any superfluous data.

Being that NAVSEA requires Redseal be utilized on it's networks this DataSource is widly available so the ability to ingest these XCCDF files would likely save the Warfare Centers hundreds if not thousands of hours of labor per year compared to the manual process used by most division.

**Comment by mayszs** [comment]
The primary use case for this data would be for audit/A&A validation requirements.
The intent would be for the Redseal Benchmarks to be imported into a separate collection whre reporting metrics are generated comparing the results from the Redseal STIGs with the Production SITGs
For each asset and STIG the following would be needed:
1. Count of Open Findings in Redseal
2. Count of Open Findings in Production
3. Count of N/A Findings in Redseal
4. Count of N/A Findings in Production
5. Count of NF Findings in Redseal
6. Count of NF Findings in Production
7. Accuracy Percentage

Accuracy percentage would continue to roll up by asset then the overall "Redseal Collection"

**Comment by cd-rite** [comment]
Redseal's xccdf output was...untraditional. They would need to better conform to the NIST standard, and reference real STIGs for us to proceed with this. But we will keep this in mind, please reopen if they make changes!
Thanks!
