### ISSUE TITLE
Create new Reviews from existing Reviews when RuleIds change but Rule "version" and check content match

### ISSUE THREAD

**Issue by cd-rite** [NUWCDIVNPT/stig-manager#957]
Problem:
New STIG Revisions often change Rule IDs without changing the check content in that Rule from the previous Revision. 
This leads to the need to re-review Rules for new Revisions even if they do not actually need to be re-evaluated (ie. Reviews are just manually copied to a Review for the new RuleId, or a whole re-evaluation takes place when it was not actually necessary, since the Check Content for the two RuleIDs was identical).

Solutions Considered:

**1. Create new Reviews with the new RuleIds under the hood when STIGs are updated.**
2. Associate Reviews with Check Content Digest
3. Associate Reviews with Check Content Digest and "STIG ID" (ie. "version") found in each Rule.
4. Alter the *presentation* of Reviews so that existing Reviews are used as a transparent (but identifiable) source for Reviews for other Rules based on matching STIG ID and Check Content Digest identifiers. "Distinct" Reviews for a new Rule ID would take precedence over any "common" Review that is only associated via Check Digest/STIG ID.

Solution 1 is the most favored solution at the moment.

Preserve:
Originating Review's timestamps, content, userIds, etc.

**Comment by dtester1** [comment]
This DISA Quarterly STIG Release is showing the importance of this feature coming to fruition.  One of the manual STIGS that got affected by this quarters renumbering is affecting us for over 75 assets.

**Comment by cd-rite** [comment]
The 1.3.5 release is planned for Monday with this behavior! Actual deployment schedules may vary, though!
