### ISSUE TITLE
FEATURE REQUEST: Layout customization for Rules

### ISSUE THREAD

**Issue by trevor-vaughan** [NUWCDIVNPT/stig-manager#962]
**Is your feature request related to a problem? Please describe.**

The current rule layout appears to allow for resizing existing internal content boxes but not rearranging the layout on the screen.

**Describe the solution you'd like**

I would like to be able to rearrange internal content boxes as well as resizing them.

**Describe alternatives you've considered**

None

**Additional context**

Using Chrome 111.0.5563.110

**Comment by cd-rite** [comment]
Our framework does not facilitate rearranging content panels, and this type of feature is out of scope with our current tasking. 
Thank you for the suggestion, though! What changes are you looking to make? 
Closing as not planned for now.
