### ISSUE TITLE
FEATURE REQUEST: Adjustable font size

### ISSUE THREAD

**Issue by trevor-vaughan** [NUWCDIVNPT/stig-manager#963]
**Is your feature request related to a problem? Please describe.**

The font used in the descriptive text is too small for high resolution displays.

**Describe the solution you'd like**

I would like to be able to adjust the font size via user preferences.

**Describe alternatives you've considered**

CSS overrides using browser tools. This works, but it's not really portable to other users with similar issues.

**Additional context**

Relates to #618 

Using Chrome 111.0.5563.110

**Comment by csmig** [comment]
Does increasing the zoom factor of the browser window address your concern? It will proportionately zoom everything and remember the last zoom setting for that origin.

**Comment by trevor-vaughan** [comment]
@csmig I tried that and zooming in makes everything else on the screen largely unusable.

I took a look a look at the difference between the UI and the RTD docs and tried changing the body text from `11px`  to `16px` to match RTD and things were vastly improved.

Likewise, if that is too large for someone, zooming out makes the interface more usable so I think that it's a reasonable change.

**Comment by cd-rite** [comment]
Hi @trevor-vaughan Browser zoom is our intended solution for users that need larger text. Our layout flows quite comfortably to 150%+ without issue. Beyond that, the NavTree and Chart panels can both be collapsed to make more room for the grid displays, and provides room for up to 200%+ zoom. You can also turn off columns in grids if they are cluttering your view.
Can you provide screenshots that show further issues?
Closing as not planned for now.
