### ISSUE TITLE
Iron Bank 1.3.4 container crashing with NODE_EXTRA_CA_CERTS

### ISSUE THREAD

**Issue by vogtjob** [NUWCDIVNPT/stig-manager#980]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version of STIG Manager?

- [X] I am using the latest [Release](https://github.com/NUWCDIVNPT/stig-manager/releases).
- [ ] I am NOT using the latest [Release](https://github.com/NUWCDIVNPT/stig-manager/releases). I am aware that the first thing I will be asked to do is update the application so that I have the latest bugfixes.

### Where are you experiencing the issue?

- [ ] API
- [ ] UI or other client
- [X] Deployment
- [ ] Elsewhere

### Current Behavior

Using the environment variable NODE_EXTRA_CA_CERTS in the IronBank:1.3.4 container gives:

"node[1]: ../src/node.cc:1026:std::unique_ptr<node::InitializationResult> node::InitializeOncePerProcess(const std::vector<std::__cxx11::basic_string<char> >&, node::ProcessFlags::Flags): Assertion `crypto::CSPRNG(nullptr, 0).is_ok()' failed."

I was able to get the container running using NODE_TLS_REJECT_UNAUTHORIZED='0', but would prefer the failing option.   

I've used the NODE_EXTRA_CA_CERTS in previous versions with the same certificate file without issues.

### Expected Behavior

Container runs with NODE_EXTRA_CA_CERTS environment variable.

### Describe your Environment

```markdown
- Hosting:
- Browser:
- OS:RHEL 8.7 utilizing podman.
- Node:
- npm:
```

**Comment by cd-rite** [comment]
Hi @vogtjob Thanks, we'll check this out.  Are you pulling directly from Iron Bank, or pulling our Iron Bank-based image from Docker Hub?

**Comment by vogtjob** [comment]
I pulled the image from Docker Hub. Thanks.

**Comment by cd-rite** [comment]
HI @vogtjob We've pushed a new image to Docker Hub using the larger UBI provided by Iron Bank that does not have this issue, and retagged appropriately.
I've also opened an Issue with Iron Bank mentioning this problem with their "slim" node base image, which we would prefer to use in the future.
Thanks for letting us know about this issue!
