### ISSUE TITLE
Will this work with cisco iosxe switches?

### ISSUE THREAD

**Issue by hhha7x** [NUWCDIVNPT/stig-manager#984]

**Comment by cd-rite** [comment]
Hi @hhha7x Just to clarify, STIG Manager is a repository for your evaluation results, it does not evaluate STIGs itself. 
That said, I think there are DISA STIGs for Cisco switches, and STIG Manager will let you assign and track results you've imported (in .ckl or XCCDF formats) or manually evaluated in the app just fine.
